% /Applications/Isabelle2025.app/contrib/spass-3.8ds-2/x86_64-darwin/SPASS -Isabelle=1 -TimeLimit=5 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5231022_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:43:58.916
begin_problem(isabelle).

list_of_descriptions.
name({**}).
author({**}).
status(unknown).
description({**}).
end_of_list.

list_of_symbols.
functions [(minus_minus_nat, 0), (minus_minus_nat1, 1), (minus_minus_nat2, 2), (one_one_nat, 0), (plus_plus_nat, 0), (plus_plus_nat1, 1), (plus_plus_nat2, 2), (plus_plus_num, 2), (plus_plus_a, 2), (times_times_nat, 0), (times_times_nat1, 1), (times_times_nat2, 2), (zero_zero_nat, 0), (suC, 1), (numeral_numeral_nat, 1), (aa_nat_nat, 2), (aa_nat_fun_nat_nat, 2), (fFalsE, 0), (fTruE, 0), (x, 0), (y, 0)].
predicates [(abel_semigroup_nat, 1), (comm_monoid_nat, 2), (comm_m2051353214ms_nat, 2), (monoid_nat, 2), (monoid_axioms_nat, 2), (semigroup_nat, 1), (groups1056228905et_nat, 2), (bot_bot_bool, 0), (ord_less_nat, 2), (ord_less_eq_nat, 2), (pp, 1)].
weights [(suC, 1), (one_one_nat, 1), (plus_plus_num, 1), (zero_zero_nat, 1), (numeral_numeral_nat, 1), (plus_plus_nat2, 2), (times_times_nat2, 2), (times_times_nat1, 4), (plus_plus_nat1, 4), (minus_minus_nat2, 4), (ord_less_nat, 4), (ord_less_eq_nat, 4), (minus_minus_nat1, 8), (plus_plus_nat, 8), (times_times_nat, 8), (minus_minus_nat, 16)].
sorts [fun_nat_fun_nat_nat, fun_nat_nat, booL, nuM, naT, a, iii].
% classes [].
end_of_list.

list_of_declarations.
function(minus_minus_nat, fun_nat_fun_nat_nat).
function(minus_minus_nat1, (naT) fun_nat_nat).
function(minus_minus_nat2, (naT, naT) naT).
function(one_one_nat, naT).
function(plus_plus_nat, fun_nat_fun_nat_nat).
function(plus_plus_nat1, (naT) fun_nat_nat).
function(plus_plus_nat2, (naT, naT) naT).
function(plus_plus_num, (nuM, nuM) nuM).
function(plus_plus_a, (a, a) a).
function(times_times_nat, fun_nat_fun_nat_nat).
function(times_times_nat1, (naT) fun_nat_nat).
function(times_times_nat2, (naT, naT) naT).
function(zero_zero_nat, naT).
function(suC, (naT) naT).
function(numeral_numeral_nat, (nuM) naT).
function(aa_nat_nat, (fun_nat_nat, naT) naT).
function(aa_nat_fun_nat_nat, (fun_nat_fun_nat_nat, naT) fun_nat_nat).
function(fFalsE, booL).
function(fTruE, booL).
function(x, a).
function(y, a).
predicate(abel_semigroup_nat, fun_nat_fun_nat_nat).
predicate(comm_monoid_nat, fun_nat_fun_nat_nat, naT).
predicate(comm_m2051353214ms_nat, fun_nat_fun_nat_nat, naT).
predicate(monoid_nat, fun_nat_fun_nat_nat, naT).
predicate(monoid_axioms_nat, fun_nat_fun_nat_nat, naT).
predicate(semigroup_nat, fun_nat_fun_nat_nat).
predicate(groups1056228905et_nat, fun_nat_fun_nat_nat, naT).
predicate(ord_less_nat, naT, naT).
predicate(ord_less_eq_nat, naT, naT).
predicate(pp, booL).
end_of_list.

list_of_formulae(axioms).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(plus_plus_nat, B_1), plus_plus_nat1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(plus_plus_nat1(B_1), B_2), plus_plus_nat2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(minus_minus_nat, B_1), minus_minus_nat1(B_1))), unc_c_Groups_Ominus__class_Ominus_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(minus_minus_nat1(B_1), B_2), minus_minus_nat2(B_1, B_2))), unc_c_Groups_Ominus__class_Ominus_001t__Nat__Onat_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(times_times_nat, B_1), times_times_nat1(B_1))), unc_c_Groups_Otimes__class_Otimes_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(times_times_nat1(B_1), B_2), times_times_nat2(B_1, B_2))), unc_c_Groups_Otimes__class_Otimes_001t__Nat__Onat_0002).

formula(forall([A : naT, B : naT, C : naT], equiv(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_0_add__left__cancel, 900). % add_left_cancel
formula(forall([B : naT, A : naT, C : naT], equiv(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_1_add__right__cancel, 928). % add_right_cancel
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_2_ab__semigroup__add__class_Oadd__ac_I1_J, 957). % ab_semigroup_add_class.add_ac(1)
formula(forall([V : nuM, W : nuM, Z : naT], equal(plus_plus_nat2(numeral_numeral_nat(V), plus_plus_nat2(numeral_numeral_nat(W), Z)), plus_plus_nat2(numeral_numeral_nat(plus_plus_num(V, W)), Z))), fact_3_add__numeral__left, 986). % add_numeral_left
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), equal(K, L)), equal(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_4_add__mono__thms__linordered__semiring_I4_J, 1014). % add_mono_thms_linordered_semiring(4)
formula(forall([A2 : naT, K : naT, A : naT, B : naT], implies(equal(A2, plus_plus_nat2(K, A)), equal(plus_plus_nat2(A2, B), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_5_group__cancel_Oadd1, 1043). % group_cancel.add1
formula(forall([B2 : naT, K : naT, B : naT, A : naT], implies(equal(B2, plus_plus_nat2(K, B)), equal(plus_plus_nat2(A, B2), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_6_group__cancel_Oadd2, 1072). % group_cancel.add2
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_7_add_Oright__neutral, 1101). % add.right_neutral
formula(forall([A : naT, B : naT], equal(plus_plus_nat2(A, B), plus_plus_nat2(B, A))), fact_8_add_Ocommute, 1129). % add.commute
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_9_add__0, 1158). % add_0
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_10_add_Oassoc, 1187). % add.assoc
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(monoid_nat(F, Z), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, A), Z), A))), fact_11_monoid_Oright__neutral, 1215). % monoid.right_neutral
formula(forall([B : naT, A : naT, C : naT], equal(plus_plus_nat2(B, plus_plus_nat2(A, C)), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_12_add_Oleft__commute, 1244). % add.left_commute
formula(forall([A : naT, B : naT, C : naT], implies(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_13_add__left__imp__eq, 1273). % add_left_imp_eq
formula(forall([B : naT, A : naT, C : naT], implies(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_14_add__right__imp__eq, 1302). % add_right_imp_eq
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(semigroup_nat(F), implies(monoid_axioms_nat(F, Z), monoid_nat(F, Z)))), fact_15_monoid_Ointro, 1330). % monoid.intro
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_16_comm__monoid__add__class_Oadd__0, 1359). % comm_monoid_add_class.add_0
formula(forall([A : naT], ord_less_eq_nat(A, A)), fact_17_dual__order_Orefl, 1388). % dual_order.refl
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(A, B)), equal(B, zero_zero_nat))), fact_18_add__cancel__right__right, 1417). % add_cancel_right_right
formula(forall([A : naT, B : naT], equiv(equal(plus_plus_nat2(A, B), A), equal(B, zero_zero_nat))), fact_19_add__cancel__left__right, 1445). % add_cancel_left_right
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(B, A)), equal(B, zero_zero_nat))), fact_20_add__cancel__right__left, 1474). % add_cancel_right_left
formula(forall([X : naT, Y : naT], equiv(equal(plus_plus_nat2(X, Y), zero_zero_nat), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_21_add__eq__0__iff__both__eq__0, 1503). % add_eq_0_iff_both_eq_0
formula(forall([X : naT, Y : naT], equiv(equal(zero_zero_nat, plus_plus_nat2(X, Y)), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_22_zero__eq__add__iff__both__eq__0, 1531). % zero_eq_add_iff_both_eq_0
formula(forall([B : naT, A : naT], equiv(equal(plus_plus_nat2(B, A), A), equal(B, zero_zero_nat))), fact_23_add__cancel__left__left, 1560). % add_cancel_left_left
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(abel_semigroup_nat(F), implies(comm_m2051353214ms_nat(F, Z), comm_monoid_nat(F, Z)))), fact_24_comm__monoid_Ointro, 1589). % comm_monoid.intro
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(monoid_nat(F, Z), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, Z), A), A))), fact_25_monoid_Oleft__neutral, 1618). % monoid.left_neutral
formula(forall([M : nuM, N : nuM], equal(plus_plus_nat2(numeral_numeral_nat(M), numeral_numeral_nat(N)), numeral_numeral_nat(plus_plus_num(M, N)))), fact_26_numeral__plus__numeral, 1646). % numeral_plus_numeral
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_27_add_Ocomm__neutral, 1675). % add.comm_neutral
formula(forall([C : naT, A : naT, B : naT], equiv(ord_less_eq_nat(plus_plus_nat2(C, A), plus_plus_nat2(C, B)), ord_less_eq_nat(A, B))), fact_28_add__le__cancel__left, 1704). % add_le_cancel_left
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_29_verit__sum__simplify, 1732). % verit_sum_simplify
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(comm_monoid_nat(F, Z), groups1056228905et_nat(F, Z))), fact_30_comm__monoid__set_Ointro, 1761). % comm_monoid_set.intro
formula(forall([M : naT, N : naT], equal(plus_plus_nat2(M, suC(N)), suC(plus_plus_nat2(M, N)))), fact_31_add__Suc__right, 1790). % add_Suc_right
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_eq_nat(I, J), ord_less_eq_nat(K, L)), ord_less_eq_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_32_add__mono__thms__linordered__semiring_I1_J, 1819). % add_mono_thms_linordered_semiring(1)
formula(forall([X : naT], equiv(equal(zero_zero_nat, X), equal(X, zero_zero_nat))), fact_33_zero__reorient, 1847). % zero_reorient
formula(comm_monoid_nat(plus_plus_nat, zero_zero_nat), fact_34_add_Ocomm__monoid__axioms, 1876). % add.comm_monoid_axioms
formula(monoid_nat(plus_plus_nat, zero_zero_nat), fact_35_add_Omonoid__axioms, 1905). % add.monoid_axioms
formula(forall([B : naT, A : naT], equiv(equal(B, plus_plus_nat2(B, A)), equal(A, zero_zero_nat))), fact_36_add__0__iff, 1934). % add_0_iff
formula(forall([X : naT], not(ord_less_nat(X, X))), fact_37_order__less__irrefl, 1962). % order_less_irrefl
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(comm_monoid_nat(F, Z), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, A), Z), A))), fact_38_comm__monoid_Ocomm__neutral, 1991). % comm_monoid.comm_neutral
formula(equal:lt(one_one_nat, suC(zero_zero_nat)), fact_39_One__nat__def, 2020). % One_nat_def
formula(forall([A : naT], equal(A, plus_plus_nat2(A, zero_zero_nat))), fact_40_nat__arith_Orule0, 2048). % nat_arith.rule0
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_eq_nat(I, J), equal(K, L)), ord_less_eq_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_41_add__mono__thms__linordered__semiring_I3_J, 2077). % add_mono_thms_linordered_semiring(3)
formula(forall([A : naT, B : naT, C : naT], implies(equal(A, B), implies(ord_less_eq_nat(B, C), ord_less_eq_nat(A, C)))), fact_42_ord__eq__le__trans, 2106). % ord_eq_le_trans
formula(forall([X : naT, Y : naT], implies(ord_less_eq_nat(X, Y), implies(ord_less_eq_nat(Y, X), equal(X, Y)))), fact_43_order__antisym, 2135). % order_antisym
formula(forall([A : naT, B : naT], equiv(ord_less_eq_nat(A, plus_plus_nat2(A, B)), ord_less_eq_nat(zero_zero_nat, B))), fact_44_le__add__same__cancel1, 2163). % le_add_same_cancel1
formula(forall([A : naT, B : naT], equiv(ord_less_eq_nat(A, plus_plus_nat2(B, A)), ord_less_eq_nat(zero_zero_nat, B))), fact_45_le__add__same__cancel2, 2192). % le_add_same_cancel2
formula(forall([X : naT, Y : naT, Z : naT], implies(ord_less_eq_nat(X, Y), implies(ord_less_eq_nat(Y, Z), ord_less_eq_nat(X, Z)))), fact_46_order__trans, 2221). % order_trans
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_nat(I, J), ord_less_eq_nat(K, L)), ord_less_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_47_add__mono__thms__linordered__field_I3_J, 2250). % add_mono_thms_linordered_field(3)
formula(forall([N : naT], equiv(ord_less_eq_nat(N, zero_zero_nat), equal(N, zero_zero_nat))), fact_48_le__zero__eq, 2278). % le_zero_eq
formula(forall([B : naT, A : naT], equiv(ord_less_eq_nat(plus_plus_nat2(B, A), B), ord_less_eq_nat(A, zero_zero_nat))), fact_49_add__le__same__cancel1, 2307). % add_le_same_cancel1
formula(forall([A : naT, B : naT], equiv(ord_less_eq_nat(plus_plus_nat2(A, B), B), ord_less_eq_nat(A, zero_zero_nat))), fact_50_add__le__same__cancel2, 2336). % add_le_same_cancel2
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_eq_nat(I, J), ord_less_nat(K, L)), ord_less_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_51_add__mono__thms__linordered__field_I4_J, 2364). % add_mono_thms_linordered_field(4)
formula(forall([A : naT, C : naT, B : naT], equiv(ord_less_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, C)), ord_less_nat(A, B))), fact_52_add__less__cancel__right, 2393). % add_less_cancel_right
formula(forall([X : naT], ord_less_eq_nat(zero_zero_nat, X)), fact_53_zero__le, 2422). % zero_le
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_nat(I, J), equal(K, L)), ord_less_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_54_add__mono__thms__linordered__field_I1_J, 2451). % add_mono_thms_linordered_field(1)
formula(forall([N : naT], equiv(not(ord_less_nat(zero_zero_nat, N)), equal(N, zero_zero_nat))), fact_55_not__gr__zero, 2479). % not_gr_zero
formula(forall([A : naT, C : naT, B : naT], equiv(ord_less_eq_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, C)), ord_less_eq_nat(A, B))), fact_56_add__le__cancel__right, 2508). % add_le_cancel_right
formula(forall([C : naT, A : naT, B : naT], equiv(ord_less_nat(plus_plus_nat2(C, A), plus_plus_nat2(C, B)), ord_less_nat(A, B))), fact_57_add__less__cancel__left, 2537). % add_less_cancel_left
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(ord_less_nat(I, J), ord_less_nat(K, L)), ord_less_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_58_add__mono__thms__linordered__field_I5_J, 2565). % add_mono_thms_linordered_field(5)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), ord_less_eq_nat(K, L)), ord_less_eq_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_59_add__mono__thms__linordered__semiring_I2_J, 2594). % add_mono_thms_linordered_semiring(2)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), ord_less_nat(K, L)), ord_less_nat(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_60_add__mono__thms__linordered__field_I2_J, 2623). % add_mono_thms_linordered_field(2)
formula(forall([X : naT, Y : naT], equiv(not(ord_less_nat(X, Y)), ord_less_eq_nat(Y, X))), fact_61_linorder__not__less, 2652). % linorder_not_less
formula(forall([X2_ : naT], not(equal(suC(X2_), zero_zero_nat))), fact_62_nat_Osimps_I3_J, 2680). % nat.simps(3)
formula(forall([B : naT, A : naT], equiv(ord_less_nat(plus_plus_nat2(B, A), B), ord_less_nat(A, zero_zero_nat))), fact_63_add__less__same__cancel1, 2709). % add_less_same_cancel1
formula(forall([A : naT, B : naT], equiv(ord_less_nat(plus_plus_nat2(A, B), B), ord_less_nat(A, zero_zero_nat))), fact_64_add__less__same__cancel2, 2738). % add_less_same_cancel2
formula(forall([A : naT, B : naT], equiv(ord_less_nat(A, plus_plus_nat2(A, B)), ord_less_nat(zero_zero_nat, B))), fact_65_less__add__same__cancel1, 2767). % less_add_same_cancel1
formula(forall([A : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(A, B), A), B)), fact_66_add__diff__cancel__left_H, 2795). % add_diff_cancel_left'
formula(forall([A : naT], equal(times_times_nat2(one_one_nat, A), A)), fact_67_mult__1, 2824). % mult_1
formula(forall([N : naT], not(ord_less_nat(N, zero_zero_nat))), fact_68_not__less__zero, 2853). % not_less_zero
formula(forall([X : naT, Y : naT], equiv(ord_less_nat(X, Y), and(ord_less_eq_nat(X, Y), not(equal(X, Y))))), fact_69_order__less__le, 2881). % order_less_le
formula(not(bot_bot_bool), fact_70_bot__bool__def, 2910). % bot_bool_def
formula(forall([A : naT, B : naT], equiv(ord_less_nat(A, plus_plus_nat2(B, A)), ord_less_nat(zero_zero_nat, B))), fact_71_less__add__same__cancel2, 2939). % less_add_same_cancel2
formula(forall([A : naT, B : naT], implies(ord_less_eq_nat(A, B), implies(ord_less_eq_nat(B, A), equal(A, B)))), fact_72_antisym, 2968). % antisym
formula(forall([A : naT], equal(times_times_nat2(A, one_one_nat), A)), fact_73_mult_Oright__neutral, 2996). % mult.right_neutral
formula(forall([A : naT, B : naT], equiv(ord_less_eq_nat(A, B), exists([C2 : naT], equal(B, plus_plus_nat2(A, C2))))), fact_74_le__iff__add, 3025). % le_iff_add
formula(forall([X : naT, Y : naT], implies(equal(X, Y), ord_less_eq_nat(X, Y))), fact_75_order__eq__refl, 3054). % order_eq_refl
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(ord_less_eq_nat(A, B), implies(ord_less_nat(C, D), ord_less_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, D))))), fact_76_add__le__less__mono, 3082). % add_le_less_mono
formula(forall([A : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(A, B), B), A)), fact_77_add__diff__cancel__right_H, 3111). % add_diff_cancel_right'
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(ord_less_nat(A, B), implies(ord_less_eq_nat(C, D), ord_less_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, D))))), fact_78_add__less__le__mono, 3140). % add_less_le_mono
formula(forall([M : naT, N : naT], equal(plus_plus_nat2(suC(M), N), suC(plus_plus_nat2(M, N)))), fact_79_add__Suc, 3169). % add_Suc
formula(forall([A : naT, B : naT], implies(ord_less_nat(zero_zero_nat, A), implies(ord_less_eq_nat(zero_zero_nat, B), ord_less_nat(zero_zero_nat, plus_plus_nat2(A, B))))), fact_80_add__pos__nonneg, 3197). % add_pos_nonneg
formula(forall([A : naT, B : naT, C : naT], implies(ord_less_eq_nat(zero_zero_nat, A), implies(ord_less_nat(B, C), ord_less_nat(B, plus_plus_nat2(A, C))))), fact_81_add__strict__increasing2, 3226). % add_strict_increasing2
formula(forall([A : naT, B : naT], implies(ord_less_eq_nat(A, B), not(forall([C3 : naT], not(equal(B, plus_plus_nat2(A, C3))))))), fact_82_less__eqE, 3255). % less_eqE
formula(forall([A : naT], equal(times_times_nat2(one_one_nat, A), A)), fact_83_comm__monoid__mult__class_Omult__1, 3284). % comm_monoid_mult_class.mult_1
formula(forall([A : naT, B : naT, C : naT], implies(ord_less_nat(zero_zero_nat, A), implies(ord_less_eq_nat(B, C), ord_less_nat(B, plus_plus_nat2(A, C))))), fact_84_add__strict__increasing, 3312). % add_strict_increasing
formula(forall([A : naT, B : naT], implies(ord_less_nat(A, zero_zero_nat), implies(ord_less_eq_nat(B, zero_zero_nat), ord_less_nat(plus_plus_nat2(A, B), zero_zero_nat)))), fact_85_add__neg__nonpos, 3341). % add_neg_nonpos
formula(forall([B3 : naT, A3 : naT], equiv(not(ord_less_eq_nat(B3, A3)), ord_less_nat(A3, B3))), fact_86_verit__comp__simplify1_I3_J, 3370). % verit_comp_simplify1(3)
formula(forall([A : naT, B : naT], implies(ord_less_eq_nat(A, zero_zero_nat), implies(ord_less_nat(B, zero_zero_nat), ord_less_nat(plus_plus_nat2(A, B), zero_zero_nat)))), fact_87_add__nonpos__neg, 3398). % add_nonpos_neg
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(ord_less_eq_nat(A, B), implies(ord_less_eq_nat(C, D), ord_less_eq_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, D))))), fact_88_add__mono, 3427). % add_mono
formula(forall([A : naT, B : naT, C : naT], implies(ord_less_eq_nat(A, B), ord_less_eq_nat(plus_plus_nat2(A, C), plus_plus_nat2(B, C)))), fact_89_add__right__mono, 3456). % add_right_mono
formula(forall([A : naT], ord_less_eq_nat(A, A)), fact_90_verit__comp__simplify1_I2_J, 3485). % verit_comp_simplify1(2)
formula(forall([A : naT, B : naT], implies(ord_less_eq_nat(zero_zero_nat, A), implies(ord_less_nat(zero_zero_nat, B), ord_less_nat(zero_zero_nat, plus_plus_nat2(A, B))))), fact_91_add__nonneg__pos, 3513). % add_nonneg_pos
formula(forall([A : naT, B : naT], equal(times_times_nat2(A, B), times_times_nat2(B, A))), fact_92_mult_Ocommute, 3542). % mult.commute
formula(forall([A : naT, B : naT, C : naT], implies(ord_less_eq_nat(A, B), ord_less_eq_nat(plus_plus_nat2(C, A), plus_plus_nat2(C, B)))), fact_93_add__left__mono, 3571). % add_left_mono

formula(pp(fTruE), help_pp_2_1_U).
formula(not(pp(fFalsE)), help_pp_1_1_U).
end_of_list.

list_of_formulae(conjectures).
formula(equal(plus_plus_a(x, y), plus_plus_a(y, x)), conj_0).
end_of_list.

list_of_settings(SPASS).
set_precedence(minus_minus_nat, times_times_nat, plus_plus_nat, minus_minus_nat1, ord_less_eq_nat, ord_less_nat, minus_minus_nat2, plus_plus_nat1, times_times_nat1, times_times_nat2, plus_plus_nat2, numeral_numeral_nat, zero_zero_nat, plus_plus_num, one_one_nat, suC).
end_of_list.

end_problem.
