% /Applications/Isabelle2025.app/contrib/e-3.1-1/arm64-darwin/eprover --tstp-in --tstp-out --silent --auto-schedule --cpu-limit=5 --proof-object=1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4729484_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:25.339
% Could-be-implicit typings (1)
tff(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (1)
tff(sy_v_P, type,
    p : a > $o).

% Conjectures (1)
tff(conj_0, conjecture,
    ((![X : a]: ((~ (p(X))) | p(X))))).
