% /Applications/Isabelle2025.app/contrib/spass-3.8ds-2/x86_64-darwin/SPASS -Isabelle=1 -TimeLimit=5 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4736132_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:25.868
begin_problem(isabelle).

list_of_descriptions.
name({**}).
author({**}).
status(unknown).
description({**}).
end_of_list.

list_of_symbols.
functions [(plus_plus_a, 2), (zero_zero_a, 0), (fFalsE, 0), (fTruE, 0), (x, 0)].
predicates [(pp, 1)].
% weights [].
sorts [booL, a, iii].
% classes [].
end_of_list.

list_of_declarations.
function(plus_plus_a, (a, a) a).
function(zero_zero_a, a).
function(fFalsE, booL).
function(fTruE, booL).
function(x, a).
predicate(pp, booL).
end_of_list.

list_of_formulae(axioms).
formula(forall([X : a], equiv(equal(zero_zero_a, X), equal(X, zero_zero_a))), fact_0_zero__reorient, 900). % zero_reorient

formula(pp(fTruE), help_pp_2_1_U).
formula(not(pp(fFalsE)), help_pp_1_1_U).
end_of_list.

list_of_formulae(conjectures).
formula(equal(plus_plus_a(x, zero_zero_a), x), conj_0).
end_of_list.

list_of_settings(SPASS).
% set_precedence().
end_of_list.

end_problem.
