% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 2.500 -nc --tptp-def-as-rewrite --rewrite-before-cnf=true --mode=ho-competitive --boolean-reasoning=bool-hoist --ext-rules=off --recognize-injectivity=true --ho-unif-level=full-framework -q "4|prefer-goals|pnrefined(1,1,1,2,2,2,0.5)" -q "1|prefer-fo|conjecture-relative-var(1.02,l,f)" -q "1|prefer-non-goals|conjecture-relative-var(1,l,f)" -q "4|prefer-ho-steps|conjecture-relative-var(1.01,s,f)" -q "1|prefer-processed|fifo" --select=bb+ho-selection --scan-clause-ac=false --kbo-weight-fun=invfreqrank --fluidsup=true --boolean-reasoning=bool-hoist --fluid-log-hoist=true --fluid-hoist=true --ite-axioms=true --lazy-cnf=true --ho-solid-decider=true --ho-fixpoint-decider=true --bool-select="sel1(pos_ctx)" --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --e-timeout=2 --e-auto=true --e-call-point=0.35 --avatar=off --e-max-derived=50 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4787494_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:31.331
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a)))), [], [isabelle_rank(900)]). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
