% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 2.500 --mode=ho-comb-complete --boolean-reasoning=simpl-only --ext-rules=off --kbo-weight-fun=lambda-def-sqarity --ho-prim-enum=none --tptp-def-as-rewrite -q "4|prefer-sos|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-var(1,s,f)" -q "3|const|default" -q "1|prefer-processed|fifo" --ho-elim-leibniz=1 --select=NoSelection --solve-formulas=true --lazy-cnf=true --lazy-cnf-kind=simp --lazy-cnf-renaming-threshold=8 --sine=60 --sine-tolerance=2 --sine-depth-max=5 --sine-depth-min=1 --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --e-timeout=3 --e-auto=true --e-max-derived=50 --e-encode-lambdas=lift --scan-clause-ac=false --presaturate=true --comb-b-penalty=3 --comb-c-penalty=3 --comb-k-penalty=1 --comb-s-penalty=5 --subvarsup=false --e-call-point=0.15 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4768674_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:26.317
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a)))), [], [isabelle_rank(900)]). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
