% /Applications/Isabelle2025.app/contrib/e-3.1-1/arm64-darwin/eprover --tstp-in --tstp-out --silent --auto-schedule --cpu-limit=5 --proof-object=1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4818590_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:31.640
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a))))). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
