% /Applications/Isabelle2025.app/contrib/e-3.1-1/arm64-darwin/eprover --tstp-in --tstp-out --silent --auto-schedule --cpu-limit=5 --proof-object=1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5168926_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:43:18.806
% Could-be-implicit typings (9)
thf(ty_n_t__Set__Oset_It__Code____Numeral__Ointeger_J, type,
    set_Code_integer : $tType).
thf(ty_n_t__Set__Oset_It__Nat__Onat_J, type,
    set_nat : $tType).
thf(ty_n_t__Set__Oset_It__Int__Oint_J, type,
    set_int : $tType).
thf(ty_n_t__Code____Numeral__Ointeger, type,
    code_integer : $tType).
thf(ty_n_t__String__Oliteral, type,
    literal : $tType).
thf(ty_n_t__Num__Onum, type,
    num : $tType).
thf(ty_n_t__Nat__Onat, type,
    nat : $tType).
thf(ty_n_t__Int__Oint, type,
    int : $tType).
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (57)
thf(sy_c_Groups_Oabel__semigroup_001t__Code____Numeral__Ointeger, type,
    abel_s732171079nteger : (code_integer > code_integer > code_integer) > $o).
thf(sy_c_Groups_Oabel__semigroup_001t__Int__Oint, type,
    abel_semigroup_int : (int > int > int) > $o).
thf(sy_c_Groups_Oabel__semigroup_001t__Nat__Onat, type,
    abel_semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Ocomm__monoid_001t__Code____Numeral__Ointeger, type,
    comm_m604335976nteger : (code_integer > code_integer > code_integer) > code_integer > $o).
thf(sy_c_Groups_Ocomm__monoid_001t__Int__Oint, type,
    comm_monoid_int : (int > int > int) > int > $o).
thf(sy_c_Groups_Ocomm__monoid_001t__Nat__Onat, type,
    comm_monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ocomm__monoid__axioms_001t__Code____Numeral__Ointeger, type,
    comm_m289427211nteger : (code_integer > code_integer > code_integer) > code_integer > $o).
thf(sy_c_Groups_Ocomm__monoid__axioms_001t__Int__Oint, type,
    comm_m541143258ms_int : (int > int > int) > int > $o).
thf(sy_c_Groups_Ocomm__monoid__axioms_001t__Nat__Onat, type,
    comm_m2051353214ms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ominus__class_Ominus_001t__Code____Numeral__Ointeger, type,
    minus_1582103350nteger : code_integer > code_integer > code_integer).
thf(sy_c_Groups_Ominus__class_Ominus_001t__Int__Oint, type,
    minus_minus_int : int > int > int).
thf(sy_c_Groups_Ominus__class_Ominus_001t__Nat__Onat, type,
    minus_minus_nat : nat > nat > nat).
thf(sy_c_Groups_Omonoid_001t__Code____Numeral__Ointeger, type,
    monoid_Code_integer : (code_integer > code_integer > code_integer) > code_integer > $o).
thf(sy_c_Groups_Omonoid_001t__Int__Oint, type,
    monoid_int : (int > int > int) > int > $o).
thf(sy_c_Groups_Omonoid_001t__Nat__Onat, type,
    monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Omonoid_001t__String__Oliteral, type,
    monoid_literal : (literal > literal > literal) > literal > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__Code____Numeral__Ointeger, type,
    monoid1740736831nteger : (code_integer > code_integer > code_integer) > code_integer > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__Int__Oint, type,
    monoid_axioms_int : (int > int > int) > int > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__Nat__Onat, type,
    monoid_axioms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__String__Oliteral, type,
    monoid588351090iteral : (literal > literal > literal) > literal > $o).
thf(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat, type,
    one_one_nat : nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Code____Numeral__Ointeger, type,
    plus_p2058578406nteger : code_integer > code_integer > code_integer).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Int__Oint, type,
    plus_plus_int : int > int > int).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Nat__Onat, type,
    plus_plus_nat : nat > nat > nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__String__Oliteral, type,
    plus_plus_literal : literal > literal > literal).
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Osemigroup_001t__Code____Numeral__Ointeger, type,
    semigr1712786959nteger : (code_integer > code_integer > code_integer) > $o).
thf(sy_c_Groups_Osemigroup_001t__Int__Oint, type,
    semigroup_int : (int > int > int) > $o).
thf(sy_c_Groups_Osemigroup_001t__Nat__Onat, type,
    semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Osemigroup_001t__String__Oliteral, type,
    semigroup_literal : (literal > literal > literal) > $o).
thf(sy_c_Groups_Otimes__class_Otimes_001t__Code____Numeral__Ointeger, type,
    times_1419655522nteger : code_integer > code_integer > code_integer).
thf(sy_c_Groups_Otimes__class_Otimes_001t__Int__Oint, type,
    times_times_int : int > int > int).
thf(sy_c_Groups_Otimes__class_Otimes_001t__Nat__Onat, type,
    times_times_nat : nat > nat > nat).
thf(sy_c_Groups_Ouminus__class_Ouminus_001t__Code____Numeral__Ointeger, type,
    uminus636303014nteger : code_integer > code_integer).
thf(sy_c_Groups_Ouminus__class_Ouminus_001t__Int__Oint, type,
    uminus_uminus_int : int > int).
thf(sy_c_Groups_Ozero__class_Ozero_001t__Code____Numeral__Ointeger, type,
    zero_z413810534nteger : code_integer).
thf(sy_c_Groups_Ozero__class_Ozero_001t__Int__Oint, type,
    zero_zero_int : int).
thf(sy_c_Groups_Ozero__class_Ozero_001t__Nat__Onat, type,
    zero_zero_nat : nat).
thf(sy_c_Groups_Ozero__class_Ozero_001t__String__Oliteral, type,
    zero_zero_literal : literal).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_c_Int_OPos, type,
    pos : num > int).
thf(sy_c_Int_Osub, type,
    sub : num > num > int).
thf(sy_c_Nat_OSuc, type,
    suc : nat > nat).
thf(sy_c_Num_Onumeral__class_Onumeral_001t__Int__Oint, type,
    numeral_numeral_int : num > int).
thf(sy_c_Orderings_Oord__class_Oless_001t__Code____Numeral__Ointeger, type,
    ord_le945590961nteger : code_integer > code_integer > $o).
thf(sy_c_Orderings_Oord__class_Oless_001t__Int__Oint, type,
    ord_less_int : int > int > $o).
thf(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat, type,
    ord_less_nat : nat > nat > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001t__Code____Numeral__Ointeger, type,
    ord_le1426714813nteger : code_integer > code_integer > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001t__Int__Oint, type,
    ord_less_eq_int : int > int > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat, type,
    ord_less_eq_nat : nat > nat > $o).
thf(sy_c_Rings_Odvd__class_Odvd_001t__Code____Numeral__Ointeger, type,
    dvd_dvd_Code_integer : code_integer > code_integer > $o).
thf(sy_c_Rings_Odvd__class_Odvd_001t__Int__Oint, type,
    dvd_dvd_int : int > int > $o).
thf(sy_c_Rings_Odvd__class_Odvd_001t__Nat__Onat, type,
    dvd_dvd_nat : nat > nat > $o).
thf(sy_c_Set_Oimage_001t__Code____Numeral__Ointeger_001t__Code____Numeral__Ointeger, type,
    image_1151633089nteger : (code_integer > code_integer) > set_Code_integer > set_Code_integer).
thf(sy_c_Set_Oimage_001t__Int__Oint_001t__Int__Oint, type,
    image_int_int : (int > int) > set_int > set_int).
thf(sy_c_Set_Oimage_001t__Nat__Onat_001t__Nat__Onat, type,
    image_nat_nat : (nat > nat) > set_nat > set_nat).
thf(sy_v_x, type,
    x : a).

% Relevant facts (254)
thf(fact_0_add_Oright__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.right_neutral
thf(fact_1_add_Oright__neutral, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ A @ zero_z413810534nteger) = A)))). % add.right_neutral
thf(fact_2_add_Oright__neutral, axiom,
    ((![A : int]: ((plus_plus_int @ A @ zero_zero_int) = A)))). % add.right_neutral
thf(fact_3_add_Oright__neutral, axiom,
    ((![A : literal]: ((plus_plus_literal @ A @ zero_zero_literal) = A)))). % add.right_neutral
thf(fact_4_add__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % add_0
thf(fact_5_add__0, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ zero_z413810534nteger @ A) = A)))). % add_0
thf(fact_6_add__0, axiom,
    ((![A : int]: ((plus_plus_int @ zero_zero_int @ A) = A)))). % add_0
thf(fact_7_add__0, axiom,
    ((![A : literal]: ((plus_plus_literal @ zero_zero_literal @ A) = A)))). % add_0
thf(fact_8_double__zero__sym, axiom,
    ((![A : code_integer]: ((zero_z413810534nteger = (plus_p2058578406nteger @ A @ A)) = (A = zero_z413810534nteger))))). % double_zero_sym
thf(fact_9_double__zero__sym, axiom,
    ((![A : int]: ((zero_zero_int = (plus_plus_int @ A @ A)) = (A = zero_zero_int))))). % double_zero_sym
thf(fact_10_add__cancel__left__left, axiom,
    ((![B : nat, A : nat]: (((plus_plus_nat @ B @ A) = A) = (B = zero_zero_nat))))). % add_cancel_left_left
thf(fact_11_add__cancel__left__left, axiom,
    ((![B : code_integer, A : code_integer]: (((plus_p2058578406nteger @ B @ A) = A) = (B = zero_z413810534nteger))))). % add_cancel_left_left
thf(fact_12_add__cancel__left__left, axiom,
    ((![B : int, A : int]: (((plus_plus_int @ B @ A) = A) = (B = zero_zero_int))))). % add_cancel_left_left
thf(fact_13_comm__monoid__add__class_Oadd__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % comm_monoid_add_class.add_0
thf(fact_14_comm__monoid__add__class_Oadd__0, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ zero_z413810534nteger @ A) = A)))). % comm_monoid_add_class.add_0
thf(fact_15_comm__monoid__add__class_Oadd__0, axiom,
    ((![A : int]: ((plus_plus_int @ zero_zero_int @ A) = A)))). % comm_monoid_add_class.add_0
thf(fact_16_nat__arith_Orule0, axiom,
    ((![A : nat]: (A = (plus_plus_nat @ A @ zero_zero_nat))))). % nat_arith.rule0
thf(fact_17_nat__arith_Orule0, axiom,
    ((![A : code_integer]: (A = (plus_p2058578406nteger @ A @ zero_z413810534nteger))))). % nat_arith.rule0
thf(fact_18_nat__arith_Orule0, axiom,
    ((![A : int]: (A = (plus_plus_int @ A @ zero_zero_int))))). % nat_arith.rule0
thf(fact_19_add__cancel__left__right, axiom,
    ((![A : nat, B : nat]: (((plus_plus_nat @ A @ B) = A) = (B = zero_zero_nat))))). % add_cancel_left_right
thf(fact_20_add__cancel__left__right, axiom,
    ((![A : code_integer, B : code_integer]: (((plus_p2058578406nteger @ A @ B) = A) = (B = zero_z413810534nteger))))). % add_cancel_left_right
thf(fact_21_add__cancel__left__right, axiom,
    ((![A : int, B : int]: (((plus_plus_int @ A @ B) = A) = (B = zero_zero_int))))). % add_cancel_left_right
thf(fact_22_add__cancel__right__left, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ B @ A)) = (B = zero_zero_nat))))). % add_cancel_right_left
thf(fact_23_add__cancel__right__left, axiom,
    ((![A : code_integer, B : code_integer]: ((A = (plus_p2058578406nteger @ B @ A)) = (B = zero_z413810534nteger))))). % add_cancel_right_left
thf(fact_24_add__cancel__right__left, axiom,
    ((![A : int, B : int]: ((A = (plus_plus_int @ B @ A)) = (B = zero_zero_int))))). % add_cancel_right_left
thf(fact_25_add__cancel__right__right, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ A @ B)) = (B = zero_zero_nat))))). % add_cancel_right_right
thf(fact_26_add__cancel__right__right, axiom,
    ((![A : code_integer, B : code_integer]: ((A = (plus_p2058578406nteger @ A @ B)) = (B = zero_z413810534nteger))))). % add_cancel_right_right
thf(fact_27_add__cancel__right__right, axiom,
    ((![A : int, B : int]: ((A = (plus_plus_int @ A @ B)) = (B = zero_zero_int))))). % add_cancel_right_right
thf(fact_28_monoid_Ointro, axiom,
    ((![F : literal > literal > literal, Z : literal]: ((semigroup_literal @ F) => ((monoid588351090iteral @ F @ Z) => (monoid_literal @ F @ Z)))))). % monoid.intro
thf(fact_29_monoid_Ointro, axiom,
    ((![F : int > int > int, Z : int]: ((semigroup_int @ F) => ((monoid_axioms_int @ F @ Z) => (monoid_int @ F @ Z)))))). % monoid.intro
thf(fact_30_monoid_Ointro, axiom,
    ((![F : code_integer > code_integer > code_integer, Z : code_integer]: ((semigr1712786959nteger @ F) => ((monoid1740736831nteger @ F @ Z) => (monoid_Code_integer @ F @ Z)))))). % monoid.intro
thf(fact_31_monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((semigroup_nat @ F) => ((monoid_axioms_nat @ F @ Z) => (monoid_nat @ F @ Z)))))). % monoid.intro
thf(fact_32_add_Ocomm__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.comm_neutral
thf(fact_33_add_Ocomm__neutral, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ A @ zero_z413810534nteger) = A)))). % add.comm_neutral
thf(fact_34_add_Ocomm__neutral, axiom,
    ((![A : int]: ((plus_plus_int @ A @ zero_zero_int) = A)))). % add.comm_neutral
thf(fact_35_add__eq__0__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: (((plus_plus_nat @ X @ Y) = zero_zero_nat) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % add_eq_0_iff_both_eq_0
thf(fact_36_verit__sum__simplify, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % verit_sum_simplify
thf(fact_37_verit__sum__simplify, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ A @ zero_z413810534nteger) = A)))). % verit_sum_simplify
thf(fact_38_verit__sum__simplify, axiom,
    ((![A : int]: ((plus_plus_int @ A @ zero_zero_int) = A)))). % verit_sum_simplify
thf(fact_39_add_Ogroup__left__neutral, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ zero_z413810534nteger @ A) = A)))). % add.group_left_neutral
thf(fact_40_add_Ogroup__left__neutral, axiom,
    ((![A : int]: ((plus_plus_int @ zero_zero_int @ A) = A)))). % add.group_left_neutral
thf(fact_41_zero__eq__add__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: ((zero_zero_nat = (plus_plus_nat @ X @ Y)) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % zero_eq_add_iff_both_eq_0
thf(fact_42_add__left__cancel, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) = (B = C))))). % add_left_cancel
thf(fact_43_add__left__cancel, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: (((plus_p2058578406nteger @ A @ B) = (plus_p2058578406nteger @ A @ C)) = (B = C))))). % add_left_cancel
thf(fact_44_add__left__cancel, axiom,
    ((![A : int, B : int, C : int]: (((plus_plus_int @ A @ B) = (plus_plus_int @ A @ C)) = (B = C))))). % add_left_cancel
thf(fact_45_double__eq__0__iff, axiom,
    ((![A : code_integer]: (((plus_p2058578406nteger @ A @ A) = zero_z413810534nteger) = (A = zero_z413810534nteger))))). % double_eq_0_iff
thf(fact_46_double__eq__0__iff, axiom,
    ((![A : int]: (((plus_plus_int @ A @ A) = zero_zero_int) = (A = zero_zero_int))))). % double_eq_0_iff
thf(fact_47_add__right__cancel, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) = (B = C))))). % add_right_cancel
thf(fact_48_add__right__cancel, axiom,
    ((![B : code_integer, A : code_integer, C : code_integer]: (((plus_p2058578406nteger @ B @ A) = (plus_p2058578406nteger @ C @ A)) = (B = C))))). % add_right_cancel
thf(fact_49_add__right__cancel, axiom,
    ((![B : int, A : int, C : int]: (((plus_plus_int @ B @ A) = (plus_plus_int @ C @ A)) = (B = C))))). % add_right_cancel
thf(fact_50_add_Ocommute, axiom,
    ((plus_plus_nat = (^[A2 : nat]: (^[B2 : nat]: (plus_plus_nat @ B2 @ A2)))))). % add.commute
thf(fact_51_add_Ocommute, axiom,
    ((plus_p2058578406nteger = (^[A2 : code_integer]: (^[B2 : code_integer]: (plus_p2058578406nteger @ B2 @ A2)))))). % add.commute
thf(fact_52_add_Ocommute, axiom,
    ((plus_plus_int = (^[A2 : int]: (^[B2 : int]: (plus_plus_int @ B2 @ A2)))))). % add.commute
thf(fact_53_comm__monoid_Ocomm__neutral, axiom,
    ((![F : int > int > int, Z : int, A : int]: ((comm_monoid_int @ F @ Z) => ((F @ A @ Z) = A))))). % comm_monoid.comm_neutral
thf(fact_54_comm__monoid_Ocomm__neutral, axiom,
    ((![F : code_integer > code_integer > code_integer, Z : code_integer, A : code_integer]: ((comm_m604335976nteger @ F @ Z) => ((F @ A @ Z) = A))))). % comm_monoid.comm_neutral
thf(fact_55_comm__monoid_Ocomm__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((comm_monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % comm_monoid.comm_neutral
thf(fact_56_add_Oleft__commute, axiom,
    ((![B : nat, A : nat, C : nat]: ((plus_plus_nat @ B @ (plus_plus_nat @ A @ C)) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.left_commute
thf(fact_57_add_Oleft__commute, axiom,
    ((![B : code_integer, A : code_integer, C : code_integer]: ((plus_p2058578406nteger @ B @ (plus_p2058578406nteger @ A @ C)) = (plus_p2058578406nteger @ A @ (plus_p2058578406nteger @ B @ C)))))). % add.left_commute
thf(fact_58_add_Oleft__commute, axiom,
    ((![B : int, A : int, C : int]: ((plus_plus_int @ B @ (plus_plus_int @ A @ C)) = (plus_plus_int @ A @ (plus_plus_int @ B @ C)))))). % add.left_commute
thf(fact_59_comm__monoid_Ointro, axiom,
    ((![F : int > int > int, Z : int]: ((abel_semigroup_int @ F) => ((comm_m541143258ms_int @ F @ Z) => (comm_monoid_int @ F @ Z)))))). % comm_monoid.intro
thf(fact_60_comm__monoid_Ointro, axiom,
    ((![F : code_integer > code_integer > code_integer, Z : code_integer]: ((abel_s732171079nteger @ F) => ((comm_m289427211nteger @ F @ Z) => (comm_m604335976nteger @ F @ Z)))))). % comm_monoid.intro
thf(fact_61_comm__monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((abel_semigroup_nat @ F) => ((comm_m2051353214ms_nat @ F @ Z) => (comm_monoid_nat @ F @ Z)))))). % comm_monoid.intro
thf(fact_62_add__left__imp__eq, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) => (B = C))))). % add_left_imp_eq
thf(fact_63_add__left__imp__eq, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: (((plus_p2058578406nteger @ A @ B) = (plus_p2058578406nteger @ A @ C)) => (B = C))))). % add_left_imp_eq
thf(fact_64_add__left__imp__eq, axiom,
    ((![A : int, B : int, C : int]: (((plus_plus_int @ A @ B) = (plus_plus_int @ A @ C)) => (B = C))))). % add_left_imp_eq
thf(fact_65_monoid_Oright__neutral, axiom,
    ((![F : literal > literal > literal, Z : literal, A : literal]: ((monoid_literal @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_66_monoid_Oright__neutral, axiom,
    ((![F : int > int > int, Z : int, A : int]: ((monoid_int @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_67_monoid_Oright__neutral, axiom,
    ((![F : code_integer > code_integer > code_integer, Z : code_integer, A : code_integer]: ((monoid_Code_integer @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_68_monoid_Oright__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_69_monoid_Oleft__neutral, axiom,
    ((![F : int > int > int, Z : int, A : int]: ((monoid_int @ F @ Z) => ((F @ Z @ A) = A))))). % monoid.left_neutral
thf(fact_70_monoid_Oleft__neutral, axiom,
    ((![F : code_integer > code_integer > code_integer, Z : code_integer, A : code_integer]: ((monoid_Code_integer @ F @ Z) => ((F @ Z @ A) = A))))). % monoid.left_neutral
thf(fact_71_monoid_Oleft__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ Z @ A) = A))))). % monoid.left_neutral
thf(fact_72_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a))))). % zero_reorient
thf(fact_73_zero__reorient, axiom,
    ((![X : nat]: ((zero_zero_nat = X) = (X = zero_zero_nat))))). % zero_reorient
thf(fact_74_zero__reorient, axiom,
    ((![X : code_integer]: ((zero_z413810534nteger = X) = (X = zero_z413810534nteger))))). % zero_reorient
thf(fact_75_zero__reorient, axiom,
    ((![X : int]: ((zero_zero_int = X) = (X = zero_zero_int))))). % zero_reorient
thf(fact_76_zero__reorient, axiom,
    ((![X : literal]: ((zero_zero_literal = X) = (X = zero_zero_literal))))). % zero_reorient
thf(fact_77_plus__nat_Osimps_I1_J, axiom,
    ((![N : nat]: ((plus_plus_nat @ zero_zero_nat @ N) = N)))). % plus_nat.simps(1)
thf(fact_78_group__cancel_Oadd1, axiom,
    ((![A3 : nat, K : nat, A : nat, B : nat]: ((A3 = (plus_plus_nat @ K @ A)) => ((plus_plus_nat @ A3 @ B) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add1
thf(fact_79_group__cancel_Oadd1, axiom,
    ((![A3 : code_integer, K : code_integer, A : code_integer, B : code_integer]: ((A3 = (plus_p2058578406nteger @ K @ A)) => ((plus_p2058578406nteger @ A3 @ B) = (plus_p2058578406nteger @ K @ (plus_p2058578406nteger @ A @ B))))))). % group_cancel.add1
thf(fact_80_group__cancel_Oadd1, axiom,
    ((![A3 : int, K : int, A : int, B : int]: ((A3 = (plus_plus_int @ K @ A)) => ((plus_plus_int @ A3 @ B) = (plus_plus_int @ K @ (plus_plus_int @ A @ B))))))). % group_cancel.add1
thf(fact_81_group__cancel_Oadd2, axiom,
    ((![B3 : nat, K : nat, B : nat, A : nat]: ((B3 = (plus_plus_nat @ K @ B)) => ((plus_plus_nat @ A @ B3) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add2
thf(fact_82_group__cancel_Oadd2, axiom,
    ((![B3 : code_integer, K : code_integer, B : code_integer, A : code_integer]: ((B3 = (plus_p2058578406nteger @ K @ B)) => ((plus_p2058578406nteger @ A @ B3) = (plus_p2058578406nteger @ K @ (plus_p2058578406nteger @ A @ B))))))). % group_cancel.add2
thf(fact_83_group__cancel_Oadd2, axiom,
    ((![B3 : int, K : int, B : int, A : int]: ((B3 = (plus_plus_int @ K @ B)) => ((plus_plus_int @ A @ B3) = (plus_plus_int @ K @ (plus_plus_int @ A @ B))))))). % group_cancel.add2
thf(fact_84_add__right__imp__eq, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) => (B = C))))). % add_right_imp_eq
thf(fact_85_add__right__imp__eq, axiom,
    ((![B : code_integer, A : code_integer, C : code_integer]: (((plus_p2058578406nteger @ B @ A) = (plus_p2058578406nteger @ C @ A)) => (B = C))))). % add_right_imp_eq
thf(fact_86_add__right__imp__eq, axiom,
    ((![B : int, A : int, C : int]: (((plus_plus_int @ B @ A) = (plus_plus_int @ C @ A)) => (B = C))))). % add_right_imp_eq
thf(fact_87_unity__coeff__ex, axiom,
    ((![P : nat > $o, L : nat]: ((?[X2 : nat]: (P @ (times_times_nat @ L @ X2))) = (?[X2 : nat]: (((dvd_dvd_nat @ L @ (plus_plus_nat @ X2 @ zero_zero_nat))) & ((P @ X2)))))))). % unity_coeff_ex
thf(fact_88_unity__coeff__ex, axiom,
    ((![P : code_integer > $o, L : code_integer]: ((?[X2 : code_integer]: (P @ (times_1419655522nteger @ L @ X2))) = (?[X2 : code_integer]: (((dvd_dvd_Code_integer @ L @ (plus_p2058578406nteger @ X2 @ zero_z413810534nteger))) & ((P @ X2)))))))). % unity_coeff_ex
thf(fact_89_unity__coeff__ex, axiom,
    ((![P : int > $o, L : int]: ((?[X2 : int]: (P @ (times_times_int @ L @ X2))) = (?[X2 : int]: (((dvd_dvd_int @ L @ (plus_plus_int @ X2 @ zero_zero_int))) & ((P @ X2)))))))). % unity_coeff_ex
thf(fact_90_image__add__0, axiom,
    ((![S : set_nat]: ((image_nat_nat @ (plus_plus_nat @ zero_zero_nat) @ S) = S)))). % image_add_0
thf(fact_91_image__add__0, axiom,
    ((![S : set_Code_integer]: ((image_1151633089nteger @ (plus_p2058578406nteger @ zero_z413810534nteger) @ S) = S)))). % image_add_0
thf(fact_92_image__add__0, axiom,
    ((![S : set_int]: ((image_int_int @ (plus_plus_int @ zero_zero_int) @ S) = S)))). % image_add_0
thf(fact_93_add_Oright__cancel, axiom,
    ((![B : code_integer, A : code_integer, C : code_integer]: (((plus_p2058578406nteger @ B @ A) = (plus_p2058578406nteger @ C @ A)) = (B = C))))). % add.right_cancel
thf(fact_94_add_Oright__cancel, axiom,
    ((![B : int, A : int, C : int]: (((plus_plus_int @ B @ A) = (plus_plus_int @ C @ A)) = (B = C))))). % add.right_cancel
thf(fact_95_add_Oleft__cancel, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: (((plus_p2058578406nteger @ A @ B) = (plus_p2058578406nteger @ A @ C)) = (B = C))))). % add.left_cancel
thf(fact_96_add_Oleft__cancel, axiom,
    ((![A : int, B : int, C : int]: (((plus_plus_int @ A @ B) = (plus_plus_int @ A @ C)) = (B = C))))). % add.left_cancel
thf(fact_97_Nat_Oadd__0__right, axiom,
    ((![M : nat]: ((plus_plus_nat @ M @ zero_zero_nat) = M)))). % Nat.add_0_right
thf(fact_98_add_Oassoc, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.assoc
thf(fact_99_add_Oassoc, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((plus_p2058578406nteger @ (plus_p2058578406nteger @ A @ B) @ C) = (plus_p2058578406nteger @ A @ (plus_p2058578406nteger @ B @ C)))))). % add.assoc
thf(fact_100_add_Oassoc, axiom,
    ((![A : int, B : int, C : int]: ((plus_plus_int @ (plus_plus_int @ A @ B) @ C) = (plus_plus_int @ A @ (plus_plus_int @ B @ C)))))). % add.assoc
thf(fact_101_add_Oassoc, axiom,
    ((![A : literal, B : literal, C : literal]: ((plus_plus_literal @ (plus_plus_literal @ A @ B) @ C) = (plus_plus_literal @ A @ (plus_plus_literal @ B @ C)))))). % add.assoc
thf(fact_102_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (K = L)) => ((plus_plus_nat @ I @ K) = (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(4)
thf(fact_103_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![I : code_integer, J : code_integer, K : code_integer, L : code_integer]: (((I = J) & (K = L)) => ((plus_p2058578406nteger @ I @ K) = (plus_p2058578406nteger @ J @ L)))))). % add_mono_thms_linordered_semiring(4)
thf(fact_104_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![I : int, J : int, K : int, L : int]: (((I = J) & (K = L)) => ((plus_plus_int @ I @ K) = (plus_plus_int @ J @ L)))))). % add_mono_thms_linordered_semiring(4)
thf(fact_105_add_Ocomm__monoid__axioms, axiom,
    ((comm_monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.comm_monoid_axioms
thf(fact_106_add_Ocomm__monoid__axioms, axiom,
    ((comm_m604335976nteger @ plus_p2058578406nteger @ zero_z413810534nteger))). % add.comm_monoid_axioms
thf(fact_107_add_Ocomm__monoid__axioms, axiom,
    ((comm_monoid_int @ plus_plus_int @ zero_zero_int))). % add.comm_monoid_axioms
thf(fact_108_add__0__iff, axiom,
    ((![B : nat, A : nat]: ((B = (plus_plus_nat @ B @ A)) = (A = zero_zero_nat))))). % add_0_iff
thf(fact_109_add__0__iff, axiom,
    ((![B : code_integer, A : code_integer]: ((B = (plus_p2058578406nteger @ B @ A)) = (A = zero_z413810534nteger))))). % add_0_iff
thf(fact_110_add__0__iff, axiom,
    ((![B : int, A : int]: ((B = (plus_plus_int @ B @ A)) = (A = zero_zero_int))))). % add_0_iff
thf(fact_111_add_Omonoid__axioms, axiom,
    ((monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.monoid_axioms
thf(fact_112_add_Omonoid__axioms, axiom,
    ((monoid_Code_integer @ plus_p2058578406nteger @ zero_z413810534nteger))). % add.monoid_axioms
thf(fact_113_add_Omonoid__axioms, axiom,
    ((monoid_int @ plus_plus_int @ zero_zero_int))). % add.monoid_axioms
thf(fact_114_add_Omonoid__axioms, axiom,
    ((monoid_literal @ plus_plus_literal @ zero_zero_literal))). % add.monoid_axioms
thf(fact_115_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % ab_semigroup_add_class.add_ac(1)
thf(fact_116_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((plus_p2058578406nteger @ (plus_p2058578406nteger @ A @ B) @ C) = (plus_p2058578406nteger @ A @ (plus_p2058578406nteger @ B @ C)))))). % ab_semigroup_add_class.add_ac(1)
thf(fact_117_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![A : int, B : int, C : int]: ((plus_plus_int @ (plus_plus_int @ A @ B) @ C) = (plus_plus_int @ A @ (plus_plus_int @ B @ C)))))). % ab_semigroup_add_class.add_ac(1)
thf(fact_118_add__uminus__conv__diff, axiom,
    ((![A : code_integer, B : code_integer]: ((plus_p2058578406nteger @ A @ (uminus636303014nteger @ B)) = (minus_1582103350nteger @ A @ B))))). % add_uminus_conv_diff
thf(fact_119_add__uminus__conv__diff, axiom,
    ((![A : int, B : int]: ((plus_plus_int @ A @ (uminus_uminus_int @ B)) = (minus_minus_int @ A @ B))))). % add_uminus_conv_diff
thf(fact_120_add__le__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_left
thf(fact_121_add__le__cancel__left, axiom,
    ((![C : code_integer, A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ (plus_p2058578406nteger @ C @ A) @ (plus_p2058578406nteger @ C @ B)) = (ord_le1426714813nteger @ A @ B))))). % add_le_cancel_left
thf(fact_122_add__le__cancel__left, axiom,
    ((![C : int, A : int, B : int]: ((ord_less_eq_int @ (plus_plus_int @ C @ A) @ (plus_plus_int @ C @ B)) = (ord_less_eq_int @ A @ B))))). % add_le_cancel_left
thf(fact_123_zero__le, axiom,
    ((![X : nat]: (ord_less_eq_nat @ zero_zero_nat @ X)))). % zero_le
thf(fact_124_plus__integer__code_I1_J, axiom,
    ((![K : code_integer]: ((plus_p2058578406nteger @ K @ zero_z413810534nteger) = K)))). % plus_integer_code(1)
thf(fact_125_Int_OPos__def, axiom,
    ((pos = numeral_numeral_int))). % Int.Pos_def
thf(fact_126_uminus__add__conv__diff, axiom,
    ((![A : code_integer, B : code_integer]: ((plus_p2058578406nteger @ (uminus636303014nteger @ A) @ B) = (minus_1582103350nteger @ B @ A))))). % uminus_add_conv_diff
thf(fact_127_uminus__add__conv__diff, axiom,
    ((![A : int, B : int]: ((plus_plus_int @ (uminus_uminus_int @ A) @ B) = (minus_minus_int @ B @ A))))). % uminus_add_conv_diff
thf(fact_128_le__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel2
thf(fact_129_le__add__same__cancel2, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ A @ (plus_p2058578406nteger @ B @ A)) = (ord_le1426714813nteger @ zero_z413810534nteger @ B))))). % le_add_same_cancel2
thf(fact_130_le__add__same__cancel2, axiom,
    ((![A : int, B : int]: ((ord_less_eq_int @ A @ (plus_plus_int @ B @ A)) = (ord_less_eq_int @ zero_zero_int @ B))))). % le_add_same_cancel2
thf(fact_131_zero__le__double__add__iff__zero__le__single__add, axiom,
    ((![A : code_integer]: ((ord_le1426714813nteger @ zero_z413810534nteger @ (plus_p2058578406nteger @ A @ A)) = (ord_le1426714813nteger @ zero_z413810534nteger @ A))))). % zero_le_double_add_iff_zero_le_single_add
thf(fact_132_zero__le__double__add__iff__zero__le__single__add, axiom,
    ((![A : int]: ((ord_less_eq_int @ zero_zero_int @ (plus_plus_int @ A @ A)) = (ord_less_eq_int @ zero_zero_int @ A))))). % zero_le_double_add_iff_zero_le_single_add
thf(fact_133_le__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel1
thf(fact_134_le__add__same__cancel1, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ A @ (plus_p2058578406nteger @ A @ B)) = (ord_le1426714813nteger @ zero_z413810534nteger @ B))))). % le_add_same_cancel1
thf(fact_135_le__add__same__cancel1, axiom,
    ((![A : int, B : int]: ((ord_less_eq_int @ A @ (plus_plus_int @ A @ B)) = (ord_less_eq_int @ zero_zero_int @ B))))). % le_add_same_cancel1
thf(fact_136_plus__int__code_I1_J, axiom,
    ((![K : int]: ((plus_plus_int @ K @ zero_zero_int) = K)))). % plus_int_code(1)
thf(fact_137_double__add__le__zero__iff__single__add__le__zero, axiom,
    ((![A : code_integer]: ((ord_le1426714813nteger @ (plus_p2058578406nteger @ A @ A) @ zero_z413810534nteger) = (ord_le1426714813nteger @ A @ zero_z413810534nteger))))). % double_add_le_zero_iff_single_add_le_zero
thf(fact_138_double__add__le__zero__iff__single__add__le__zero, axiom,
    ((![A : int]: ((ord_less_eq_int @ (plus_plus_int @ A @ A) @ zero_zero_int) = (ord_less_eq_int @ A @ zero_zero_int))))). % double_add_le_zero_iff_single_add_le_zero
thf(fact_139_is__num__normalize_I1_J, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((plus_p2058578406nteger @ (plus_p2058578406nteger @ A @ B) @ C) = (plus_p2058578406nteger @ A @ (plus_p2058578406nteger @ B @ C)))))). % is_num_normalize(1)
thf(fact_140_is__num__normalize_I1_J, axiom,
    ((![A : int, B : int, C : int]: ((plus_plus_int @ (plus_plus_int @ A @ B) @ C) = (plus_plus_int @ A @ (plus_plus_int @ B @ C)))))). % is_num_normalize(1)
thf(fact_141_plus__int__code_I2_J, axiom,
    ((![L : int]: ((plus_plus_int @ zero_zero_int @ L) = L)))). % plus_int_code(2)
thf(fact_142_add__le__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel1
thf(fact_143_add__le__same__cancel1, axiom,
    ((![B : code_integer, A : code_integer]: ((ord_le1426714813nteger @ (plus_p2058578406nteger @ B @ A) @ B) = (ord_le1426714813nteger @ A @ zero_z413810534nteger))))). % add_le_same_cancel1
thf(fact_144_add__le__same__cancel1, axiom,
    ((![B : int, A : int]: ((ord_less_eq_int @ (plus_plus_int @ B @ A) @ B) = (ord_less_eq_int @ A @ zero_zero_int))))). % add_le_same_cancel1
thf(fact_145_add__le__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel2
thf(fact_146_add__le__same__cancel2, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ (plus_p2058578406nteger @ A @ B) @ B) = (ord_le1426714813nteger @ A @ zero_z413810534nteger))))). % add_le_same_cancel2
thf(fact_147_add__le__same__cancel2, axiom,
    ((![A : int, B : int]: ((ord_less_eq_int @ (plus_plus_int @ A @ B) @ B) = (ord_less_eq_int @ A @ zero_zero_int))))). % add_le_same_cancel2
thf(fact_148_le__zero__eq, axiom,
    ((![N : nat]: ((ord_less_eq_nat @ N @ zero_zero_nat) = (N = zero_zero_nat))))). % le_zero_eq
thf(fact_149_plus__integer__code_I2_J, axiom,
    ((![L : code_integer]: ((plus_p2058578406nteger @ zero_z413810534nteger @ L) = L)))). % plus_integer_code(2)
thf(fact_150_not__gr__zero, axiom,
    ((![N : nat]: ((~ ((ord_less_nat @ zero_zero_nat @ N))) = (N = zero_zero_nat))))). % not_gr_zero
thf(fact_151_zero__less__double__add__iff__zero__less__single__add, axiom,
    ((![A : code_integer]: ((ord_le945590961nteger @ zero_z413810534nteger @ (plus_p2058578406nteger @ A @ A)) = (ord_le945590961nteger @ zero_z413810534nteger @ A))))). % zero_less_double_add_iff_zero_less_single_add
thf(fact_152_zero__less__double__add__iff__zero__less__single__add, axiom,
    ((![A : int]: ((ord_less_int @ zero_zero_int @ (plus_plus_int @ A @ A)) = (ord_less_int @ zero_zero_int @ A))))). % zero_less_double_add_iff_zero_less_single_add
thf(fact_153_add__less__cancel__left, axiom,
    ((![C : code_integer, A : code_integer, B : code_integer]: ((ord_le945590961nteger @ (plus_p2058578406nteger @ C @ A) @ (plus_p2058578406nteger @ C @ B)) = (ord_le945590961nteger @ A @ B))))). % add_less_cancel_left
thf(fact_154_add__less__cancel__left, axiom,
    ((![C : int, A : int, B : int]: ((ord_less_int @ (plus_plus_int @ C @ A) @ (plus_plus_int @ C @ B)) = (ord_less_int @ A @ B))))). % add_less_cancel_left
thf(fact_155_add__less__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_nat @ A @ B))))). % add_less_cancel_left
thf(fact_156_add__literal__code_I1_J, axiom,
    ((![S2 : literal]: ((plus_plus_literal @ zero_zero_literal @ S2) = S2)))). % add_literal_code(1)
thf(fact_157_add__le__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_right
thf(fact_158_add__le__cancel__right, axiom,
    ((![A : code_integer, C : code_integer, B : code_integer]: ((ord_le1426714813nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ C)) = (ord_le1426714813nteger @ A @ B))))). % add_le_cancel_right
thf(fact_159_add__le__cancel__right, axiom,
    ((![A : int, C : int, B : int]: ((ord_less_eq_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ C)) = (ord_less_eq_int @ A @ B))))). % add_le_cancel_right
thf(fact_160_add__literal__code_I2_J, axiom,
    ((![S2 : literal]: ((plus_plus_literal @ S2 @ zero_zero_literal) = S2)))). % add_literal_code(2)
thf(fact_161_mult__1, axiom,
    ((![A : nat]: ((times_times_nat @ one_one_nat @ A) = A)))). % mult_1
thf(fact_162_add__less__cancel__right, axiom,
    ((![A : code_integer, C : code_integer, B : code_integer]: ((ord_le945590961nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ C)) = (ord_le945590961nteger @ A @ B))))). % add_less_cancel_right
thf(fact_163_add__less__cancel__right, axiom,
    ((![A : int, C : int, B : int]: ((ord_less_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ C)) = (ord_less_int @ A @ B))))). % add_less_cancel_right
thf(fact_164_add__less__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_nat @ A @ B))))). % add_less_cancel_right
thf(fact_165_add__less__same__cancel1, axiom,
    ((![B : code_integer, A : code_integer]: ((ord_le945590961nteger @ (plus_p2058578406nteger @ B @ A) @ B) = (ord_le945590961nteger @ A @ zero_z413810534nteger))))). % add_less_same_cancel1
thf(fact_166_add__less__same__cancel1, axiom,
    ((![B : int, A : int]: ((ord_less_int @ (plus_plus_int @ B @ A) @ B) = (ord_less_int @ A @ zero_zero_int))))). % add_less_same_cancel1
thf(fact_167_add__less__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel1
thf(fact_168_One__nat__def, axiom,
    ((one_one_nat = (suc @ zero_zero_nat)))). % One_nat_def
thf(fact_169_Int_Osub__def, axiom,
    ((sub = (^[M2 : num]: (^[N2 : num]: (minus_minus_int @ (numeral_numeral_int @ M2) @ (numeral_numeral_int @ N2))))))). % Int.sub_def
thf(fact_170_add__less__same__cancel2, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le945590961nteger @ (plus_p2058578406nteger @ A @ B) @ B) = (ord_le945590961nteger @ A @ zero_z413810534nteger))))). % add_less_same_cancel2
thf(fact_171_add__less__same__cancel2, axiom,
    ((![A : int, B : int]: ((ord_less_int @ (plus_plus_int @ A @ B) @ B) = (ord_less_int @ A @ zero_zero_int))))). % add_less_same_cancel2
thf(fact_172_add__less__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel2
thf(fact_173_less__add__same__cancel1, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le945590961nteger @ A @ (plus_p2058578406nteger @ A @ B)) = (ord_le945590961nteger @ zero_z413810534nteger @ B))))). % less_add_same_cancel1
thf(fact_174_less__add__same__cancel1, axiom,
    ((![A : int, B : int]: ((ord_less_int @ A @ (plus_plus_int @ A @ B)) = (ord_less_int @ zero_zero_int @ B))))). % less_add_same_cancel1
thf(fact_175_less__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel1
thf(fact_176_mult_Oright__neutral, axiom,
    ((![A : nat]: ((times_times_nat @ A @ one_one_nat) = A)))). % mult.right_neutral
thf(fact_177_not__less__zero, axiom,
    ((![N : nat]: (~ ((ord_less_nat @ N @ zero_zero_nat)))))). % not_less_zero
thf(fact_178_linorder__not__less, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_nat @ X @ Y))) = (ord_less_eq_nat @ Y @ X))))). % linorder_not_less
thf(fact_179_ab__left__minus, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ (uminus636303014nteger @ A) @ A) = zero_z413810534nteger)))). % ab_left_minus
thf(fact_180_ab__left__minus, axiom,
    ((![A : int]: ((plus_plus_int @ (uminus_uminus_int @ A) @ A) = zero_zero_int)))). % ab_left_minus
thf(fact_181_less__add__same__cancel2, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le945590961nteger @ A @ (plus_p2058578406nteger @ B @ A)) = (ord_le945590961nteger @ zero_z413810534nteger @ B))))). % less_add_same_cancel2
thf(fact_182_less__add__same__cancel2, axiom,
    ((![A : int, B : int]: ((ord_less_int @ A @ (plus_plus_int @ B @ A)) = (ord_less_int @ zero_zero_int @ B))))). % less_add_same_cancel2
thf(fact_183_less__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel2
thf(fact_184_double__add__less__zero__iff__single__add__less__zero, axiom,
    ((![A : code_integer]: ((ord_le945590961nteger @ (plus_p2058578406nteger @ A @ A) @ zero_z413810534nteger) = (ord_le945590961nteger @ A @ zero_z413810534nteger))))). % double_add_less_zero_iff_single_add_less_zero
thf(fact_185_double__add__less__zero__iff__single__add__less__zero, axiom,
    ((![A : int]: ((ord_less_int @ (plus_plus_int @ A @ A) @ zero_zero_int) = (ord_less_int @ A @ zero_zero_int))))). % double_add_less_zero_iff_single_add_less_zero
thf(fact_186_add__diff__cancel__left_H, axiom,
    ((![A : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ A @ B) @ A) = B)))). % add_diff_cancel_left'
thf(fact_187_add__diff__cancel__left_H, axiom,
    ((![A : code_integer, B : code_integer]: ((minus_1582103350nteger @ (plus_p2058578406nteger @ A @ B) @ A) = B)))). % add_diff_cancel_left'
thf(fact_188_add__diff__cancel__left_H, axiom,
    ((![A : int, B : int]: ((minus_minus_int @ (plus_plus_int @ A @ B) @ A) = B)))). % add_diff_cancel_left'
thf(fact_189_comm__monoid__mult__class_Omult__1, axiom,
    ((![A : nat]: ((times_times_nat @ one_one_nat @ A) = A)))). % comm_monoid_mult_class.mult_1
thf(fact_190_order__less__irrefl, axiom,
    ((![X : nat]: (~ ((ord_less_nat @ X @ X)))))). % order_less_irrefl
thf(fact_191_order__less__le, axiom,
    ((ord_less_nat = (^[X2 : nat]: (^[Y2 : nat]: (((ord_less_eq_nat @ X2 @ Y2)) & ((~ ((X2 = Y2)))))))))). % order_less_le
thf(fact_192_nat_Osimps_I3_J, axiom,
    ((![X22 : nat]: ((suc @ X22) != zero_zero_nat)))). % nat.simps(3)
thf(fact_193_comm__semiring__class_Odistrib, axiom,
    ((![A : nat, B : nat, C : nat]: ((times_times_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ (times_times_nat @ A @ C) @ (times_times_nat @ B @ C)))))). % comm_semiring_class.distrib
thf(fact_194_comm__semiring__class_Odistrib, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((times_1419655522nteger @ (plus_p2058578406nteger @ A @ B) @ C) = (plus_p2058578406nteger @ (times_1419655522nteger @ A @ C) @ (times_1419655522nteger @ B @ C)))))). % comm_semiring_class.distrib
thf(fact_195_comm__semiring__class_Odistrib, axiom,
    ((![A : int, B : int, C : int]: ((times_times_int @ (plus_plus_int @ A @ B) @ C) = (plus_plus_int @ (times_times_int @ A @ C) @ (times_times_int @ B @ C)))))). % comm_semiring_class.distrib
thf(fact_196_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(1)
thf(fact_197_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![I : code_integer, J : code_integer, K : code_integer, L : code_integer]: (((ord_le1426714813nteger @ I @ J) & (ord_le1426714813nteger @ K @ L)) => (ord_le1426714813nteger @ (plus_p2058578406nteger @ I @ K) @ (plus_p2058578406nteger @ J @ L)))))). % add_mono_thms_linordered_semiring(1)
thf(fact_198_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![I : int, J : int, K : int, L : int]: (((ord_less_eq_int @ I @ J) & (ord_less_eq_int @ K @ L)) => (ord_less_eq_int @ (plus_plus_int @ I @ K) @ (plus_plus_int @ J @ L)))))). % add_mono_thms_linordered_semiring(1)
thf(fact_199_add__less__le__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer, D : code_integer]: ((ord_le945590961nteger @ A @ B) => ((ord_le1426714813nteger @ C @ D) => (ord_le945590961nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ D))))))). % add_less_le_mono
thf(fact_200_add__less__le__mono, axiom,
    ((![A : int, B : int, C : int, D : int]: ((ord_less_int @ A @ B) => ((ord_less_eq_int @ C @ D) => (ord_less_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ D))))))). % add_less_le_mono
thf(fact_201_add__less__le__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_nat @ A @ B) => ((ord_less_eq_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_less_le_mono
thf(fact_202_add__le__less__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer, D : code_integer]: ((ord_le1426714813nteger @ A @ B) => ((ord_le945590961nteger @ C @ D) => (ord_le945590961nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ D))))))). % add_le_less_mono
thf(fact_203_add__le__less__mono, axiom,
    ((![A : int, B : int, C : int, D : int]: ((ord_less_eq_int @ A @ B) => ((ord_less_int @ C @ D) => (ord_less_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ D))))))). % add_le_less_mono
thf(fact_204_add__le__less__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_le_less_mono
thf(fact_205_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (K = L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(3)
thf(fact_206_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![I : code_integer, J : code_integer, K : code_integer, L : code_integer]: (((ord_le1426714813nteger @ I @ J) & (K = L)) => (ord_le1426714813nteger @ (plus_p2058578406nteger @ I @ K) @ (plus_p2058578406nteger @ J @ L)))))). % add_mono_thms_linordered_semiring(3)
thf(fact_207_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![I : int, J : int, K : int, L : int]: (((ord_less_eq_int @ I @ J) & (K = L)) => (ord_less_eq_int @ (plus_plus_int @ I @ K) @ (plus_plus_int @ J @ L)))))). % add_mono_thms_linordered_semiring(3)
thf(fact_208_add__neg__nonpos, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le945590961nteger @ A @ zero_z413810534nteger) => ((ord_le1426714813nteger @ B @ zero_z413810534nteger) => (ord_le945590961nteger @ (plus_p2058578406nteger @ A @ B) @ zero_z413810534nteger)))))). % add_neg_nonpos
thf(fact_209_add__neg__nonpos, axiom,
    ((![A : int, B : int]: ((ord_less_int @ A @ zero_zero_int) => ((ord_less_eq_int @ B @ zero_zero_int) => (ord_less_int @ (plus_plus_int @ A @ B) @ zero_zero_int)))))). % add_neg_nonpos
thf(fact_210_add__neg__nonpos, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ zero_zero_nat) => ((ord_less_eq_nat @ B @ zero_zero_nat) => (ord_less_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_neg_nonpos
thf(fact_211_add__nonneg__pos, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ zero_z413810534nteger @ A) => ((ord_le945590961nteger @ zero_z413810534nteger @ B) => (ord_le945590961nteger @ zero_z413810534nteger @ (plus_p2058578406nteger @ A @ B))))))). % add_nonneg_pos
thf(fact_212_add__nonneg__pos, axiom,
    ((![A : int, B : int]: ((ord_less_eq_int @ zero_zero_int @ A) => ((ord_less_int @ zero_zero_int @ B) => (ord_less_int @ zero_zero_int @ (plus_plus_int @ A @ B))))))). % add_nonneg_pos
thf(fact_213_add__nonneg__pos, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_nat @ zero_zero_nat @ B) => (ord_less_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_nonneg_pos
thf(fact_214_add__pos__nonneg, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le945590961nteger @ zero_z413810534nteger @ A) => ((ord_le1426714813nteger @ zero_z413810534nteger @ B) => (ord_le945590961nteger @ zero_z413810534nteger @ (plus_p2058578406nteger @ A @ B))))))). % add_pos_nonneg
thf(fact_215_add__pos__nonneg, axiom,
    ((![A : int, B : int]: ((ord_less_int @ zero_zero_int @ A) => ((ord_less_eq_int @ zero_zero_int @ B) => (ord_less_int @ zero_zero_int @ (plus_plus_int @ A @ B))))))). % add_pos_nonneg
thf(fact_216_add__pos__nonneg, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ zero_zero_nat @ B) => (ord_less_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_pos_nonneg
thf(fact_217_add__nonpos__neg, axiom,
    ((![A : code_integer, B : code_integer]: ((ord_le1426714813nteger @ A @ zero_z413810534nteger) => ((ord_le945590961nteger @ B @ zero_z413810534nteger) => (ord_le945590961nteger @ (plus_p2058578406nteger @ A @ B) @ zero_z413810534nteger)))))). % add_nonpos_neg
thf(fact_218_add__nonpos__neg, axiom,
    ((![A : int, B : int]: ((ord_less_eq_int @ A @ zero_zero_int) => ((ord_less_int @ B @ zero_zero_int) => (ord_less_int @ (plus_plus_int @ A @ B) @ zero_zero_int)))))). % add_nonpos_neg
thf(fact_219_add__nonpos__neg, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ zero_zero_nat) => ((ord_less_nat @ B @ zero_zero_nat) => (ord_less_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_nonpos_neg
thf(fact_220_canonically__ordered__monoid__add__class_OlessE, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ B) => (~ ((![C2 : nat]: ((B = (plus_plus_nat @ A @ C2)) => (C2 = zero_zero_nat))))))))). % canonically_ordered_monoid_add_class.lessE
thf(fact_221_mult__zero__left, axiom,
    ((![A : nat]: ((times_times_nat @ zero_zero_nat @ A) = zero_zero_nat)))). % mult_zero_left
thf(fact_222_mult__zero__left, axiom,
    ((![A : code_integer]: ((times_1419655522nteger @ zero_z413810534nteger @ A) = zero_z413810534nteger)))). % mult_zero_left
thf(fact_223_mult__zero__left, axiom,
    ((![A : int]: ((times_times_int @ zero_zero_int @ A) = zero_zero_int)))). % mult_zero_left
thf(fact_224_add__strict__increasing, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((ord_le945590961nteger @ zero_z413810534nteger @ A) => ((ord_le1426714813nteger @ B @ C) => (ord_le945590961nteger @ B @ (plus_p2058578406nteger @ A @ C))))))). % add_strict_increasing
thf(fact_225_add__strict__increasing, axiom,
    ((![A : int, B : int, C : int]: ((ord_less_int @ zero_zero_int @ A) => ((ord_less_eq_int @ B @ C) => (ord_less_int @ B @ (plus_plus_int @ A @ C))))))). % add_strict_increasing
thf(fact_226_add__strict__increasing, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ B @ C) => (ord_less_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_strict_increasing
thf(fact_227_diff__zero, axiom,
    ((![A : nat]: ((minus_minus_nat @ A @ zero_zero_nat) = A)))). % diff_zero
thf(fact_228_diff__zero, axiom,
    ((![A : code_integer]: ((minus_1582103350nteger @ A @ zero_z413810534nteger) = A)))). % diff_zero
thf(fact_229_diff__zero, axiom,
    ((![A : int]: ((minus_minus_int @ A @ zero_zero_int) = A)))). % diff_zero
thf(fact_230_add__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_eq_nat @ C @ D) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_mono
thf(fact_231_add__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer, D : code_integer]: ((ord_le1426714813nteger @ A @ B) => ((ord_le1426714813nteger @ C @ D) => (ord_le1426714813nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ D))))))). % add_mono
thf(fact_232_add__mono, axiom,
    ((![A : int, B : int, C : int, D : int]: ((ord_less_eq_int @ A @ B) => ((ord_less_eq_int @ C @ D) => (ord_less_eq_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ D))))))). % add_mono
thf(fact_233_add__strict__increasing2, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((ord_le1426714813nteger @ zero_z413810534nteger @ A) => ((ord_le945590961nteger @ B @ C) => (ord_le945590961nteger @ B @ (plus_p2058578406nteger @ A @ C))))))). % add_strict_increasing2
thf(fact_234_add__strict__increasing2, axiom,
    ((![A : int, B : int, C : int]: ((ord_less_eq_int @ zero_zero_int @ A) => ((ord_less_int @ B @ C) => (ord_less_int @ B @ (plus_plus_int @ A @ C))))))). % add_strict_increasing2
thf(fact_235_add__strict__increasing2, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_nat @ B @ C) => (ord_less_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_strict_increasing2
thf(fact_236_add__mono__thms__linordered__field_I3_J, axiom,
    ((![I : code_integer, J : code_integer, K : code_integer, L : code_integer]: (((ord_le945590961nteger @ I @ J) & (ord_le1426714813nteger @ K @ L)) => (ord_le945590961nteger @ (plus_p2058578406nteger @ I @ K) @ (plus_p2058578406nteger @ J @ L)))))). % add_mono_thms_linordered_field(3)
thf(fact_237_add__mono__thms__linordered__field_I3_J, axiom,
    ((![I : int, J : int, K : int, L : int]: (((ord_less_int @ I @ J) & (ord_less_eq_int @ K @ L)) => (ord_less_int @ (plus_plus_int @ I @ K) @ (plus_plus_int @ J @ L)))))). % add_mono_thms_linordered_field(3)
thf(fact_238_add__mono__thms__linordered__field_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(3)
thf(fact_239_bot__nat__0_Onot__eq__extremum, axiom,
    ((![A : nat]: ((~ ((A = zero_zero_nat))) = (ord_less_nat @ zero_zero_nat @ A))))). % bot_nat_0.not_eq_extremum
thf(fact_240_add__left__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ A @ B) => (ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)))))). % add_left_mono
thf(fact_241_add__left__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((ord_le1426714813nteger @ A @ B) => (ord_le1426714813nteger @ (plus_p2058578406nteger @ C @ A) @ (plus_p2058578406nteger @ C @ B)))))). % add_left_mono
thf(fact_242_add__left__mono, axiom,
    ((![A : int, B : int, C : int]: ((ord_less_eq_int @ A @ B) => (ord_less_eq_int @ (plus_plus_int @ C @ A) @ (plus_plus_int @ C @ B)))))). % add_left_mono
thf(fact_243_add__mono__thms__linordered__field_I4_J, axiom,
    ((![I : code_integer, J : code_integer, K : code_integer, L : code_integer]: (((ord_le1426714813nteger @ I @ J) & (ord_le945590961nteger @ K @ L)) => (ord_le945590961nteger @ (plus_p2058578406nteger @ I @ K) @ (plus_p2058578406nteger @ J @ L)))))). % add_mono_thms_linordered_field(4)
thf(fact_244_add__mono__thms__linordered__field_I4_J, axiom,
    ((![I : int, J : int, K : int, L : int]: (((ord_less_eq_int @ I @ J) & (ord_less_int @ K @ L)) => (ord_less_int @ (plus_plus_int @ I @ K) @ (plus_plus_int @ J @ L)))))). % add_mono_thms_linordered_field(4)
thf(fact_245_add__mono__thms__linordered__field_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(4)
thf(fact_246_ab__group__add__class_Oab__left__minus, axiom,
    ((![A : code_integer]: ((plus_p2058578406nteger @ (uminus636303014nteger @ A) @ A) = zero_z413810534nteger)))). % ab_group_add_class.ab_left_minus
thf(fact_247_ab__group__add__class_Oab__left__minus, axiom,
    ((![A : int]: ((plus_plus_int @ (uminus_uminus_int @ A) @ A) = zero_zero_int)))). % ab_group_add_class.ab_left_minus
thf(fact_248_add__strict__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer, D : code_integer]: ((ord_le945590961nteger @ A @ B) => ((ord_le945590961nteger @ C @ D) => (ord_le945590961nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ D))))))). % add_strict_mono
thf(fact_249_add__strict__mono, axiom,
    ((![A : int, B : int, C : int, D : int]: ((ord_less_int @ A @ B) => ((ord_less_int @ C @ D) => (ord_less_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ D))))))). % add_strict_mono
thf(fact_250_add__strict__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_nat @ A @ B) => ((ord_less_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_strict_mono
thf(fact_251_add__right__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ A @ B) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)))))). % add_right_mono
thf(fact_252_add__right__mono, axiom,
    ((![A : code_integer, B : code_integer, C : code_integer]: ((ord_le1426714813nteger @ A @ B) => (ord_le1426714813nteger @ (plus_p2058578406nteger @ A @ C) @ (plus_p2058578406nteger @ B @ C)))))). % add_right_mono
thf(fact_253_add__right__mono, axiom,
    ((![A : int, B : int, C : int]: ((ord_less_eq_int @ A @ B) => (ord_less_eq_int @ (plus_plus_int @ A @ C) @ (plus_plus_int @ B @ C)))))). % add_right_mono

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
