% /Applications/Isabelle2025.app/contrib/spass-3.8ds-2/x86_64-darwin/SPASS -Heuristic=2 -RNuV=1 -Sorts=0 -Isabelle=1 -TimeLimit=5 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5352506_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:44:14.312
begin_problem(isabelle).

list_of_descriptions.
name({**}).
author({**}).
status(unknown).
description({**}).
end_of_list.

list_of_symbols.
functions [(cOMBB_nat_nat_nat, 2), (comp_nat_nat_nat, 2), (comp_nat_nat_nat3, 3), (comm_monoid_nat, 1), (comm_monoid_nat2, 2), (comm_m2051353214ms_nat, 1), (comm_m1939377251s_nat2, 2), (minus_minus_nat, 0), (minus_minus_nat1, 1), (minus_minus_nat2, 2), (monoid_nat, 1), (monoid_nat2, 2), (monoid_axioms_nat, 1), (monoid_axioms_nat2, 2), (one_one_nat, 0), (plus_plus_nat, 0), (plus_plus_nat1, 1), (plus_plus_nat2, 2), (plus_plus_num, 2), (plus_plus_a, 2), (times_times_nat, 0), (times_times_nat1, 1), (times_times_nat2, 2), (zero_zero_nat, 0), (groups1842438620at_nat, 2), (groups1056228905et_nat, 1), (groups1479517816t_nat2, 2), (suC, 0), (suc1, 1), (bit0, 1), (onE, 0), (numeral_numeral_nat, 1), (ord_less_nat, 1), (ord_less_nat2, 2), (ord_less_eq_nat, 1), (ord_less_eq_nat2, 2), (zero_n1356753679ol_nat, 1), (set_or601162459st_nat, 2), (set_or562006527an_nat, 2), (set_ord_atMost_nat, 1), (aa_nat_bool, 2), (aa_nat_nat, 2), (aa_nat_fun_nat_nat, 2), (fFalsE, 0), (fTruE, 0), (x, 0), (y, 0)].
predicates [(abel_semigroup_nat, 1), (abel_s1659454557ms_nat, 1), (semigroup_nat, 1), (bot_bot_bool, 0), (ord_less_bool, 2), (ord_less_eq_bool, 2), (pp, 1)].
weights [(onE, 1), (bit0, 1), (suc1, 1), (fTruE, 1), (aa_nat_nat, 1), (monoid_nat2, 1), (one_one_nat, 1), (plus_plus_num, 1), (zero_zero_nat, 1), (comm_monoid_nat2, 1), (monoid_axioms_nat2, 1), (set_ord_atMost_nat, 1), (comm_m1939377251s_nat2, 1), (groups1479517816t_nat2, 1), (groups1056228905et_nat, 2), (comm_m2051353214ms_nat, 2), (monoid_axioms_nat, 2), (comm_monoid_nat, 2), (times_times_nat2, 2), (numeral_numeral_nat, 2), (zero_n1356753679ol_nat, 2), (monoid_nat, 2), (cOMBB_nat_nat_nat, 2), (comp_nat_nat_nat3, 2), (suC, 2), (comp_nat_nat_nat, 4), (times_times_nat1, 4), (plus_plus_nat2, 4), (times_times_nat, 8), (plus_plus_nat1, 8), (groups1842438620at_nat, 8), (ord_less_nat2, 8), (minus_minus_nat2, 8), (ord_less_eq_nat2, 8), (plus_plus_nat, 16), (ord_less_eq_nat, 16), (minus_minus_nat1, 16), (ord_less_nat, 16), (minus_minus_nat, 32)].
sorts [fun_nat_fun_nat_nat, fun_nat_bool, fun_nat_nat, set_nat, booL, nuM, naT, a, iii].
% classes [].
end_of_list.

list_of_declarations.
function(cOMBB_nat_nat_nat, (fun_nat_nat, fun_nat_nat) fun_nat_nat).
function(comp_nat_nat_nat, (fun_nat_nat, fun_nat_nat) fun_nat_nat).
function(comp_nat_nat_nat3, (fun_nat_nat, fun_nat_nat, naT) naT).
function(comm_monoid_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(comm_monoid_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(comm_m2051353214ms_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(comm_m1939377251s_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(minus_minus_nat, fun_nat_fun_nat_nat).
function(minus_minus_nat1, (naT) fun_nat_nat).
function(minus_minus_nat2, (naT, naT) naT).
function(monoid_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(monoid_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(monoid_axioms_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(monoid_axioms_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(one_one_nat, naT).
function(plus_plus_nat, fun_nat_fun_nat_nat).
function(plus_plus_nat1, (naT) fun_nat_nat).
function(plus_plus_nat2, (naT, naT) naT).
function(plus_plus_num, (nuM, nuM) nuM).
function(plus_plus_a, (a, a) a).
function(times_times_nat, fun_nat_fun_nat_nat).
function(times_times_nat1, (naT) fun_nat_nat).
function(times_times_nat2, (naT, naT) naT).
function(zero_zero_nat, naT).
function(groups1842438620at_nat, (fun_nat_nat, set_nat) naT).
function(groups1056228905et_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(groups1479517816t_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(suC, fun_nat_nat).
function(suc1, (naT) naT).
function(bit0, (nuM) nuM).
function(onE, nuM).
function(numeral_numeral_nat, (nuM) naT).
function(ord_less_nat, (naT) fun_nat_bool).
function(ord_less_nat2, (naT, naT) booL).
function(ord_less_eq_nat, (naT) fun_nat_bool).
function(ord_less_eq_nat2, (naT, naT) booL).
function(zero_n1356753679ol_nat, (booL) naT).
function(set_or601162459st_nat, (naT, naT) set_nat).
function(set_or562006527an_nat, (naT, naT) set_nat).
function(set_ord_atMost_nat, (naT) set_nat).
function(aa_nat_bool, (fun_nat_bool, naT) booL).
function(aa_nat_nat, (fun_nat_nat, naT) naT).
function(aa_nat_fun_nat_nat, (fun_nat_fun_nat_nat, naT) fun_nat_nat).
function(fFalsE, booL).
function(fTruE, booL).
function(x, a).
function(y, a).
predicate(abel_semigroup_nat, fun_nat_fun_nat_nat).
predicate(abel_s1659454557ms_nat, fun_nat_fun_nat_nat).
predicate(semigroup_nat, fun_nat_fun_nat_nat).
predicate(ord_less_bool, booL, booL).
predicate(ord_less_eq_bool, booL, booL).
predicate(pp, booL).
end_of_list.

list_of_formulae(axioms).
formula(forall([B_1 : naT], equal:lt(aa_nat_nat(suC, B_1), suc1(B_1))), unc_c_Nat_OSuc_0001).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(monoid_nat(B_1), B_2), monoid_nat2(B_1, B_2))), unc_c_Groups_Omonoid_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(comm_monoid_nat(B_1), B_2), comm_monoid_nat2(B_1, B_2))), unc_c_Groups_Ocomm__monoid_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(monoid_axioms_nat(B_1), B_2), monoid_axioms_nat2(B_1, B_2))), unc_c_Groups_Omonoid__axioms_001t__Nat__Onat_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(plus_plus_nat, B_1), plus_plus_nat1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(plus_plus_nat1(B_1), B_2), plus_plus_nat2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(minus_minus_nat, B_1), minus_minus_nat1(B_1))), unc_c_Groups_Ominus__class_Ominus_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(minus_minus_nat1(B_1), B_2), minus_minus_nat2(B_1, B_2))), unc_c_Groups_Ominus__class_Ominus_001t__Nat__Onat_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(times_times_nat, B_1), times_times_nat1(B_1))), unc_c_Groups_Otimes__class_Otimes_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(times_times_nat1(B_1), B_2), times_times_nat2(B_1, B_2))), unc_c_Groups_Otimes__class_Otimes_001t__Nat__Onat_0002).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_bool(ord_less_nat(B_1), B_2), ord_less_nat2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(comm_m2051353214ms_nat(B_1), B_2), comm_m1939377251s_nat2(B_1, B_2))), unc_c_Groups_Ocomm__monoid__axioms_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(groups1056228905et_nat(B_1), B_2), groups1479517816t_nat2(B_1, B_2))), unc_c_Groups__Big_Ocomm__monoid__set_001t__Nat__Onat_0002).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_bool(ord_less_eq_nat(B_1), B_2), ord_less_eq_nat2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_nat_nat, B_2 : fun_nat_nat, B_3 : naT], equal:lt(aa_nat_nat(comp_nat_nat_nat(B_1, B_2), B_3), comp_nat_nat_nat3(B_1, B_2, B_3))), unc_c_Fun_Ocomp_001t__Nat__Onat_001t__Nat__Onat_001t__Nat__Onat_0003).

formula(forall([A : naT, B : naT, C : naT], equiv(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_0_add__left__cancel, 900). % add_left_cancel
formula(forall([F : fun_nat_fun_nat_nat], implies(forall([A2 : naT, B2 : naT, C2 : naT], equal(aa_nat_nat(aa_nat_fun_nat_nat(F, aa_nat_nat(aa_nat_fun_nat_nat(F, A2), B2)), C2), aa_nat_nat(aa_nat_fun_nat_nat(F, A2), aa_nat_nat(aa_nat_fun_nat_nat(F, B2), C2)))), semigroup_nat(F))), fact_1_semigroup_Ointro, 912). % semigroup.intro
formula(forall([B : naT, A : naT, C : naT], equiv(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_2_add__right__cancel, 925). % add_right_cancel
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_3_ab__semigroup__add__class_Oadd__ac_I1_J, 937). % ab_semigroup_add_class.add_ac(1)
formula(forall([V : nuM, W : nuM, Z : naT], equal(plus_plus_nat2(numeral_numeral_nat(V), plus_plus_nat2(numeral_numeral_nat(W), Z)), plus_plus_nat2(numeral_numeral_nat(plus_plus_num(V, W)), Z))), fact_4_add__numeral__left, 950). % add_numeral_left
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), equal(K, L)), equal(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_5_add__mono__thms__linordered__semiring_I4_J, 962). % add_mono_thms_linordered_semiring(4)
formula(forall([A3 : naT, K : naT, A : naT, B : naT], implies(equal(A3, plus_plus_nat2(K, A)), equal(plus_plus_nat2(A3, B), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_6_group__cancel_Oadd1, 975). % group_cancel.add1
formula(forall([F : fun_nat_fun_nat_nat, A : naT, B : naT], implies(abel_semigroup_nat(F), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, A), B), aa_nat_nat(aa_nat_fun_nat_nat(F, B), A)))), fact_7_abel__semigroup_Ocommute, 987). % abel_semigroup.commute
formula(forall([B3 : naT, K : naT, B : naT, A : naT], implies(equal(B3, plus_plus_nat2(K, B)), equal(plus_plus_nat2(A, B3), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_8_group__cancel_Oadd2). % group_cancel.add2
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_9_add_Oright__neutral, 1013). % add.right_neutral
formula(forall([A : naT, B : naT], equal(plus_plus_nat2(A, B), plus_plus_nat2(B, A))), fact_10_add_Ocommute, 1025). % add.commute
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_11_add__0, 1038). % add_0
formula(forall([F : fun_nat_fun_nat_nat], implies(semigroup_nat(F), implies(abel_s1659454557ms_nat(F), abel_semigroup_nat(F)))), fact_12_abel__semigroup_Ointro, 1050). % abel_semigroup.intro
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_13_add_Oassoc, 1063). % add.assoc
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(pp(monoid_nat2(F, Z)), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, A), Z), A))), fact_14_monoid_Oright__neutral, 1075). % monoid.right_neutral
formula(forall([B : naT, A : naT, C : naT], equal(plus_plus_nat2(B, plus_plus_nat2(A, C)), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_15_add_Oleft__commute, 1088). % add.left_commute
formula(forall([A : naT, B : naT, C : naT], implies(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_16_add__left__imp__eq, 1100). % add_left_imp_eq
formula(forall([B : naT, A : naT, C : naT], implies(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_17_add__right__imp__eq, 1113). % add_right_imp_eq
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(semigroup_nat(F), implies(pp(monoid_axioms_nat2(F, Z)), pp(monoid_nat2(F, Z))))), fact_18_monoid_Ointro, 1126). % monoid.intro
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_19_comm__monoid__add__class_Oadd__0, 1138). % comm_monoid_add_class.add_0
formula(forall([A : booL], ord_less_eq_bool(A, A)), fact_20_dual__order_Orefl, 1151). % dual_order.refl
formula(forall([A : naT], pp(ord_less_eq_nat2(A, A))), fact_21_dual__order_Orefl, 1163). % dual_order.refl
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(A, B)), equal(B, zero_zero_nat))), fact_22_add__cancel__right__right, 1176). % add_cancel_right_right
formula(forall([A : naT, B : naT], equiv(equal(plus_plus_nat2(A, B), A), equal(B, zero_zero_nat))), fact_23_add__cancel__left__right, 1188). % add_cancel_left_right
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(B, A)), equal(B, zero_zero_nat))), fact_24_add__cancel__right__left, 1201). % add_cancel_right_left
formula(forall([X : naT, Y : naT], equiv(equal(plus_plus_nat2(X, Y), zero_zero_nat), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_25_add__eq__0__iff__both__eq__0, 1213). % add_eq_0_iff_both_eq_0
formula(forall([X : naT, Y : naT], equiv(equal(zero_zero_nat, plus_plus_nat2(X, Y)), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_26_zero__eq__add__iff__both__eq__0, 1226). % zero_eq_add_iff_both_eq_0
formula(forall([B : naT, A : naT], equiv(equal(plus_plus_nat2(B, A), A), equal(B, zero_zero_nat))), fact_27_add__cancel__left__left, 1239). % add_cancel_left_left
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(abel_semigroup_nat(F), implies(pp(comm_m1939377251s_nat2(F, Z)), pp(comm_monoid_nat2(F, Z))))), fact_28_comm__monoid_Ointro, 1251). % comm_monoid.intro
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(pp(monoid_nat2(F, Z)), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, Z), A), A))), fact_29_monoid_Oleft__neutral, 1264). % monoid.left_neutral
formula(forall([M : nuM, N : nuM], equal(plus_plus_nat2(numeral_numeral_nat(M), numeral_numeral_nat(N)), numeral_numeral_nat(plus_plus_num(M, N)))), fact_30_numeral__plus__numeral, 1276). % numeral_plus_numeral
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_31_add_Ocomm__neutral, 1289). % add.comm_neutral
formula(forall([C : naT, A : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_eq_nat2(A, B)))), fact_32_add__le__cancel__left, 1301). % add_le_cancel_left
formula(forall([F : fun_nat_fun_nat_nat, B : naT, A : naT, C : naT], implies(abel_semigroup_nat(F), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, B), aa_nat_nat(aa_nat_fun_nat_nat(F, A), C)), aa_nat_nat(aa_nat_fun_nat_nat(F, A), aa_nat_nat(aa_nat_fun_nat_nat(F, B), C))))), fact_33_abel__semigroup_Oleft__commute, 1314). % abel_semigroup.left_commute
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_34_verit__sum__simplify, 1326). % verit_sum_simplify
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], implies(pp(comm_monoid_nat2(F, Z)), pp(groups1479517816t_nat2(F, Z)))), fact_35_comm__monoid__set_Ointro, 1339). % comm_monoid_set.intro
formula(forall([M : naT, N : naT], equal(plus_plus_nat2(M, suc1(N)), suc1(plus_plus_nat2(M, N)))), fact_36_add__Suc__right, 1352). % add_Suc_right
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), pp(ord_less_eq_nat2(K, L))), pp(ord_less_eq_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_37_add__mono__thms__linordered__semiring_I1_J, 1364). % add_mono_thms_linordered_semiring(1)
formula(forall([X : naT], equiv(equal(zero_zero_nat, X), equal(X, zero_zero_nat))), fact_38_zero__reorient, 1377). % zero_reorient
formula(pp(comm_monoid_nat2(plus_plus_nat, zero_zero_nat)), fact_39_add_Ocomm__monoid__axioms, 1389). % add.comm_monoid_axioms
formula(pp(monoid_nat2(plus_plus_nat, zero_zero_nat)), fact_40_add_Omonoid__axioms, 1402). % add.monoid_axioms
formula(forall([B : naT, A : naT], equiv(equal(B, plus_plus_nat2(B, A)), equal(A, zero_zero_nat))), fact_41_add__0__iff, 1414). % add_0_iff
formula(forall([X : booL], not(ord_less_bool(X, X))), fact_42_order__less__irrefl, 1427). % order_less_irrefl
formula(forall([X : naT], not(pp(ord_less_nat2(X, X)))), fact_43_order__less__irrefl, 1440). % order_less_irrefl
formula(forall([F : fun_nat_fun_nat_nat, Z : naT, A : naT], implies(pp(comm_monoid_nat2(F, Z)), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, A), Z), A))), fact_44_comm__monoid_Ocomm__neutral, 1452). % comm_monoid.comm_neutral
formula(equal:lt(one_one_nat, suc1(zero_zero_nat)), fact_45_One__nat__def, 1465). % One_nat_def
formula(forall([A : naT], equal(A, plus_plus_nat2(A, zero_zero_nat))), fact_46_nat__arith_Orule0, 1477). % nat_arith.rule0
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), equal(K, L)), pp(ord_less_eq_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_47_add__mono__thms__linordered__semiring_I3_J, 1490). % add_mono_thms_linordered_semiring(3)
formula(forall([F : fun_nat_nat, G : fun_nat_nat, X : naT], equal(comp_nat_nat_nat3(F, G, X), aa_nat_nat(F, aa_nat_nat(G, X)))), fact_48_o__apply, 1502). % o_apply
formula(forall([A : booL, B : booL, C : booL], implies(equiv(pp(A), pp(B)), implies(ord_less_eq_bool(B, C), ord_less_eq_bool(A, C)))), fact_49_ord__eq__le__trans, 1515). % ord_eq_le_trans
formula(forall([A : naT, B : naT, C : naT], implies(equal(A, B), implies(pp(ord_less_eq_nat2(B, C)), pp(ord_less_eq_nat2(A, C))))), fact_50_ord__eq__le__trans, 1527). % ord_eq_le_trans
formula(forall([X : booL, Y : booL], implies(ord_less_eq_bool(X, Y), implies(ord_less_eq_bool(Y, X), equiv(pp(X), pp(Y))))), fact_51_order__antisym, 1540). % order_antisym
formula(forall([X : naT, Y : naT], implies(pp(ord_less_eq_nat2(X, Y)), implies(pp(ord_less_eq_nat2(Y, X)), equal(X, Y)))), fact_52_order__antisym, 1553). % order_antisym
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(A, plus_plus_nat2(A, B))), pp(ord_less_eq_nat2(zero_zero_nat, B)))), fact_53_le__add__same__cancel1, 1565). % le_add_same_cancel1
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(A, plus_plus_nat2(B, A))), pp(ord_less_eq_nat2(zero_zero_nat, B)))), fact_54_le__add__same__cancel2, 1578). % le_add_same_cancel2
formula(forall([X : booL, Y : booL, Z : booL], implies(ord_less_eq_bool(X, Y), implies(ord_less_eq_bool(Y, Z), ord_less_eq_bool(X, Z)))), fact_55_order__trans, 1590). % order_trans
formula(forall([X : naT, Y : naT, Z : naT], implies(pp(ord_less_eq_nat2(X, Y)), implies(pp(ord_less_eq_nat2(Y, Z)), pp(ord_less_eq_nat2(X, Z))))), fact_56_order__trans, 1603). % order_trans
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_nat2(I, J)), pp(ord_less_eq_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_57_add__mono__thms__linordered__field_I3_J, 1615). % add_mono_thms_linordered_field(3)
formula(forall([N : naT], equiv(pp(ord_less_eq_nat2(N, zero_zero_nat)), equal(N, zero_zero_nat))), fact_58_le__zero__eq, 1628). % le_zero_eq
formula(forall([B : naT, A : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(B, A), B)), pp(ord_less_eq_nat2(A, zero_zero_nat)))), fact_59_add__le__same__cancel1, 1640). % add_le_same_cancel1
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(A, B), B)), pp(ord_less_eq_nat2(A, zero_zero_nat)))), fact_60_add__le__same__cancel2, 1653). % add_le_same_cancel2
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), pp(ord_less_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_61_add__mono__thms__linordered__field_I4_J, 1666). % add_mono_thms_linordered_field(4)
formula(forall([A : naT, C : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_nat2(A, B)))), fact_62_add__less__cancel__right, 1678). % add_less_cancel_right
formula(forall([X : naT], pp(ord_less_eq_nat2(zero_zero_nat, X))), fact_63_zero__le, 1691). % zero_le
formula(forall([F : fun_nat_fun_nat_nat, A : naT, B : naT, C : naT], implies(semigroup_nat(F), equal(aa_nat_nat(aa_nat_fun_nat_nat(F, aa_nat_nat(aa_nat_fun_nat_nat(F, A), B)), C), aa_nat_nat(aa_nat_fun_nat_nat(F, A), aa_nat_nat(aa_nat_fun_nat_nat(F, B), C))))), fact_64_semigroup_Oassoc, 1703). % semigroup.assoc
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_nat2(I, J)), equal(K, L)), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_65_add__mono__thms__linordered__field_I1_J, 1716). % add_mono_thms_linordered_field(1)
formula(forall([N : naT], equiv(not(pp(ord_less_nat2(zero_zero_nat, N))), equal(N, zero_zero_nat))), fact_66_not__gr__zero, 1728). % not_gr_zero
formula(forall([A : naT, C : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_eq_nat2(A, B)))), fact_67_add__le__cancel__right, 1741). % add_le_cancel_right
formula(forall([C : naT, A : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_nat2(A, B)))), fact_68_add__less__cancel__left, 1753). % add_less_cancel_left
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_nat2(I, J)), pp(ord_less_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_69_add__mono__thms__linordered__field_I5_J, 1766). % add_mono_thms_linordered_field(5)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), pp(ord_less_eq_nat2(K, L))), pp(ord_less_eq_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_70_add__mono__thms__linordered__semiring_I2_J, 1779). % add_mono_thms_linordered_semiring(2)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), pp(ord_less_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_71_add__mono__thms__linordered__field_I2_J, 1791). % add_mono_thms_linordered_field(2)
formula(forall([X : booL, Y : booL], equiv(not(ord_less_bool(X, Y)), ord_less_eq_bool(Y, X))), fact_72_linorder__not__less, 1804). % linorder_not_less
formula(forall([X : naT, Y : naT], equiv(not(pp(ord_less_nat2(X, Y))), pp(ord_less_eq_nat2(Y, X)))), fact_73_linorder__not__less, 1816). % linorder_not_less
formula(forall([X2_ : naT], not(equal(suc1(X2_), zero_zero_nat))), fact_74_nat_Osimps_I3_J, 1829). % nat.simps(3)
formula(forall([F : fun_nat_nat, G : fun_nat_nat, X2 : naT], equal:lt(comp_nat_nat_nat3(F, G, X2), aa_nat_nat(F, aa_nat_nat(G, X2)))), fact_75_o__def, 1841). % o_def
formula(forall([B : naT, A : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(B, A), B)), pp(ord_less_nat2(A, zero_zero_nat)))), fact_76_add__less__same__cancel1, 1854). % add_less_same_cancel1
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(A, B), B)), pp(ord_less_nat2(A, zero_zero_nat)))), fact_77_add__less__same__cancel2, 1866). % add_less_same_cancel2
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(A, plus_plus_nat2(A, B))), pp(ord_less_nat2(zero_zero_nat, B)))), fact_78_less__add__same__cancel1, 1879). % less_add_same_cancel1
formula(forall([A : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(A, B), A), B)), fact_79_add__diff__cancel__left_H, 1892). % add_diff_cancel_left'
formula(forall([A : naT], equal(times_times_nat2(one_one_nat, A), A)), fact_80_mult__1, 1904). % mult_1
formula(forall([N : naT], not(pp(ord_less_nat2(N, zero_zero_nat)))), fact_81_not__less__zero, 1917). % not_less_zero
formula(forall([X : booL, Y : booL], equiv(ord_less_bool(X, Y), and(ord_less_eq_bool(X, Y), not(equiv(pp(X), pp(Y)))))), fact_82_order__less__le, 1929). % order_less_le
formula(forall([X : naT, Y : naT], equiv(pp(ord_less_nat2(X, Y)), and(pp(ord_less_eq_nat2(X, Y)), not(equal(X, Y))))), fact_83_order__less__le, 1942). % order_less_le
formula(not(bot_bot_bool), fact_84_bot__bool__def, 1954). % bot_bool_def
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(A, plus_plus_nat2(B, A))), pp(ord_less_nat2(zero_zero_nat, B)))), fact_85_less__add__same__cancel2, 1967). % less_add_same_cancel2
formula(forall([A : booL, B : booL], implies(ord_less_eq_bool(A, B), implies(ord_less_eq_bool(B, A), equiv(pp(A), pp(B))))), fact_86_antisym, 1980). % antisym
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(pp(ord_less_eq_nat2(B, A)), equal(A, B)))), fact_87_antisym, 1992). % antisym
formula(forall([A : naT], equal(times_times_nat2(A, one_one_nat), A)), fact_88_mult_Oright__neutral, 2005). % mult.right_neutral
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(A, B)), exists([C3 : naT], equal(B, plus_plus_nat2(A, C3))))), fact_89_le__iff__add, 2017). % le_iff_add
formula(forall([X : booL, Y : booL], implies(equiv(pp(X), pp(Y)), ord_less_eq_bool(X, Y))), fact_90_order__eq__refl, 2030). % order_eq_refl
formula(forall([X : naT, Y : naT], implies(equal(X, Y), pp(ord_less_eq_nat2(X, Y)))), fact_91_order__eq__refl, 2042). % order_eq_refl
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(pp(ord_less_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_92_add__le__less__mono, 2055). % add_le_less_mono
formula(forall([A : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(A, B), B), A)), fact_93_add__diff__cancel__right_H, 2067). % add_diff_cancel_right'
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_nat2(A, B)), implies(pp(ord_less_eq_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_94_add__less__le__mono, 2080). % add_less_le_mono
formula(forall([M : naT, N : naT], equal(plus_plus_nat2(suc1(M), N), suc1(plus_plus_nat2(M, N)))), fact_95_add__Suc, 2093). % add_Suc
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_96_add__pos__nonneg, 2105). % add_pos_nonneg
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(B, C)), pp(ord_less_nat2(B, plus_plus_nat2(A, C)))))), fact_97_add__strict__increasing2, 2118). % add_strict_increasing2
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(A, B)), not(forall([C2 : naT], not(equal(B, plus_plus_nat2(A, C2))))))), fact_98_less__eqE, 2130). % less_eqE
formula(forall([A : naT], equal(times_times_nat2(one_one_nat, A), A)), fact_99_comm__monoid__mult__class_Omult__1, 2143). % comm_monoid_mult_class.mult_1
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(B, C)), pp(ord_less_nat2(B, plus_plus_nat2(A, C)))))), fact_100_add__strict__increasing, 2155). % add_strict_increasing
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, zero_zero_nat)), implies(pp(ord_less_eq_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_101_add__neg__nonpos, 2168). % add_neg_nonpos
formula(forall([B4 : booL, A4 : booL], equiv(not(ord_less_eq_bool(B4, A4)), ord_less_bool(A4, B4))), fact_102_verit__comp__simplify1_I3_J, 2180). % verit_comp_simplify1(3)
formula(forall([B4 : naT, A4 : naT], equiv(not(pp(ord_less_eq_nat2(B4, A4))), pp(ord_less_nat2(A4, B4)))), fact_103_verit__comp__simplify1_I3_J, 2193). % verit_comp_simplify1(3)
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(A, zero_zero_nat)), implies(pp(ord_less_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_104_add__nonpos__neg, 2206). % add_nonpos_neg
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(pp(ord_less_eq_nat2(C, D)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_105_add__mono, 2218). % add_mono
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))))), fact_106_add__right__mono, 2231). % add_right_mono
formula(forall([A : booL], ord_less_eq_bool(A, A)), fact_107_verit__comp__simplify1_I2_J, 2243). % verit_comp_simplify1(2)
formula(forall([A : naT], pp(ord_less_eq_nat2(A, A))), fact_108_verit__comp__simplify1_I2_J, 2256). % verit_comp_simplify1(2)
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_109_add__nonneg__pos, 2268). % add_nonneg_pos
formula(forall([A : naT, B : naT], equal(times_times_nat2(A, B), times_times_nat2(B, A))), fact_110_mult_Ocommute, 2281). % mult.commute
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))))), fact_111_add__left__mono, 2293). % add_left_mono
formula(forall([A : naT, B : naT, C : naT], equal(times_times_nat2(A, plus_plus_nat2(B, C)), plus_plus_nat2(times_times_nat2(A, B), times_times_nat2(A, C)))), fact_112_distrib__left, 2306). % distrib_left
formula(forall([A : booL], not(ord_less_bool(A, A))), fact_113_verit__comp__simplify1_I1_J, 2319). % verit_comp_simplify1(1)
formula(forall([A : naT], not(pp(ord_less_nat2(A, A)))), fact_114_verit__comp__simplify1_I1_J, 2331). % verit_comp_simplify1(1)
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, B)), not(forall([C2 : naT], implies(equal(B, plus_plus_nat2(A, C2)), equal(C2, zero_zero_nat)))))), fact_115_canonically__ordered__monoid__add__class_OlessE, 2344). % canonically_ordered_monoid_add_class.lessE
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_nat2(A, B)), implies(pp(ord_less_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_116_add__strict__mono, 2356). % add_strict_mono
formula(forall([A : naT, C : naT, B : naT], implies(pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_nat2(A, B)))), fact_117_add__less__imp__less__right, 2369). % add_less_imp_less_right
formula(forall([A : booL, B : booL], or(equiv(pp(A), pp(B)), or(not(ord_less_eq_bool(A, B)), not(ord_less_eq_bool(B, A))))), fact_118_verit__la__disequality, 2381). % verit_la_disequality
formula(forall([A : naT, B : naT], or(equal(A, B), or(not(pp(ord_less_eq_nat2(A, B))), not(pp(ord_less_eq_nat2(B, A)))))), fact_119_verit__la__disequality, 2394). % verit_la_disequality
formula(forall([C : naT, A : naT, B : naT], implies(pp(ord_less_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_nat2(A, B)))), fact_120_add__less__imp__less__left, 2406). % add_less_imp_less_left
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(A, B)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))))), fact_121_add__strict__right__mono, 2419). % add_strict_right_mono
formula(forall([A : naT, B : naT, C : naT], equal(times_times_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(times_times_nat2(A, C), times_times_nat2(B, C)))), fact_122_comm__semiring__class_Odistrib, 2432). % comm_semiring_class.distrib
formula(forall([P : booL, Q : booL], implies(implies(pp(P), pp(Q)), ord_less_eq_bool(P, Q))), fact_123_le__boolI_H, 2444). % le_boolI'
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(A, B)), pp(ord_less_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))))), fact_124_add__strict__left__mono, 2457). % add_strict_left_mono
formula(forall([N : naT], equiv(pp(ord_less_nat2(zero_zero_nat, N)), not(equal(N, zero_zero_nat)))), fact_125_zero__less__iff__neq__zero, 2469). % zero_less_iff_neq_zero
formula(forall([M : naT, N : naT], implies(pp(ord_less_nat2(M, N)), not(equal(N, zero_zero_nat)))), fact_126_gr__implies__not__zero, 2482). % gr_implies_not_zero
formula(forall([A : booL, B : booL], equiv(not(ord_less_eq_bool(A, B)), and(ord_less_eq_bool(B, A), not(equiv(pp(B), pp(A)))))), fact_127_nle__le, 2494). % nle_le
formula(forall([A : naT, B : naT], equiv(not(pp(ord_less_eq_nat2(A, B))), and(pp(ord_less_eq_nat2(B, A)), not(equal(B, A))))), fact_128_nle__le, 2507). % nle_le
formula(forall([A : naT], equiv(not(equal(A, zero_zero_nat)), pp(ord_less_nat2(zero_zero_nat, A)))), fact_129_bot__nat__0_Onot__eq__extremum, 2520). % bot_nat_0.not_eq_extremum
formula(forall([C : naT, A : naT, B : naT], implies(pp(ord_less_eq_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_eq_nat2(A, B)))), fact_130_add__le__imp__le__left, 2532). % add_le_imp_le_left
formula(forall([A : naT, C : naT, B : naT], implies(pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_eq_nat2(A, B)))), fact_131_add__le__imp__le__right, 2545). % add_le_imp_le_right
formula(forall([N : naT], implies(not(equal(N, zero_zero_nat)), pp(ord_less_nat2(zero_zero_nat, N)))), fact_132_gr__zeroI, 2557). % gr_zeroI
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_133_add__pos__pos, 2570). % add_pos_pos
formula(equal:lt(numeral_numeral_nat(onE), one_one_nat), fact_134_numeral__One, 2582). % numeral_One
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(zero_zero_nat, B)), pp(ord_less_eq_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_135_add__nonneg__nonneg, 2595). % add_nonneg_nonneg
formula(not(pp(ord_less_nat2(zero_zero_nat, zero_zero_nat))), fact_136_less__numeral__extra_I3_J, 2607). % less_numeral_extra(3)
formula(pp(ord_less_eq_nat2(zero_zero_nat, zero_zero_nat)), fact_137_le__numeral__extra_I3_J, 2620). % le_numeral_extra(3)
formula(forall([A : booL, B : booL], equiv(not(ord_less_bool(A, B)), or(not(ord_less_eq_bool(A, B)), equiv(pp(A), pp(B))))), fact_138_nless__le, 2633). % nless_le
formula(forall([A : naT, B : naT], equiv(not(pp(ord_less_nat2(A, B))), or(not(pp(ord_less_eq_nat2(A, B))), equal(A, B)))), fact_139_nless__le, 2645). % nless_le
formula(forall([A3 : naT, K : naT, A : naT], implies(equal(A3, plus_plus_nat2(K, A)), equal(suc1(A3), plus_plus_nat2(K, suc1(A))))), fact_140_nat__arith_Osuc1, 2658). % nat_arith.suc1
formula(forall([X : naT, Y : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, X)), implies(pp(ord_less_eq_nat2(zero_zero_nat, Y)), equiv(equal(plus_plus_nat2(X, Y), zero_zero_nat), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))))), fact_141_add__nonneg__eq__0__iff, 2670). % add_nonneg_eq_0_iff
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, zero_zero_nat)), implies(pp(ord_less_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_142_add__neg__neg, 2683). % add_neg_neg
formula(forall([X : booL, Y : booL], or(ord_less_eq_bool(X, Y), ord_less_eq_bool(Y, X))), fact_143_linorder__linear, 2695). % linorder_linear
formula(forall([X : naT, Y : naT], or(pp(ord_less_eq_nat2(X, Y)), pp(ord_less_eq_nat2(Y, X)))), fact_144_linorder__linear, 2708). % linorder_linear
formula(forall([X : naT, Y : naT], implies(pp(ord_less_eq_nat2(X, zero_zero_nat)), implies(pp(ord_less_eq_nat2(Y, zero_zero_nat)), equiv(equal(plus_plus_nat2(X, Y), zero_zero_nat), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))))), fact_145_add__nonpos__eq__0__iff, 2720). % add_nonpos_eq_0_iff
formula(forall([A : booL, B : booL, C : booL], implies(ord_less_eq_bool(A, B), implies(equiv(pp(B), pp(C)), ord_less_eq_bool(A, C)))), fact_146_ord__le__eq__trans, 2733). % ord_le_eq_trans
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(equal(B, C), pp(ord_less_eq_nat2(A, C))))), fact_147_ord__le__eq__trans, 2746). % ord_le_eq_trans
formula(forall([X : booL, Y : booL], equiv(not(ord_less_eq_bool(X, Y)), ord_less_bool(Y, X))), fact_148_linorder__not__le, 2758). % linorder_not_le
formula(forall([X : naT, Y : naT], equiv(not(pp(ord_less_eq_nat2(X, Y))), pp(ord_less_nat2(Y, X)))), fact_149_linorder__not__le, 2771). % linorder_not_le
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(B, C)), pp(ord_less_eq_nat2(B, plus_plus_nat2(A, C)))))), fact_150_add__increasing, 2783). % add_increasing
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(A, zero_zero_nat)), implies(pp(ord_less_eq_nat2(B, zero_zero_nat)), pp(ord_less_eq_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_151_add__nonpos__nonpos, 2796). % add_nonpos_nonpos
formula(forall([C : naT, B : naT, A : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, C)), implies(pp(ord_less_eq_nat2(B, A)), pp(ord_less_eq_nat2(B, plus_plus_nat2(A, C)))))), fact_152_add__increasing2, 2808). % add_increasing2
formula(forall([A : naT, C : naT, B : naT], implies(pp(ord_less_eq_nat2(A, zero_zero_nat)), implies(pp(ord_less_eq_nat2(C, B)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), B))))), fact_153_add__decreasing, 2821). % add_decreasing
formula(forall([A : naT], pp(ord_less_eq_nat2(zero_zero_nat, A))), fact_154_bot__nat__0_Oextremum, 2833). % bot_nat_0.extremum
formula(forall([C : naT, A : naT, B : naT], implies(pp(ord_less_eq_nat2(C, zero_zero_nat)), implies(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), B))))), fact_155_add__decreasing2, 2846). % add_decreasing2
formula(forall([C : naT, A : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B)), minus_minus_nat2(A, B))), fact_156_add__diff__cancel__left, 2859). % add_diff_cancel_left
formula(forall([X : booL, Y : booL], equiv(ord_less_eq_bool(X, Y), or(ord_less_bool(X, Y), equiv(pp(X), pp(Y))))), fact_157_order__le__less, 2871). % order_le_less
formula(forall([X : naT, Y : naT], equiv(pp(ord_less_eq_nat2(X, Y)), or(pp(ord_less_nat2(X, Y)), equal(X, Y)))), fact_158_order__le__less, 2884). % order_le_less
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(B, C)), pp(ord_less_nat2(B, plus_plus_nat2(A, C)))))), fact_159_pos__add__strict, 2896). % pos_add_strict
formula(forall([G2 : fun_nat_nat, N2 : naT, M2 : naT], equal(groups1842438620at_nat(G2, set_or601162459st_nat(N2, M2)), groups1842438620at_nat(cOMBB_nat_nat_nat(G2, minus_minus_nat1(plus_plus_nat2(M2, N2))), set_or601162459st_nat(N2, M2)))), fact_160_sum_OatLeastAtMost__rev, 2909). % sum.atLeastAtMost_rev
formula(forall([M2 : naT, N2 : naT, G2 : fun_nat_nat], implies(pp(ord_less_eq_nat2(M2, N2)), equal(plus_plus_nat2(groups1842438620at_nat(G2, set_or601162459st_nat(M2, N2)), aa_nat_nat(G2, suc1(N2))), plus_plus_nat2(aa_nat_nat(G2, M2), groups1842438620at_nat(cOMBB_nat_nat_nat(G2, suC), set_or601162459st_nat(M2, N2)))))), fact_161_sum_OSuc__reindex__ivl, 2921). % sum.Suc_reindex_ivl
formula(forall([P : booL, Q : booL], implies(ord_less_eq_bool(P, Q), implies(pp(P), pp(Q)))), fact_162_le__boolD, 2934). % le_boolD
formula(forall([Y : booL, X : booL], implies(ord_less_eq_bool(Y, X), equiv(ord_less_eq_bool(X, Y), equiv(pp(X), pp(Y))))), fact_163_order__antisym__conv, 2946). % order_antisym_conv
formula(forall([Y : naT, X : naT], implies(pp(ord_less_eq_nat2(Y, X)), equiv(pp(ord_less_eq_nat2(X, Y)), equal(X, Y)))), fact_164_order__antisym__conv, 2959). % order_antisym_conv
formula(forall([X : booL, Y : booL], equiv(ord_less_bool(X, Y), and(ord_less_eq_bool(X, Y), not(ord_less_eq_bool(Y, X))))), fact_165_less__le__not__le, 2972). % less_le_not_le
formula(forall([X : naT, Y : naT], equiv(pp(ord_less_nat2(X, Y)), and(pp(ord_less_eq_nat2(X, Y)), not(pp(ord_less_eq_nat2(Y, X)))))), fact_166_less__le__not__le, 2984). % less_le_not_le
formula(forall([A : naT], equal(minus_minus_nat2(A, zero_zero_nat), A)), fact_167_diff__zero, 2997). % diff_zero
formula(forall([X : booL, Y : booL], implies(ord_less_bool(X, Y), ord_less_eq_bool(X, Y))), fact_168_order__less__imp__le, 3009). % order_less_imp_le
formula(forall([X : naT, Y : naT], implies(pp(ord_less_nat2(X, Y)), pp(ord_less_eq_nat2(X, Y)))), fact_169_order__less__imp__le, 3022). % order_less_imp_le
formula(forall([G : fun_nat_nat, N : naT], equal(groups1842438620at_nat(G, set_or601162459st_nat(zero_zero_nat, suc1(N))), plus_plus_nat2(groups1842438620at_nat(G, set_or601162459st_nat(zero_zero_nat, N)), aa_nat_nat(G, suc1(N))))), fact_170_sum_OatLeast0__atMost__Suc, 3034). % sum.atLeast0_atMost_Suc
formula(forall([A : naT], equal(times_times_nat2(zero_zero_nat, A), zero_zero_nat)), fact_171_mult__zero__left, 3047). % mult_zero_left
formula(forall([M : naT, N : naT, P2 : naT, G : fun_nat_nat], implies(pp(ord_less_eq_nat2(M, N)), implies(pp(ord_less_eq_nat2(N, P2)), equal(plus_plus_nat2(groups1842438620at_nat(G, set_or562006527an_nat(M, N)), groups1842438620at_nat(G, set_or562006527an_nat(N, P2))), groups1842438620at_nat(G, set_or562006527an_nat(M, P2)))))), fact_172_sum_OatLeastLessThan__concat, 3060). % sum.atLeastLessThan_concat
formula(forall([N : naT], equal(suc1(N), plus_plus_nat2(N, one_one_nat))), fact_173_Suc__eq__plus1, 3072). % Suc_eq_plus1
formula(forall([G : fun_nat_nat, N : naT], equal(groups1842438620at_nat(G, set_or601162459st_nat(zero_zero_nat, suc1(N))), plus_plus_nat2(aa_nat_nat(G, zero_zero_nat), groups1842438620at_nat(comp_nat_nat_nat(G, suC), set_or601162459st_nat(zero_zero_nat, N))))), fact_174_sum_OatLeast0__atMost__Suc__shift, 3085). % sum.atLeast0_atMost_Suc_shift
formula(forall([A : naT, B : naT, C : naT], equal(times_times_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(times_times_nat2(A, C), times_times_nat2(B, C)))), fact_175_distrib__right, 3097). % distrib_right
formula(forall([X : booL, Y : booL, Z : booL], implies(ord_less_eq_bool(X, Y), implies(ord_less_bool(Y, Z), ord_less_bool(X, Z)))), fact_176_order__le__less__trans, 3110). % order_le_less_trans
formula(forall([X : naT, Y : naT, Z : naT], implies(pp(ord_less_eq_nat2(X, Y)), implies(pp(ord_less_nat2(Y, Z)), pp(ord_less_nat2(X, Z))))), fact_177_order__le__less__trans, 3122). % order_le_less_trans
formula(forall([A : naT], equal(times_times_nat2(A, zero_zero_nat), zero_zero_nat)), fact_178_mult__zero__right, 3135). % mult_zero_right
formula(forall([G : fun_nat_nat, N : naT], equal(groups1842438620at_nat(G, set_or562006527an_nat(zero_zero_nat, suc1(N))), plus_plus_nat2(groups1842438620at_nat(G, set_or562006527an_nat(zero_zero_nat, N)), aa_nat_nat(G, N)))), fact_179_sum_OatLeast0__lessThan__Suc, 3147). % sum.atLeast0_lessThan_Suc
formula(forall([X : booL, Y : booL, Z : booL], implies(ord_less_bool(X, Y), implies(ord_less_eq_bool(Y, Z), ord_less_bool(X, Z)))), fact_180_order__less__le__trans, 3160). % order_less_le_trans
formula(forall([X : naT, Y : naT, Z : naT], implies(pp(ord_less_nat2(X, Y)), implies(pp(ord_less_eq_nat2(Y, Z)), pp(ord_less_nat2(X, Z))))), fact_181_order__less__le__trans, 3173). % order_less_le_trans
formula(forall([A : booL, B : booL, C : booL], implies(ord_less_bool(A, B), implies(equiv(pp(B), pp(C)), ord_less_bool(A, C)))), fact_182_ord__less__eq__trans, 3185). % ord_less_eq_trans
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(A, B)), implies(equal(B, C), pp(ord_less_nat2(A, C))))), fact_183_ord__less__eq__trans, 3198). % ord_less_eq_trans
formula(equal(plus_plus_nat2(one_one_nat, one_one_nat), numeral_numeral_nat(bit0(onE))), fact_184_one__add__one, 3210). % one_add_one
formula(forall([X : booL, Y : booL], implies(not(ord_less_bool(X, Y)), ord_less_eq_bool(Y, X))), fact_185_leI, 3223). % leI
formula(forall([X : naT, Y : naT], implies(not(pp(ord_less_nat2(X, Y))), pp(ord_less_eq_nat2(Y, X)))), fact_186_leI, 3235). % leI
formula(forall([A : naT], equiv(pp(ord_less_eq_nat2(A, zero_zero_nat)), equal(A, zero_zero_nat))), fact_187_bot__nat__0_Oextremum__unique, 3248). % bot_nat_0.extremum_unique
formula(semigroup_nat(plus_plus_nat), fact_188_add_Osemigroup__axioms, 3260). % add.semigroup_axioms
formula(forall([G : fun_nat_nat, N : naT], equal(groups1842438620at_nat(G, set_or562006527an_nat(zero_zero_nat, suc1(N))), plus_plus_nat2(aa_nat_nat(G, zero_zero_nat), groups1842438620at_nat(comp_nat_nat_nat(G, suC), set_or562006527an_nat(zero_zero_nat, N))))), fact_189_sum_OatLeast0__lessThan__Suc__shift, 3273). % sum.atLeast0_lessThan_Suc_shift
formula(forall([X : booL, Y : booL, Z : booL], implies(ord_less_bool(X, Y), implies(ord_less_bool(Y, Z), ord_less_bool(X, Z)))), fact_190_order__less__trans, 3286). % order_less_trans
formula(forall([X : naT, Y : naT, Z : naT], implies(pp(ord_less_nat2(X, Y)), implies(pp(ord_less_nat2(Y, Z)), pp(ord_less_nat2(X, Z))))), fact_191_order__less__trans, 3298). % order_less_trans
formula(forall([G2 : fun_nat_nat, N2 : naT, M2 : naT], equal(groups1842438620at_nat(G2, set_or562006527an_nat(N2, M2)), groups1842438620at_nat(cOMBB_nat_nat_nat(G2, cOMBB_nat_nat_nat(minus_minus_nat1(plus_plus_nat2(M2, N2)), suC)), set_or562006527an_nat(N2, M2)))), fact_192_sum_OatLeastLessThan__rev, 3311). % sum.atLeastLessThan_rev
formula(forall([X : booL], ord_less_eq_bool(X, X)), fact_193_order__refl, 3323). % order_refl
formula(forall([X : naT], pp(ord_less_eq_nat2(X, X))), fact_194_order__refl, 3336). % order_refl
formula(forall([M : naT, N : naT, G : fun_nat_nat], implies(pp(ord_less_eq_nat2(M, N)), equal(groups1842438620at_nat(G, set_or601162459st_nat(M, N)), groups1842438620at_nat(comp_nat_nat_nat(G, plus_plus_nat1(M)), set_or601162459st_nat(zero_zero_nat, minus_minus_nat2(N, M)))))), fact_195_sum_OatLeastAtMost__shift__0, 3348). % sum.atLeastAtMost_shift_0
formula(abel_semigroup_nat(plus_plus_nat), fact_196_add_Oabel__semigroup__axioms, 3361). % add.abel_semigroup_axioms
formula(forall([A : naT, B : naT, C : naT], equal(times_times_nat2(times_times_nat2(A, B), C), times_times_nat2(A, times_times_nat2(B, C)))), fact_197_mult_Oassoc, 3373). % mult.assoc
formula(forall([G : fun_nat_nat, M : naT, K : naT, N : naT], equal(groups1842438620at_nat(G, set_or601162459st_nat(plus_plus_nat2(M, K), plus_plus_nat2(N, K))), groups1842438620at_nat(comp_nat_nat_nat(G, plus_plus_nat1(K)), set_or601162459st_nat(M, N)))), fact_198_sum_OatLeastAtMost__shift__bounds, 3386). % sum.atLeastAtMost_shift_bounds
formula(forall([F : fun_nat_fun_nat_nat, Z : naT], equiv(pp(comm_monoid_nat2(F, Z)), and(abel_semigroup_nat(F), pp(comm_m1939377251s_nat2(F, Z))))), fact_199_comm__monoid__def, 3399). % comm_monoid_def
formula(equal(zero_n1356753679ol_nat(fTruE), one_one_nat), fact_200_of__bool__eq_I2_J, 3411). % of_bool_eq(2)
formula(forall([X : booL, Y : booL], implies(not(ord_less_eq_bool(X, Y)), ord_less_eq_bool(Y, X))), fact_201_linorder__le__cases, 3424). % linorder_le_cases
formula(forall([X : naT, Y : naT], implies(not(pp(ord_less_eq_nat2(X, Y))), pp(ord_less_eq_nat2(Y, X)))), fact_202_linorder__le__cases, 3436). % linorder_le_cases
formula(forall([G : fun_nat_nat, N : naT], equal(groups1842438620at_nat(G, set_ord_atMost_nat(suc1(N))), plus_plus_nat2(groups1842438620at_nat(G, set_ord_atMost_nat(N)), aa_nat_nat(G, suc1(N))))), fact_203_sum_OatMost__Suc, 3449). % sum.atMost_Suc
formula(forall([X : booL, Y : booL], or(ord_less_bool(X, Y), or(equiv(pp(X), pp(Y)), ord_less_bool(Y, X)))), fact_204_linorder__less__linear, 3461). % linorder_less_linear
formula(forall([X : naT, Y : naT], or(pp(ord_less_nat2(X, Y)), or(equal(X, Y), pp(ord_less_nat2(Y, X))))), fact_205_linorder__less__linear, 3474). % linorder_less_linear
formula(forall([A : naT, C : naT, B : naT], equal(minus_minus_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C)), minus_minus_nat2(A, B))), fact_206_add__diff__cancel__right, 3486). % add_diff_cancel_right
formula(forall([A : naT, B : naT, G : fun_nat_nat], implies(pp(ord_less_eq_nat2(A, B)), equal(groups1842438620at_nat(G, set_or562006527an_nat(A, suc1(B))), plus_plus_nat2(groups1842438620at_nat(G, set_or562006527an_nat(A, B)), aa_nat_nat(G, B))))), fact_207_sum_OatLeastLessThan__Suc, 3499). % sum.atLeastLessThan_Suc
formula(forall([A : booL, B : booL], equiv(equiv(pp(A), pp(B)), and(ord_less_eq_bool(A, B), ord_less_eq_bool(B, A)))), fact_208_Orderings_Oorder__eq__iff, 3512). % Orderings.order_eq_iff
formula(forall([A : naT, B : naT], equiv(equal(A, B), and(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(B, A))))), fact_209_Orderings_Oorder__eq__iff, 3524). % Orderings.order_eq_iff
formula(forall([X : booL, Y : booL], implies(ord_less_bool(X, Y), not(equiv(pp(X), pp(Y))))), fact_210_less__imp__neq, 3537). % less_imp_neq
formula(forall([X : naT, Y : naT], implies(pp(ord_less_nat2(X, Y)), not(equal(X, Y)))), fact_211_less__imp__neq, 3549). % less_imp_neq
formula(forall([X : booL, Y : booL], implies(equiv(pp(X), not(pp(Y))), implies(not(ord_less_bool(X, Y)), ord_less_bool(Y, X)))), fact_212_linorder__neqE, 3562). % linorder_neqE
formula(forall([X : naT, Y : naT], implies(not(equal(X, Y)), implies(not(pp(ord_less_nat2(X, Y))), pp(ord_less_nat2(Y, X))))), fact_213_linorder__neqE, 3574). % linorder_neqE
formula(forall([P : fun_nat_bool, A : naT], implies(forall([X3 : naT], implies(forall([Y2 : naT], implies(pp(ord_less_nat2(Y2, X3)), pp(aa_nat_bool(P, Y2)))), pp(aa_nat_bool(P, X3)))), pp(aa_nat_bool(P, A)))), fact_214_less__induct, 3587). % less_induct

formula(not(pp(fFalsE)), help_pp_1_1_U).
formula(forall([P : booL], or(equal(P, fTruE), equal(P, fFalsE))), help_fTrue_1_1_T).
formula(pp(fTruE), help_fTrue_1_1_U).
formula(forall([P : fun_nat_nat, Q : fun_nat_nat, R : naT], equal:lt(aa_nat_nat(cOMBB_nat_nat_nat(P, Q), R), aa_nat_nat(P, aa_nat_nat(Q, R)))), help_COMBB_1_1_COMBB_001t__Nat__Onat_001t__Nat__Onat_001t__Nat__Onat_U).
end_of_list.

list_of_formulae(conjectures).
formula(equal(plus_plus_a(x, y), plus_plus_a(y, x)), conj_0).
end_of_list.

list_of_settings(SPASS).
set_precedence(minus_minus_nat, ord_less_nat, minus_minus_nat1, ord_less_eq_nat, plus_plus_nat, ord_less_eq_nat2, minus_minus_nat2, ord_less_nat2, groups1842438620at_nat, plus_plus_nat1, times_times_nat, plus_plus_nat2, times_times_nat1, comp_nat_nat_nat, suC, comp_nat_nat_nat3, cOMBB_nat_nat_nat, monoid_nat, zero_n1356753679ol_nat, numeral_numeral_nat, times_times_nat2, comm_monoid_nat, monoid_axioms_nat, comm_m2051353214ms_nat, groups1056228905et_nat, groups1479517816t_nat2, comm_m1939377251s_nat2, set_ord_atMost_nat, monoid_axioms_nat2, comm_monoid_nat2, zero_zero_nat, plus_plus_num, one_one_nat, monoid_nat2, aa_nat_nat, fTruE, suc1, bit0, onE).
end_of_list.

end_problem.
