% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 2.500 -nc --tptp-def-as-rewrite --mode=ho-pragmatic --max-inferences=4 --ho-max-app-projections=1 --ho-max-elims=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --ho-unif-max-depth=2 --boolean-reasoning=simpl-only --ext-rules=off --kbo-weight-fun=lambda-def-const --ho-prim-enum=neg --ho-prim-enum-early-bird=true --tptp-def-as-rewrite --rewrite-before-cnf=true --ho-unif-level=pragmatic-framework --ho-unif-max-depth=1 --sine=50 --sine-tolerance=1.0 --sine-depth-max=3 --sine-depth-min=1 --sine-trim-implications=true -q "4|prefer-sos|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-var(1,s,f)" -q "3|const|default" -q "1|prefer-processed|fifo" --ho-elim-leibniz=1 --ho-fixpoint-decider=true --ho-pattern-decider=true --ho-solid-decider=false --select=e-selection10 --solve-formulas=true --sup-at-vars=false --sup-at-var-headed=false --sup-from-var-headed=true --lazy-cnf=true --lazy-cnf-kind=simp --lazy-cnf-renaming-threshold=4 --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --e-timeout=2 --e-auto=true --e-max-derived=32 --e-encode-lambdas=lift --scan-clause-ac=false --presaturate=true --e-call-point=0.16 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5127406_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:43:13.677
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a)))), [], [isabelle_rank(900)]). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
