% /Applications/Isabelle2025.app/contrib/vampire-4.8/x86_64-darwin/vampire --input_syntax tptp --proof tptp --output_axiom_names on --mode portfolio --schedule snake_slh -t 3 --input_file /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4850792_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:32.695
% Could-be-implicit typings (2)
tff(ty_n_t__HOL__Obool, type,
    bool : $tType).
tff(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (6)
tff(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : (a * a) > a).
tff(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
tff(sy_c_fFalse, type,
    fFalse : bool).
tff(sy_c_fTrue, type,
    fTrue : bool).
tff(sy_c_pp, type,
    pp : bool > $o).
tff(sy_v_x, type,
    x : a).

% Relevant facts (1)
tff(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) <=> (X = zero_zero_a))))). % zero_reorient

% Helper facts (2)
tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).
tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).

% Conjectures (1)
tff(conj_0, conjecture,
    ((plus_plus_a(x, zero_zero_a) = x))).
