% /Applications/Isabelle2025.app/contrib/e-3.1-1/arm64-darwin/eprover --tstp-in --tstp-out --silent --auto-schedule --cpu-limit=5 --proof-object=1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5352504_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:44:14.223
% Could-be-implicit typings (3)
thf(ty_n_t__Num__Onum, type,
    num : $tType).
thf(ty_n_t__Nat__Onat, type,
    nat : $tType).
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (21)
thf(sy_c_Groups_Oabel__semigroup_001t__Nat__Onat, type,
    abel_semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Ocomm__monoid_001t__Nat__Onat, type,
    comm_monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ocomm__monoid__axioms_001t__Nat__Onat, type,
    comm_m2051353214ms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ominus__class_Ominus_001t__Nat__Onat, type,
    minus_minus_nat : nat > nat > nat).
thf(sy_c_Groups_Omonoid_001t__Nat__Onat, type,
    monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__Nat__Onat, type,
    monoid_axioms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat, type,
    one_one_nat : nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Nat__Onat, type,
    plus_plus_nat : nat > nat > nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Num__Onum, type,
    plus_plus_num : num > num > num).
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Osemigroup_001t__Nat__Onat, type,
    semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Otimes__class_Otimes_001t__Nat__Onat, type,
    times_times_nat : nat > nat > nat).
thf(sy_c_Groups_Ozero__class_Ozero_001t__Nat__Onat, type,
    zero_zero_nat : nat).
thf(sy_c_Groups__Big_Ocomm__monoid__set_001t__Nat__Onat, type,
    groups1056228905et_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Nat_OSuc, type,
    suc : nat > nat).
thf(sy_c_Num_Onumeral__class_Onumeral_001t__Nat__Onat, type,
    numeral_numeral_nat : num > nat).
thf(sy_c_Orderings_Obot__class_Obot_001_Eo, type,
    bot_bot_o : $o).
thf(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat, type,
    ord_less_nat : nat > nat > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat, type,
    ord_less_eq_nat : nat > nat > $o).
thf(sy_v_x, type,
    x : a).
thf(sy_v_y, type,
    y : a).

% Relevant facts (76)
thf(fact_0_add__left__cancel, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) = (B = C))))). % add_left_cancel
thf(fact_1_add__right__cancel, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) = (B = C))))). % add_right_cancel
thf(fact_2_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % ab_semigroup_add_class.add_ac(1)
thf(fact_3_add__numeral__left, axiom,
    ((![V : num, W : num, Z : nat]: ((plus_plus_nat @ (numeral_numeral_nat @ V) @ (plus_plus_nat @ (numeral_numeral_nat @ W) @ Z)) = (plus_plus_nat @ (numeral_numeral_nat @ (plus_plus_num @ V @ W)) @ Z))))). % add_numeral_left
thf(fact_4_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (K = L)) => ((plus_plus_nat @ I @ K) = (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(4)
thf(fact_5_group__cancel_Oadd1, axiom,
    ((![A2 : nat, K : nat, A : nat, B : nat]: ((A2 = (plus_plus_nat @ K @ A)) => ((plus_plus_nat @ A2 @ B) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add1
thf(fact_6_group__cancel_Oadd2, axiom,
    ((![B2 : nat, K : nat, B : nat, A : nat]: ((B2 = (plus_plus_nat @ K @ B)) => ((plus_plus_nat @ A @ B2) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add2
thf(fact_7_add_Oright__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.right_neutral
thf(fact_8_add_Ocommute, axiom,
    ((plus_plus_nat = (^[A3 : nat]: (^[B3 : nat]: (plus_plus_nat @ B3 @ A3)))))). % add.commute
thf(fact_9_add__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % add_0
thf(fact_10_add_Oassoc, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.assoc
thf(fact_11_monoid_Oright__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_12_add_Oleft__commute, axiom,
    ((![B : nat, A : nat, C : nat]: ((plus_plus_nat @ B @ (plus_plus_nat @ A @ C)) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.left_commute
thf(fact_13_add__left__imp__eq, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) => (B = C))))). % add_left_imp_eq
thf(fact_14_add__right__imp__eq, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) => (B = C))))). % add_right_imp_eq
thf(fact_15_monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((semigroup_nat @ F) => ((monoid_axioms_nat @ F @ Z) => (monoid_nat @ F @ Z)))))). % monoid.intro
thf(fact_16_comm__monoid__add__class_Oadd__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % comm_monoid_add_class.add_0
thf(fact_17_dual__order_Orefl, axiom,
    ((![A : nat]: (ord_less_eq_nat @ A @ A)))). % dual_order.refl
thf(fact_18_add__cancel__right__right, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ A @ B)) = (B = zero_zero_nat))))). % add_cancel_right_right
thf(fact_19_add__cancel__left__right, axiom,
    ((![A : nat, B : nat]: (((plus_plus_nat @ A @ B) = A) = (B = zero_zero_nat))))). % add_cancel_left_right
thf(fact_20_add__cancel__right__left, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ B @ A)) = (B = zero_zero_nat))))). % add_cancel_right_left
thf(fact_21_add__eq__0__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: (((plus_plus_nat @ X @ Y) = zero_zero_nat) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % add_eq_0_iff_both_eq_0
thf(fact_22_zero__eq__add__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: ((zero_zero_nat = (plus_plus_nat @ X @ Y)) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % zero_eq_add_iff_both_eq_0
thf(fact_23_add__cancel__left__left, axiom,
    ((![B : nat, A : nat]: (((plus_plus_nat @ B @ A) = A) = (B = zero_zero_nat))))). % add_cancel_left_left
thf(fact_24_comm__monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((abel_semigroup_nat @ F) => ((comm_m2051353214ms_nat @ F @ Z) => (comm_monoid_nat @ F @ Z)))))). % comm_monoid.intro
thf(fact_25_monoid_Oleft__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ Z @ A) = A))))). % monoid.left_neutral
thf(fact_26_numeral__plus__numeral, axiom,
    ((![M : num, N : num]: ((plus_plus_nat @ (numeral_numeral_nat @ M) @ (numeral_numeral_nat @ N)) = (numeral_numeral_nat @ (plus_plus_num @ M @ N)))))). % numeral_plus_numeral
thf(fact_27_add_Ocomm__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.comm_neutral
thf(fact_28_add__le__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_left
thf(fact_29_verit__sum__simplify, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % verit_sum_simplify
thf(fact_30_comm__monoid__set_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((comm_monoid_nat @ F @ Z) => (groups1056228905et_nat @ F @ Z))))). % comm_monoid_set.intro
thf(fact_31_add__Suc__right, axiom,
    ((![M : nat, N : nat]: ((plus_plus_nat @ M @ (suc @ N)) = (suc @ (plus_plus_nat @ M @ N)))))). % add_Suc_right
thf(fact_32_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(1)
thf(fact_33_zero__reorient, axiom,
    ((![X : nat]: ((zero_zero_nat = X) = (X = zero_zero_nat))))). % zero_reorient
thf(fact_34_add_Ocomm__monoid__axioms, axiom,
    ((comm_monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.comm_monoid_axioms
thf(fact_35_add_Omonoid__axioms, axiom,
    ((monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.monoid_axioms
thf(fact_36_add__0__iff, axiom,
    ((![B : nat, A : nat]: ((B = (plus_plus_nat @ B @ A)) = (A = zero_zero_nat))))). % add_0_iff
thf(fact_37_order__less__irrefl, axiom,
    ((![X : nat]: (~ ((ord_less_nat @ X @ X)))))). % order_less_irrefl
thf(fact_38_comm__monoid_Ocomm__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((comm_monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % comm_monoid.comm_neutral
thf(fact_39_One__nat__def, axiom,
    ((one_one_nat = (suc @ zero_zero_nat)))). % One_nat_def
thf(fact_40_nat__arith_Orule0, axiom,
    ((![A : nat]: (A = (plus_plus_nat @ A @ zero_zero_nat))))). % nat_arith.rule0
thf(fact_41_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (K = L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(3)
thf(fact_42_ord__eq__le__trans, axiom,
    ((![A : nat, B : nat, C : nat]: ((A = B) => ((ord_less_eq_nat @ B @ C) => (ord_less_eq_nat @ A @ C)))))). % ord_eq_le_trans
thf(fact_43_order__antisym, axiom,
    ((![X : nat, Y : nat]: ((ord_less_eq_nat @ X @ Y) => ((ord_less_eq_nat @ Y @ X) => (X = Y)))))). % order_antisym
thf(fact_44_le__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel1
thf(fact_45_le__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel2
thf(fact_46_order__trans, axiom,
    ((![X : nat, Y : nat, Z : nat]: ((ord_less_eq_nat @ X @ Y) => ((ord_less_eq_nat @ Y @ Z) => (ord_less_eq_nat @ X @ Z)))))). % order_trans
thf(fact_47_add__mono__thms__linordered__field_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(3)
thf(fact_48_le__zero__eq, axiom,
    ((![N : nat]: ((ord_less_eq_nat @ N @ zero_zero_nat) = (N = zero_zero_nat))))). % le_zero_eq
thf(fact_49_add__le__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel1
thf(fact_50_add__le__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel2
thf(fact_51_add__mono__thms__linordered__field_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(4)
thf(fact_52_add__less__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_nat @ A @ B))))). % add_less_cancel_right
thf(fact_53_zero__le, axiom,
    ((![X : nat]: (ord_less_eq_nat @ zero_zero_nat @ X)))). % zero_le
thf(fact_54_add__mono__thms__linordered__field_I1_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (K = L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(1)
thf(fact_55_not__gr__zero, axiom,
    ((![N : nat]: ((~ ((ord_less_nat @ zero_zero_nat @ N))) = (N = zero_zero_nat))))). % not_gr_zero
thf(fact_56_add__le__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_right
thf(fact_57_add__less__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_nat @ A @ B))))). % add_less_cancel_left
thf(fact_58_add__mono__thms__linordered__field_I5_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(5)
thf(fact_59_add__mono__thms__linordered__semiring_I2_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (ord_less_eq_nat @ K @ L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(2)
thf(fact_60_add__mono__thms__linordered__field_I2_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(2)
thf(fact_61_linorder__not__less, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_nat @ X @ Y))) = (ord_less_eq_nat @ Y @ X))))). % linorder_not_less
thf(fact_62_nat_Osimps_I3_J, axiom,
    ((![X2 : nat]: ((suc @ X2) != zero_zero_nat)))). % nat.simps(3)
thf(fact_63_add__less__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel1
thf(fact_64_add__less__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel2
thf(fact_65_less__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel1
thf(fact_66_add__diff__cancel__left_H, axiom,
    ((![A : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ A @ B) @ A) = B)))). % add_diff_cancel_left'
thf(fact_67_mult__1, axiom,
    ((![A : nat]: ((times_times_nat @ one_one_nat @ A) = A)))). % mult_1
thf(fact_68_not__less__zero, axiom,
    ((![N : nat]: (~ ((ord_less_nat @ N @ zero_zero_nat)))))). % not_less_zero
thf(fact_69_order__less__le, axiom,
    ((ord_less_nat = (^[X3 : nat]: (^[Y2 : nat]: (((ord_less_eq_nat @ X3 @ Y2)) & ((~ ((X3 = Y2)))))))))). % order_less_le
thf(fact_70_bot__bool__def, axiom,
    ((~ (bot_bot_o)))). % bot_bool_def
thf(fact_71_less__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel2
thf(fact_72_antisym, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_eq_nat @ B @ A) => (A = B)))))). % antisym
thf(fact_73_mult_Oright__neutral, axiom,
    ((![A : nat]: ((times_times_nat @ A @ one_one_nat) = A)))). % mult.right_neutral
thf(fact_74_le__iff__add, axiom,
    ((ord_less_eq_nat = (^[A3 : nat]: (^[B3 : nat]: (?[C2 : nat]: (B3 = (plus_plus_nat @ A3 @ C2)))))))). % le_iff_add
thf(fact_75_order__eq__refl, axiom,
    ((![X : nat, Y : nat]: ((X = Y) => (ord_less_eq_nat @ X @ Y))))). % order_eq_refl

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ y) = (plus_plus_a @ y @ x)))).
