% /Applications/Isabelle2025.app/contrib/spass-3.8ds-2/x86_64-darwin/SPASS -Isabelle=1 -TimeLimit=5 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4884488_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:42:54.153
begin_problem(isabelle).

list_of_descriptions.
name({**}).
author({**}).
status(unknown).
description({**}).
end_of_list.

list_of_symbols.
functions [(comm_m604335976nteger, 1), (comm_m138292217teger2, 2), (comm_monoid_int, 1), (comm_monoid_int2, 2), (comm_monoid_nat, 1), (comm_monoid_nat2, 2), (minus_1582103350nteger, 2), (minus_minus_int, 2), (minus_minus_nat, 2), (monoid_Code_integer, 1), (monoid_Code_integer2, 2), (monoid_int, 1), (monoid_int2, 2), (monoid_nat, 1), (monoid_nat2, 2), (one_one_nat, 0), (plus_p2058578406nteger, 0), (plus_p715165434teger1, 1), (plus_p715165435teger2, 2), (plus_plus_int, 0), (plus_plus_int1, 1), (plus_plus_int2, 2), (plus_plus_nat, 0), (plus_plus_nat1, 1), (plus_plus_nat2, 2), (plus_plus_literal, 0), (plus_plus_literal1, 1), (plus_plus_literal2, 2), (plus_plus_a, 2), (times_1419655522nteger, 2), (times_times_int, 2), (times_times_nat, 2), (uminus636303014ntegeR, 1), (uminus_uminus_int, 1), (zero_z413810534nteger, 0), (zero_zero_int, 0), (zero_zero_nat, 0), (zero_zero_literal, 0), (zero_zero_a, 0), (poS, 0), (suB, 2), (suC, 1), (numeral_numeral_int, 0), (numeral_numeral_int1, 1), (ord_le945590961nteger, 1), (ord_le1687847920teger2, 2), (ord_less_int, 1), (ord_less_int2, 2), (ord_less_nat, 1), (ord_less_nat2, 2), (ord_le1426714813nteger, 1), (ord_le1442264292teger2, 2), (ord_less_eq_int, 1), (ord_less_eq_int2, 2), (ord_less_eq_nat, 1), (ord_less_eq_nat2, 2), (dvd_dvd_Code_integer, 1), (dvd_dv413397790teger2, 2), (dvd_dvd_int, 1), (dvd_dvd_int2, 2), (dvd_dvd_nat, 1), (dvd_dvd_nat2, 2), (image_1151633089nteger, 2), (image_int_int, 2), (image_nat_nat, 2), (aa_Cod479057144nteger, 2), (aa_Code_integer_bool, 2), (aa_Cod1485984722nteger, 2), (aa_int_bool, 2), (aa_int_int, 2), (aa_int_fun_int_int, 2), (aa_nat_bool, 2), (aa_nat_nat, 2), (aa_nat_fun_nat_nat, 2), (aa_num_int, 2), (aa_literal_literal, 2), (aa_lit1494493019iteral, 2), (fFalsE, 0), (fTruE, 0), (x, 0)].
predicates [(monoid_literal, 2), (pp, 1)].
weights [(monoid_int2, 1), (monoid_nat2, 1), (one_one_nat, 1), (dvd_dvd_int2, 1), (dvd_dvd_nat2, 1), (zero_zero_int, 1), (zero_zero_nat, 1), (comm_monoid_int2, 1), (comm_monoid_nat2, 1), (uminus_uminus_int, 1), (zero_zero_literal, 1), (monoid_Code_integer2, 1), (numeral_numeral_int1, 1), (comm_m138292217teger2, 1), (dvd_dv413397790teger2, 1), (uminus636303014ntegeR, 1), (zero_z413810534nteger, 1), (minus_1582103350nteger, 2), (times_1419655522nteger, 2), (dvd_dvd_Code_integer, 2), (comm_m604335976nteger, 2), (numeral_numeral_int, 2), (monoid_Code_integer, 2), (plus_plus_literal2, 2), (comm_monoid_nat, 2), (comm_monoid_int, 2), (plus_plus_nat2, 2), (times_times_nat, 2), (minus_minus_int, 2), (times_times_int, 2), (dvd_dvd_nat, 2), (dvd_dvd_int, 2), (monoid_nat, 2), (monoid_int, 2), (plus_plus_nat1, 4), (plus_plus_literal1, 4), (plus_p715165435teger2, 4), (suB, 4), (plus_plus_int2, 4), (ord_less_nat2, 4), (minus_minus_nat, 4), (ord_less_eq_nat2, 4), (plus_plus_literal, 8), (plus_plus_nat, 8), (ord_less_eq_nat, 8), (ord_less_nat, 8), (plus_plus_int1, 8), (plus_p715165434teger1, 8), (ord_le1442264292teger2, 8), (ord_le1687847920teger2, 8), (image_nat_nat, 8), (ord_less_int2, 8), (ord_less_eq_int2, 8), (plus_p2058578406nteger, 16), (plus_plus_int, 16), (ord_less_eq_int, 16), (ord_less_int, 16), (ord_le945590961nteger, 16), (ord_le1426714813nteger, 16), (image_1151633089nteger, 16), (image_int_int, 16)].
sorts [fun_Co708814609nteger, fun_li1962565290iteral, fun_Co1957674295nteger, fun_nat_fun_nat_nat, fun_int_fun_int_int, fun_Co535713875r_bool, fun_literal_literal, set_Code_integer, fun_nat_bool, fun_int_bool, fun_num_int, fun_nat_nat, fun_int_int, set_nat, set_int, code_integer, literaL, booL, nuM, naT, inT, a, iii].
% classes [].
end_of_list.

list_of_declarations.
function(comm_m604335976nteger, (fun_Co708814609nteger) fun_Co535713875r_bool).
function(comm_m138292217teger2, (fun_Co708814609nteger, code_integer) booL).
function(comm_monoid_int, (fun_int_fun_int_int) fun_int_bool).
function(comm_monoid_int2, (fun_int_fun_int_int, inT) booL).
function(comm_monoid_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(comm_monoid_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(minus_1582103350nteger, (code_integer, code_integer) code_integer).
function(minus_minus_int, (inT, inT) inT).
function(minus_minus_nat, (naT, naT) naT).
function(monoid_Code_integer, (fun_Co708814609nteger) fun_Co535713875r_bool).
function(monoid_Code_integer2, (fun_Co708814609nteger, code_integer) booL).
function(monoid_int, (fun_int_fun_int_int) fun_int_bool).
function(monoid_int2, (fun_int_fun_int_int, inT) booL).
function(monoid_nat, (fun_nat_fun_nat_nat) fun_nat_bool).
function(monoid_nat2, (fun_nat_fun_nat_nat, naT) booL).
function(one_one_nat, naT).
function(plus_p2058578406nteger, fun_Co708814609nteger).
function(plus_p715165434teger1, (code_integer) fun_Co1957674295nteger).
function(plus_p715165435teger2, (code_integer, code_integer) code_integer).
function(plus_plus_int, fun_int_fun_int_int).
function(plus_plus_int1, (inT) fun_int_int).
function(plus_plus_int2, (inT, inT) inT).
function(plus_plus_nat, fun_nat_fun_nat_nat).
function(plus_plus_nat1, (naT) fun_nat_nat).
function(plus_plus_nat2, (naT, naT) naT).
function(plus_plus_literal, fun_li1962565290iteral).
function(plus_plus_literal1, (literaL) fun_literal_literal).
function(plus_plus_literal2, (literaL, literaL) literaL).
function(plus_plus_a, (a, a) a).
function(times_1419655522nteger, (code_integer, code_integer) code_integer).
function(times_times_int, (inT, inT) inT).
function(times_times_nat, (naT, naT) naT).
function(uminus636303014ntegeR, (code_integer) code_integer).
function(uminus_uminus_int, (inT) inT).
function(zero_z413810534nteger, code_integer).
function(zero_zero_int, inT).
function(zero_zero_nat, naT).
function(zero_zero_literal, literaL).
function(zero_zero_a, a).
function(poS, fun_num_int).
function(suB, (nuM, nuM) inT).
function(suC, (naT) naT).
function(numeral_numeral_int, fun_num_int).
function(numeral_numeral_int1, (nuM) inT).
function(ord_le945590961nteger, (code_integer) fun_Co535713875r_bool).
function(ord_le1687847920teger2, (code_integer, code_integer) booL).
function(ord_less_int, (inT) fun_int_bool).
function(ord_less_int2, (inT, inT) booL).
function(ord_less_nat, (naT) fun_nat_bool).
function(ord_less_nat2, (naT, naT) booL).
function(ord_le1426714813nteger, (code_integer) fun_Co535713875r_bool).
function(ord_le1442264292teger2, (code_integer, code_integer) booL).
function(ord_less_eq_int, (inT) fun_int_bool).
function(ord_less_eq_int2, (inT, inT) booL).
function(ord_less_eq_nat, (naT) fun_nat_bool).
function(ord_less_eq_nat2, (naT, naT) booL).
function(dvd_dvd_Code_integer, (code_integer) fun_Co535713875r_bool).
function(dvd_dv413397790teger2, (code_integer, code_integer) booL).
function(dvd_dvd_int, (inT) fun_int_bool).
function(dvd_dvd_int2, (inT, inT) booL).
function(dvd_dvd_nat, (naT) fun_nat_bool).
function(dvd_dvd_nat2, (naT, naT) booL).
function(image_1151633089nteger, (fun_Co1957674295nteger, set_Code_integer) set_Code_integer).
function(image_int_int, (fun_int_int, set_int) set_int).
function(image_nat_nat, (fun_nat_nat, set_nat) set_nat).
function(aa_Cod479057144nteger, (fun_Co1957674295nteger, code_integer) code_integer).
function(aa_Code_integer_bool, (fun_Co535713875r_bool, code_integer) booL).
function(aa_Cod1485984722nteger, (fun_Co708814609nteger, code_integer) fun_Co1957674295nteger).
function(aa_int_bool, (fun_int_bool, inT) booL).
function(aa_int_int, (fun_int_int, inT) inT).
function(aa_int_fun_int_int, (fun_int_fun_int_int, inT) fun_int_int).
function(aa_nat_bool, (fun_nat_bool, naT) booL).
function(aa_nat_nat, (fun_nat_nat, naT) naT).
function(aa_nat_fun_nat_nat, (fun_nat_fun_nat_nat, naT) fun_nat_nat).
function(aa_num_int, (fun_num_int, nuM) inT).
function(aa_literal_literal, (fun_literal_literal, literaL) literaL).
function(aa_lit1494493019iteral, (fun_li1962565290iteral, literaL) fun_literal_literal).
function(fFalsE, booL).
function(fTruE, booL).
function(x, a).
predicate(monoid_literal, fun_li1962565290iteral, literaL).
predicate(pp, booL).
end_of_list.

list_of_formulae(axioms).
formula(forall([B_1 : fun_int_fun_int_int, B_2 : inT], equal:lt(aa_int_bool(monoid_int(B_1), B_2), monoid_int2(B_1, B_2))), unc_c_Groups_Omonoid_001t__Int__Oint_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(monoid_nat(B_1), B_2), monoid_nat2(B_1, B_2))), unc_c_Groups_Omonoid_001t__Nat__Onat_0002).
formula(forall([B_1 : fun_int_fun_int_int, B_2 : inT], equal:lt(aa_int_bool(comm_monoid_int(B_1), B_2), comm_monoid_int2(B_1, B_2))), unc_c_Groups_Ocomm__monoid_001t__Int__Oint_0002).
formula(forall([B_1 : fun_nat_fun_nat_nat, B_2 : naT], equal:lt(aa_nat_bool(comm_monoid_nat(B_1), B_2), comm_monoid_nat2(B_1, B_2))), unc_c_Groups_Ocomm__monoid_001t__Nat__Onat_0002).
formula(forall([B_1 : inT, B_2 : inT], equal:lt(aa_int_bool(dvd_dvd_int(B_1), B_2), dvd_dvd_int2(B_1, B_2))), unc_c_Rings_Odvd__class_Odvd_001t__Int__Oint_0002).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_bool(dvd_dvd_nat(B_1), B_2), dvd_dvd_nat2(B_1, B_2))), unc_c_Rings_Odvd__class_Odvd_001t__Nat__Onat_0002).
formula(forall([B_1 : inT], equal:lt(aa_int_fun_int_int(plus_plus_int, B_1), plus_plus_int1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__Int__Oint_0001).
formula(forall([B_1 : inT, B_2 : inT], equal:lt(aa_int_int(plus_plus_int1(B_1), B_2), plus_plus_int2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__Int__Oint_0002).
formula(forall([B_1 : naT], equal:lt(aa_nat_fun_nat_nat(plus_plus_nat, B_1), plus_plus_nat1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0001).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_nat(plus_plus_nat1(B_1), B_2), plus_plus_nat2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__Nat__Onat_0002).
formula(forall([B_1 : inT, B_2 : inT], equal:lt(aa_int_bool(ord_less_int(B_1), B_2), ord_less_int2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless_001t__Int__Oint_0002).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_bool(ord_less_nat(B_1), B_2), ord_less_nat2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless_001t__Nat__Onat_0002).
formula(forall([B_1 : nuM], equal:lt(aa_num_int(numeral_numeral_int, B_1), numeral_numeral_int1(B_1))), unc_c_Num_Onumeral__class_Onumeral_001t__Int__Oint_0001).
formula(forall([B_1 : fun_Co708814609nteger, B_2 : code_integer], equal:lt(aa_Code_integer_bool(monoid_Code_integer(B_1), B_2), monoid_Code_integer2(B_1, B_2))), unc_c_Groups_Omonoid_001t__Code____Numeral__Ointeger_0002).
formula(forall([B_1 : inT, B_2 : inT], equal:lt(aa_int_bool(ord_less_eq_int(B_1), B_2), ord_less_eq_int2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless__eq_001t__Int__Oint_0002).
formula(forall([B_1 : naT, B_2 : naT], equal:lt(aa_nat_bool(ord_less_eq_nat(B_1), B_2), ord_less_eq_nat2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat_0002).
formula(forall([B_1 : literaL], equal:lt(aa_lit1494493019iteral(plus_plus_literal, B_1), plus_plus_literal1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__String__Oliteral_0001).
formula(forall([B_1 : literaL, B_2 : literaL], equal:lt(aa_literal_literal(plus_plus_literal1(B_1), B_2), plus_plus_literal2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__String__Oliteral_0002).
formula(forall([B_1 : fun_Co708814609nteger, B_2 : code_integer], equal:lt(aa_Code_integer_bool(comm_m604335976nteger(B_1), B_2), comm_m138292217teger2(B_1, B_2))), unc_c_Groups_Ocomm__monoid_001t__Code____Numeral__Ointeger_0002).
formula(forall([B_1 : code_integer, B_2 : code_integer], equal:lt(aa_Code_integer_bool(dvd_dvd_Code_integer(B_1), B_2), dvd_dv413397790teger2(B_1, B_2))), unc_c_Rings_Odvd__class_Odvd_001t__Code____Numeral__Ointeger_0002).
formula(forall([B_1 : code_integer], equal:lt(aa_Cod1485984722nteger(plus_p2058578406nteger, B_1), plus_p715165434teger1(B_1))), unc_c_Groups_Oplus__class_Oplus_001t__Code____Numeral__Ointeger_0001).
formula(forall([B_1 : code_integer, B_2 : code_integer], equal:lt(aa_Cod479057144nteger(plus_p715165434teger1(B_1), B_2), plus_p715165435teger2(B_1, B_2))), unc_c_Groups_Oplus__class_Oplus_001t__Code____Numeral__Ointeger_0002).
formula(forall([B_1 : code_integer, B_2 : code_integer], equal:lt(aa_Code_integer_bool(ord_le945590961nteger(B_1), B_2), ord_le1687847920teger2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless_001t__Code____Numeral__Ointeger_0002).
formula(forall([B_1 : code_integer, B_2 : code_integer], equal:lt(aa_Code_integer_bool(ord_le1426714813nteger(B_1), B_2), ord_le1442264292teger2(B_1, B_2))), unc_c_Orderings_Oord__class_Oless__eq_001t__Code____Numeral__Ointeger_0002).

formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_0_add_Oright__neutral, 900). % add.right_neutral
formula(forall([A : code_integer], equal(plus_p715165435teger2(A, zero_z413810534nteger), A)), fact_1_add_Oright__neutral, 910). % add.right_neutral
formula(forall([A : inT], equal(plus_plus_int2(A, zero_zero_int), A)), fact_2_add_Oright__neutral, 921). % add.right_neutral
formula(forall([A : literaL], equal(plus_plus_literal2(A, zero_zero_literal), A)), fact_3_add_Oright__neutral, 932). % add.right_neutral
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_4_add__0, 943). % add_0
formula(forall([A : code_integer], equal(plus_p715165435teger2(zero_z413810534nteger, A), A)), fact_5_add__0, 954). % add_0
formula(forall([A : inT], equal(plus_plus_int2(zero_zero_int, A), A)), fact_6_add__0, 965). % add_0
formula(forall([A : literaL], equal(plus_plus_literal2(zero_zero_literal, A), A)), fact_7_add__0, 976). % add_0
formula(forall([A : code_integer], equiv(equal(zero_z413810534nteger, plus_p715165435teger2(A, A)), equal(A, zero_z413810534nteger))), fact_8_double__zero__sym, 987). % double_zero_sym
formula(forall([A : inT], equiv(equal(zero_zero_int, plus_plus_int2(A, A)), equal(A, zero_zero_int))), fact_9_double__zero__sym, 997). % double_zero_sym
formula(forall([B : naT, A : naT], equiv(equal(plus_plus_nat2(B, A), A), equal(B, zero_zero_nat))), fact_10_add__cancel__left__left, 1008). % add_cancel_left_left
formula(forall([B : code_integer, A : code_integer], equiv(equal(plus_p715165435teger2(B, A), A), equal(B, zero_z413810534nteger))), fact_11_add__cancel__left__left, 1019). % add_cancel_left_left
formula(forall([B : inT, A : inT], equiv(equal(plus_plus_int2(B, A), A), equal(B, zero_zero_int))), fact_12_add__cancel__left__left, 1030). % add_cancel_left_left
formula(forall([A : naT], equal(plus_plus_nat2(zero_zero_nat, A), A)), fact_13_comm__monoid__add__class_Oadd__0, 1041). % comm_monoid_add_class.add_0
formula(forall([A : code_integer], equal(plus_p715165435teger2(zero_z413810534nteger, A), A)), fact_14_comm__monoid__add__class_Oadd__0, 1052). % comm_monoid_add_class.add_0
formula(forall([A : inT], equal(plus_plus_int2(zero_zero_int, A), A)), fact_15_comm__monoid__add__class_Oadd__0, 1063). % comm_monoid_add_class.add_0
formula(forall([A : naT], equal(A, plus_plus_nat2(A, zero_zero_nat))), fact_16_nat__arith_Orule0, 1074). % nat_arith.rule0
formula(forall([A : code_integer], equal(A, plus_p715165435teger2(A, zero_z413810534nteger))), fact_17_nat__arith_Orule0, 1085). % nat_arith.rule0
formula(forall([A : inT], equal(A, plus_plus_int2(A, zero_zero_int))), fact_18_nat__arith_Orule0, 1095). % nat_arith.rule0
formula(forall([A : naT, B : naT], equiv(equal(plus_plus_nat2(A, B), A), equal(B, zero_zero_nat))), fact_19_add__cancel__left__right, 1106). % add_cancel_left_right
formula(forall([A : code_integer, B : code_integer], equiv(equal(plus_p715165435teger2(A, B), A), equal(B, zero_z413810534nteger))), fact_20_add__cancel__left__right, 1117). % add_cancel_left_right
formula(forall([A : inT, B : inT], equiv(equal(plus_plus_int2(A, B), A), equal(B, zero_zero_int))), fact_21_add__cancel__left__right, 1128). % add_cancel_left_right
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(B, A)), equal(B, zero_zero_nat))), fact_22_add__cancel__right__left, 1139). % add_cancel_right_left
formula(forall([A : code_integer, B : code_integer], equiv(equal(A, plus_p715165435teger2(B, A)), equal(B, zero_z413810534nteger))), fact_23_add__cancel__right__left, 1150). % add_cancel_right_left
formula(forall([A : inT, B : inT], equiv(equal(A, plus_plus_int2(B, A)), equal(B, zero_zero_int))), fact_24_add__cancel__right__left, 1161). % add_cancel_right_left
formula(forall([A : naT, B : naT], equiv(equal(A, plus_plus_nat2(A, B)), equal(B, zero_zero_nat))), fact_25_add__cancel__right__right, 1172). % add_cancel_right_right
formula(forall([A : code_integer, B : code_integer], equiv(equal(A, plus_p715165435teger2(A, B)), equal(B, zero_z413810534nteger))), fact_26_add__cancel__right__right, 1183). % add_cancel_right_right
formula(forall([A : inT, B : inT], equiv(equal(A, plus_plus_int2(A, B)), equal(B, zero_zero_int))), fact_27_add__cancel__right__right, 1193). % add_cancel_right_right
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_28_add_Ocomm__neutral, 1204). % add.comm_neutral
formula(forall([A : code_integer], equal(plus_p715165435teger2(A, zero_z413810534nteger), A)), fact_29_add_Ocomm__neutral, 1215). % add.comm_neutral
formula(forall([A : inT], equal(plus_plus_int2(A, zero_zero_int), A)), fact_30_add_Ocomm__neutral, 1226). % add.comm_neutral
formula(forall([X : naT, Y : naT], equiv(equal(plus_plus_nat2(X, Y), zero_zero_nat), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_31_add__eq__0__iff__both__eq__0, 1237). % add_eq_0_iff_both_eq_0
formula(forall([A : naT], equal(plus_plus_nat2(A, zero_zero_nat), A)), fact_32_verit__sum__simplify, 1248). % verit_sum_simplify
formula(forall([A : code_integer], equal(plus_p715165435teger2(A, zero_z413810534nteger), A)), fact_33_verit__sum__simplify, 1259). % verit_sum_simplify
formula(forall([A : inT], equal(plus_plus_int2(A, zero_zero_int), A)), fact_34_verit__sum__simplify, 1270). % verit_sum_simplify
formula(forall([A : code_integer], equal(plus_p715165435teger2(zero_z413810534nteger, A), A)), fact_35_add_Ogroup__left__neutral, 1281). % add.group_left_neutral
formula(forall([A : inT], equal(plus_plus_int2(zero_zero_int, A), A)), fact_36_add_Ogroup__left__neutral, 1291). % add.group_left_neutral
formula(forall([X : naT, Y : naT], equiv(equal(zero_zero_nat, plus_plus_nat2(X, Y)), and(equal(X, zero_zero_nat), equal(Y, zero_zero_nat)))), fact_37_zero__eq__add__iff__both__eq__0, 1302). % zero_eq_add_iff_both_eq_0
formula(forall([A : naT, B : naT, C : naT], equiv(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_38_add__left__cancel, 1313). % add_left_cancel
formula(forall([A : code_integer, B : code_integer, C : code_integer], equiv(equal(plus_p715165435teger2(A, B), plus_p715165435teger2(A, C)), equal(B, C))), fact_39_add__left__cancel, 1324). % add_left_cancel
formula(forall([A : inT, B : inT, C : inT], equiv(equal(plus_plus_int2(A, B), plus_plus_int2(A, C)), equal(B, C))), fact_40_add__left__cancel, 1335). % add_left_cancel
formula(forall([A : code_integer], equiv(equal(plus_p715165435teger2(A, A), zero_z413810534nteger), equal(A, zero_z413810534nteger))), fact_41_double__eq__0__iff, 1346). % double_eq_0_iff
formula(forall([A : inT], equiv(equal(plus_plus_int2(A, A), zero_zero_int), equal(A, zero_zero_int))), fact_42_double__eq__0__iff, 1357). % double_eq_0_iff
formula(forall([B : naT, A : naT, C : naT], equiv(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_43_add__right__cancel, 1368). % add_right_cancel
formula(forall([B : code_integer, A : code_integer, C : code_integer], equiv(equal(plus_p715165435teger2(B, A), plus_p715165435teger2(C, A)), equal(B, C))), fact_44_add__right__cancel, 1379). % add_right_cancel
formula(forall([B : inT, A : inT, C : inT], equiv(equal(plus_plus_int2(B, A), plus_plus_int2(C, A)), equal(B, C))), fact_45_add__right__cancel, 1389). % add_right_cancel
formula(forall([A : naT, B : naT], equal(plus_plus_nat2(A, B), plus_plus_nat2(B, A))), fact_46_add_Ocommute, 1400). % add.commute
formula(forall([A : code_integer, B : code_integer], equal(plus_p715165435teger2(A, B), plus_p715165435teger2(B, A))), fact_47_add_Ocommute, 1411). % add.commute
formula(forall([A : inT, B : inT], equal(plus_plus_int2(A, B), plus_plus_int2(B, A))), fact_48_add_Ocommute, 1422). % add.commute
formula(forall([B : naT, A : naT, C : naT], equal(plus_plus_nat2(B, plus_plus_nat2(A, C)), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_49_add_Oleft__commute, 1433). % add.left_commute
formula(forall([B : code_integer, A : code_integer, C : code_integer], equal(plus_p715165435teger2(B, plus_p715165435teger2(A, C)), plus_p715165435teger2(A, plus_p715165435teger2(B, C)))), fact_50_add_Oleft__commute, 1444). % add.left_commute
formula(forall([B : inT, A : inT, C : inT], equal(plus_plus_int2(B, plus_plus_int2(A, C)), plus_plus_int2(A, plus_plus_int2(B, C)))), fact_51_add_Oleft__commute, 1455). % add.left_commute
formula(forall([A : naT, B : naT, C : naT], implies(equal(plus_plus_nat2(A, B), plus_plus_nat2(A, C)), equal(B, C))), fact_52_add__left__imp__eq, 1466). % add_left_imp_eq
formula(forall([A : code_integer, B : code_integer, C : code_integer], implies(equal(plus_p715165435teger2(A, B), plus_p715165435teger2(A, C)), equal(B, C))), fact_53_add__left__imp__eq, 1477). % add_left_imp_eq
formula(forall([A : inT, B : inT, C : inT], implies(equal(plus_plus_int2(A, B), plus_plus_int2(A, C)), equal(B, C))), fact_54_add__left__imp__eq, 1487). % add_left_imp_eq
formula(forall([X : a], equiv(equal(zero_zero_a, X), equal(X, zero_zero_a))), fact_55_zero__reorient, 1498). % zero_reorient
formula(forall([X : naT], equiv(equal(zero_zero_nat, X), equal(X, zero_zero_nat))), fact_56_zero__reorient, 1509). % zero_reorient
formula(forall([X : code_integer], equiv(equal(zero_z413810534nteger, X), equal(X, zero_z413810534nteger))), fact_57_zero__reorient, 1520). % zero_reorient
formula(forall([X : inT], equiv(equal(zero_zero_int, X), equal(X, zero_zero_int))), fact_58_zero__reorient, 1531). % zero_reorient
formula(forall([X : literaL], equiv(equal(zero_zero_literal, X), equal(X, zero_zero_literal))), fact_59_zero__reorient, 1542). % zero_reorient
formula(forall([N : naT], equal:lt(plus_plus_nat2(zero_zero_nat, N), N)), fact_60_plus__nat_Osimps_I1_J, 1553). % plus_nat.simps(1)
formula(forall([A2 : naT, K : naT, A : naT, B : naT], implies(equal(A2, plus_plus_nat2(K, A)), equal(plus_plus_nat2(A2, B), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_61_group__cancel_Oadd1, 1564). % group_cancel.add1
formula(forall([A2 : code_integer, K : code_integer, A : code_integer, B : code_integer], implies(equal(A2, plus_p715165435teger2(K, A)), equal(plus_p715165435teger2(A2, B), plus_p715165435teger2(K, plus_p715165435teger2(A, B))))), fact_62_group__cancel_Oadd1, 1575). % group_cancel.add1
formula(forall([A2 : inT, K : inT, A : inT, B : inT], implies(equal(A2, plus_plus_int2(K, A)), equal(plus_plus_int2(A2, B), plus_plus_int2(K, plus_plus_int2(A, B))))), fact_63_group__cancel_Oadd1, 1585). % group_cancel.add1
formula(forall([B2 : naT, K : naT, B : naT, A : naT], implies(equal(B2, plus_plus_nat2(K, B)), equal(plus_plus_nat2(A, B2), plus_plus_nat2(K, plus_plus_nat2(A, B))))), fact_64_group__cancel_Oadd2, 1596). % group_cancel.add2
formula(forall([B2 : code_integer, K : code_integer, B : code_integer, A : code_integer], implies(equal(B2, plus_p715165435teger2(K, B)), equal(plus_p715165435teger2(A, B2), plus_p715165435teger2(K, plus_p715165435teger2(A, B))))), fact_65_group__cancel_Oadd2, 1607). % group_cancel.add2
formula(forall([B2 : inT, K : inT, B : inT, A : inT], implies(equal(B2, plus_plus_int2(K, B)), equal(plus_plus_int2(A, B2), plus_plus_int2(K, plus_plus_int2(A, B))))), fact_66_group__cancel_Oadd2, 1618). % group_cancel.add2
formula(forall([B : naT, A : naT, C : naT], implies(equal(plus_plus_nat2(B, A), plus_plus_nat2(C, A)), equal(B, C))), fact_67_add__right__imp__eq, 1629). % add_right_imp_eq
formula(forall([B : code_integer, A : code_integer, C : code_integer], implies(equal(plus_p715165435teger2(B, A), plus_p715165435teger2(C, A)), equal(B, C))), fact_68_add__right__imp__eq, 1640). % add_right_imp_eq
formula(forall([B : inT, A : inT, C : inT], implies(equal(plus_plus_int2(B, A), plus_plus_int2(C, A)), equal(B, C))), fact_69_add__right__imp__eq, 1651). % add_right_imp_eq
formula(forall([P : fun_nat_bool, L : naT], equiv(exists([X2 : naT], pp(aa_nat_bool(P, times_times_nat(L, X2)))), exists([X2 : naT], and(pp(dvd_dvd_nat2(L, plus_plus_nat2(X2, zero_zero_nat))), pp(aa_nat_bool(P, X2)))))), fact_70_unity__coeff__ex, 1662). % unity_coeff_ex
formula(forall([P : fun_Co535713875r_bool, L : code_integer], equiv(exists([X2 : code_integer], pp(aa_Code_integer_bool(P, times_1419655522nteger(L, X2)))), exists([X2 : code_integer], and(pp(dvd_dv413397790teger2(L, plus_p715165435teger2(X2, zero_z413810534nteger))), pp(aa_Code_integer_bool(P, X2)))))), fact_71_unity__coeff__ex, 1672). % unity_coeff_ex
formula(forall([P : fun_int_bool, L : inT], equiv(exists([X2 : inT], pp(aa_int_bool(P, times_times_int(L, X2)))), exists([X2 : inT], and(pp(dvd_dvd_int2(L, plus_plus_int2(X2, zero_zero_int))), pp(aa_int_bool(P, X2)))))), fact_72_unity__coeff__ex, 1683). % unity_coeff_ex
formula(forall([S : set_nat], equal(image_nat_nat(plus_plus_nat1(zero_zero_nat), S), S)), fact_73_image__add__0, 1694). % image_add_0
formula(forall([S : set_Code_integer], equal(image_1151633089nteger(plus_p715165434teger1(zero_z413810534nteger), S), S)), fact_74_image__add__0, 1705). % image_add_0
formula(forall([S : set_int], equal(image_int_int(plus_plus_int1(zero_zero_int), S), S)), fact_75_image__add__0, 1716). % image_add_0
formula(forall([B : code_integer, A : code_integer, C : code_integer], equiv(equal(plus_p715165435teger2(B, A), plus_p715165435teger2(C, A)), equal(B, C))), fact_76_add_Oright__cancel, 1727). % add.right_cancel
formula(forall([B : inT, A : inT, C : inT], equiv(equal(plus_plus_int2(B, A), plus_plus_int2(C, A)), equal(B, C))), fact_77_add_Oright__cancel, 1738). % add.right_cancel
formula(forall([A : code_integer, B : code_integer, C : code_integer], equiv(equal(plus_p715165435teger2(A, B), plus_p715165435teger2(A, C)), equal(B, C))), fact_78_add_Oleft__cancel, 1749). % add.left_cancel
formula(forall([A : inT, B : inT, C : inT], equiv(equal(plus_plus_int2(A, B), plus_plus_int2(A, C)), equal(B, C))), fact_79_add_Oleft__cancel, 1760). % add.left_cancel
formula(forall([M : naT], equal(plus_plus_nat2(M, zero_zero_nat), M)), fact_80_Nat_Oadd__0__right, 1770). % Nat.add_0_right
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_81_add_Oassoc, 1781). % add.assoc
formula(forall([A : code_integer, B : code_integer, C : code_integer], equal(plus_p715165435teger2(plus_p715165435teger2(A, B), C), plus_p715165435teger2(A, plus_p715165435teger2(B, C)))), fact_82_add_Oassoc, 1792). % add.assoc
formula(forall([A : inT, B : inT, C : inT], equal(plus_plus_int2(plus_plus_int2(A, B), C), plus_plus_int2(A, plus_plus_int2(B, C)))), fact_83_add_Oassoc, 1803). % add.assoc
formula(forall([A : literaL, B : literaL, C : literaL], equal(plus_plus_literal2(plus_plus_literal2(A, B), C), plus_plus_literal2(A, plus_plus_literal2(B, C)))), fact_84_add_Oassoc, 1814). % add.assoc
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(equal(I, J), equal(K, L)), equal(plus_plus_nat2(I, K), plus_plus_nat2(J, L)))), fact_85_add__mono__thms__linordered__semiring_I4_J, 1825). % add_mono_thms_linordered_semiring(4)
formula(forall([I : code_integer, J : code_integer, K : code_integer, L : code_integer], implies(and(equal(I, J), equal(K, L)), equal(plus_p715165435teger2(I, K), plus_p715165435teger2(J, L)))), fact_86_add__mono__thms__linordered__semiring_I4_J, 1836). % add_mono_thms_linordered_semiring(4)
formula(forall([I : inT, J : inT, K : inT, L : inT], implies(and(equal(I, J), equal(K, L)), equal(plus_plus_int2(I, K), plus_plus_int2(J, L)))), fact_87_add__mono__thms__linordered__semiring_I4_J, 1847). % add_mono_thms_linordered_semiring(4)
formula(pp(comm_monoid_nat2(plus_plus_nat, zero_zero_nat)), fact_88_add_Ocomm__monoid__axioms, 1858). % add.comm_monoid_axioms
formula(pp(comm_m138292217teger2(plus_p2058578406nteger, zero_z413810534nteger)), fact_89_add_Ocomm__monoid__axioms, 1868). % add.comm_monoid_axioms
formula(pp(comm_monoid_int2(plus_plus_int, zero_zero_int)), fact_90_add_Ocomm__monoid__axioms, 1879). % add.comm_monoid_axioms
formula(forall([B : naT, A : naT], equiv(equal(B, plus_plus_nat2(B, A)), equal(A, zero_zero_nat))), fact_91_add__0__iff, 1890). % add_0_iff
formula(forall([B : code_integer, A : code_integer], equiv(equal(B, plus_p715165435teger2(B, A)), equal(A, zero_z413810534nteger))), fact_92_add__0__iff, 1901). % add_0_iff
formula(forall([B : inT, A : inT], equiv(equal(B, plus_plus_int2(B, A)), equal(A, zero_zero_int))), fact_93_add__0__iff, 1912). % add_0_iff
formula(pp(monoid_nat2(plus_plus_nat, zero_zero_nat)), fact_94_add_Omonoid__axioms, 1923). % add.monoid_axioms
formula(pp(monoid_Code_integer2(plus_p2058578406nteger, zero_z413810534nteger)), fact_95_add_Omonoid__axioms, 1934). % add.monoid_axioms
formula(pp(monoid_int2(plus_plus_int, zero_zero_int)), fact_96_add_Omonoid__axioms, 1945). % add.monoid_axioms
formula(monoid_literal(plus_plus_literal, zero_zero_literal), fact_97_add_Omonoid__axioms, 1956). % add.monoid_axioms
formula(forall([A : naT, B : naT, C : naT], equal(plus_plus_nat2(plus_plus_nat2(A, B), C), plus_plus_nat2(A, plus_plus_nat2(B, C)))), fact_98_ab__semigroup__add__class_Oadd__ac_I1_J, 1966). % ab_semigroup_add_class.add_ac(1)
formula(forall([A : code_integer, B : code_integer, C : code_integer], equal(plus_p715165435teger2(plus_p715165435teger2(A, B), C), plus_p715165435teger2(A, plus_p715165435teger2(B, C)))), fact_99_ab__semigroup__add__class_Oadd__ac_I1_J, 1977). % ab_semigroup_add_class.add_ac(1)
formula(forall([A : inT, B : inT, C : inT], equal(plus_plus_int2(plus_plus_int2(A, B), C), plus_plus_int2(A, plus_plus_int2(B, C)))), fact_100_ab__semigroup__add__class_Oadd__ac_I1_J, 1988). % ab_semigroup_add_class.add_ac(1)
formula(forall([A : code_integer, B : code_integer], equal(plus_p715165435teger2(A, uminus636303014ntegeR(B)), minus_1582103350nteger(A, B))), fact_101_add__uminus__conv__diff, 1999). % add_uminus_conv_diff
formula(forall([A : inT, B : inT], equal(plus_plus_int2(A, uminus_uminus_int(B)), minus_minus_int(A, B))), fact_102_add__uminus__conv__diff, 2010). % add_uminus_conv_diff
formula(forall([C : naT, A : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_eq_nat2(A, B)))), fact_103_add__le__cancel__left, 2021). % add_le_cancel_left
formula(forall([C : code_integer, A : code_integer, B : code_integer], equiv(pp(ord_le1442264292teger2(plus_p715165435teger2(C, A), plus_p715165435teger2(C, B))), pp(ord_le1442264292teger2(A, B)))), fact_104_add__le__cancel__left, 2032). % add_le_cancel_left
formula(forall([C : inT, A : inT, B : inT], equiv(pp(ord_less_eq_int2(plus_plus_int2(C, A), plus_plus_int2(C, B))), pp(ord_less_eq_int2(A, B)))), fact_105_add__le__cancel__left, 2043). % add_le_cancel_left
formula(forall([X : naT], pp(ord_less_eq_nat2(zero_zero_nat, X))), fact_106_zero__le, 2054). % zero_le
formula(forall([K : code_integer], equal(plus_p715165435teger2(K, zero_z413810534nteger), K)), fact_107_plus__integer__code_I1_J, 2064). % plus_integer_code(1)
formula(equal:lt(poS, numeral_numeral_int), fact_108_Int_OPos__def, 2075). % Int.Pos_def
formula(forall([A : code_integer, B : code_integer], equal(plus_p715165435teger2(uminus636303014ntegeR(A), B), minus_1582103350nteger(B, A))), fact_109_uminus__add__conv__diff, 2086). % uminus_add_conv_diff
formula(forall([A : inT, B : inT], equal(plus_plus_int2(uminus_uminus_int(A), B), minus_minus_int(B, A))), fact_110_uminus__add__conv__diff, 2097). % uminus_add_conv_diff
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(A, plus_plus_nat2(B, A))), pp(ord_less_eq_nat2(zero_zero_nat, B)))), fact_111_le__add__same__cancel2, 2108). % le_add_same_cancel2
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1442264292teger2(A, plus_p715165435teger2(B, A))), pp(ord_le1442264292teger2(zero_z413810534nteger, B)))), fact_112_le__add__same__cancel2, 2119). % le_add_same_cancel2
formula(forall([A : inT, B : inT], equiv(pp(ord_less_eq_int2(A, plus_plus_int2(B, A))), pp(ord_less_eq_int2(zero_zero_int, B)))), fact_113_le__add__same__cancel2, 2130). % le_add_same_cancel2
formula(forall([A : code_integer], equiv(pp(ord_le1442264292teger2(zero_z413810534nteger, plus_p715165435teger2(A, A))), pp(ord_le1442264292teger2(zero_z413810534nteger, A)))), fact_114_zero__le__double__add__iff__zero__le__single__add, 2141). % zero_le_double_add_iff_zero_le_single_add
formula(forall([A : inT], equiv(pp(ord_less_eq_int2(zero_zero_int, plus_plus_int2(A, A))), pp(ord_less_eq_int2(zero_zero_int, A)))), fact_115_zero__le__double__add__iff__zero__le__single__add, 2152). % zero_le_double_add_iff_zero_le_single_add
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(A, plus_plus_nat2(A, B))), pp(ord_less_eq_nat2(zero_zero_nat, B)))), fact_116_le__add__same__cancel1, 2162). % le_add_same_cancel1
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1442264292teger2(A, plus_p715165435teger2(A, B))), pp(ord_le1442264292teger2(zero_z413810534nteger, B)))), fact_117_le__add__same__cancel1, 2173). % le_add_same_cancel1
formula(forall([A : inT, B : inT], equiv(pp(ord_less_eq_int2(A, plus_plus_int2(A, B))), pp(ord_less_eq_int2(zero_zero_int, B)))), fact_118_le__add__same__cancel1, 2184). % le_add_same_cancel1
formula(forall([K : inT], equal(plus_plus_int2(K, zero_zero_int), K)), fact_119_plus__int__code_I1_J, 2195). % plus_int_code(1)
formula(forall([A : code_integer], equiv(pp(ord_le1442264292teger2(plus_p715165435teger2(A, A), zero_z413810534nteger)), pp(ord_le1442264292teger2(A, zero_z413810534nteger)))), fact_120_double__add__le__zero__iff__single__add__le__zero, 2206). % double_add_le_zero_iff_single_add_le_zero
formula(forall([A : inT], equiv(pp(ord_less_eq_int2(plus_plus_int2(A, A), zero_zero_int)), pp(ord_less_eq_int2(A, zero_zero_int)))), fact_121_double__add__le__zero__iff__single__add__le__zero, 2217). % double_add_le_zero_iff_single_add_le_zero
formula(forall([A : code_integer, B : code_integer, C : code_integer], equal(plus_p715165435teger2(plus_p715165435teger2(A, B), C), plus_p715165435teger2(A, plus_p715165435teger2(B, C)))), fact_122_is__num__normalize_I1_J, 2228). % is_num_normalize(1)
formula(forall([A : inT, B : inT, C : inT], equal(plus_plus_int2(plus_plus_int2(A, B), C), plus_plus_int2(A, plus_plus_int2(B, C)))), fact_123_is__num__normalize_I1_J, 2239). % is_num_normalize(1)
formula(forall([L : inT], equal(plus_plus_int2(zero_zero_int, L), L)), fact_124_plus__int__code_I2_J, 2250). % plus_int_code(2)
formula(forall([B : naT, A : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(B, A), B)), pp(ord_less_eq_nat2(A, zero_zero_nat)))), fact_125_add__le__same__cancel1, 2260). % add_le_same_cancel1
formula(forall([B : code_integer, A : code_integer], equiv(pp(ord_le1442264292teger2(plus_p715165435teger2(B, A), B)), pp(ord_le1442264292teger2(A, zero_z413810534nteger)))), fact_126_add__le__same__cancel1, 2271). % add_le_same_cancel1
formula(forall([B : inT, A : inT], equiv(pp(ord_less_eq_int2(plus_plus_int2(B, A), B)), pp(ord_less_eq_int2(A, zero_zero_int)))), fact_127_add__le__same__cancel1, 2282). % add_le_same_cancel1
formula(forall([A : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(A, B), B)), pp(ord_less_eq_nat2(A, zero_zero_nat)))), fact_128_add__le__same__cancel2, 2293). % add_le_same_cancel2
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1442264292teger2(plus_p715165435teger2(A, B), B)), pp(ord_le1442264292teger2(A, zero_z413810534nteger)))), fact_129_add__le__same__cancel2, 2304). % add_le_same_cancel2
formula(forall([A : inT, B : inT], equiv(pp(ord_less_eq_int2(plus_plus_int2(A, B), B)), pp(ord_less_eq_int2(A, zero_zero_int)))), fact_130_add__le__same__cancel2, 2315). % add_le_same_cancel2
formula(forall([N : naT], equiv(pp(ord_less_eq_nat2(N, zero_zero_nat)), equal(N, zero_zero_nat))), fact_131_le__zero__eq, 2326). % le_zero_eq
formula(forall([L : code_integer], equal(plus_p715165435teger2(zero_z413810534nteger, L), L)), fact_132_plus__integer__code_I2_J, 2337). % plus_integer_code(2)
formula(forall([N : naT], equiv(not(pp(ord_less_nat2(zero_zero_nat, N))), equal(N, zero_zero_nat))), fact_133_not__gr__zero, 2347). % not_gr_zero
formula(forall([A : code_integer], equiv(pp(ord_le1687847920teger2(zero_z413810534nteger, plus_p715165435teger2(A, A))), pp(ord_le1687847920teger2(zero_z413810534nteger, A)))), fact_134_zero__less__double__add__iff__zero__less__single__add, 2358). % zero_less_double_add_iff_zero_less_single_add
formula(forall([A : inT], equiv(pp(ord_less_int2(zero_zero_int, plus_plus_int2(A, A))), pp(ord_less_int2(zero_zero_int, A)))), fact_135_zero__less__double__add__iff__zero__less__single__add, 2369). % zero_less_double_add_iff_zero_less_single_add
formula(forall([C : code_integer, A : code_integer, B : code_integer], equiv(pp(ord_le1687847920teger2(plus_p715165435teger2(C, A), plus_p715165435teger2(C, B))), pp(ord_le1687847920teger2(A, B)))), fact_136_add__less__cancel__left, 2380). % add_less_cancel_left
formula(forall([C : inT, A : inT, B : inT], equiv(pp(ord_less_int2(plus_plus_int2(C, A), plus_plus_int2(C, B))), pp(ord_less_int2(A, B)))), fact_137_add__less__cancel__left, 2391). % add_less_cancel_left
formula(forall([C : naT, A : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))), pp(ord_less_nat2(A, B)))), fact_138_add__less__cancel__left, 2402). % add_less_cancel_left
formula(forall([S2 : literaL], equal(plus_plus_literal2(zero_zero_literal, S2), S2)), fact_139_add__literal__code_I1_J, 2413). % add_literal_code(1)
formula(forall([A : naT, C : naT, B : naT], equiv(pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_eq_nat2(A, B)))), fact_140_add__le__cancel__right, 2424). % add_le_cancel_right
formula(forall([A : code_integer, C : code_integer, B : code_integer], equiv(pp(ord_le1442264292teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, C))), pp(ord_le1442264292teger2(A, B)))), fact_141_add__le__cancel__right, 2435). % add_le_cancel_right
formula(forall([A : inT, C : inT, B : inT], equiv(pp(ord_less_eq_int2(plus_plus_int2(A, C), plus_plus_int2(B, C))), pp(ord_less_eq_int2(A, B)))), fact_142_add__le__cancel__right, 2445). % add_le_cancel_right
formula(forall([S2 : literaL], equal(plus_plus_literal2(S2, zero_zero_literal), S2)), fact_143_add__literal__code_I2_J, 2456). % add_literal_code(2)
formula(forall([A : naT], equal(times_times_nat(one_one_nat, A), A)), fact_144_mult__1, 2467). % mult_1
formula(forall([A : code_integer, C : code_integer, B : code_integer], equiv(pp(ord_le1687847920teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, C))), pp(ord_le1687847920teger2(A, B)))), fact_145_add__less__cancel__right, 2478). % add_less_cancel_right
formula(forall([A : inT, C : inT, B : inT], equiv(pp(ord_less_int2(plus_plus_int2(A, C), plus_plus_int2(B, C))), pp(ord_less_int2(A, B)))), fact_146_add__less__cancel__right, 2489). % add_less_cancel_right
formula(forall([A : naT, C : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))), pp(ord_less_nat2(A, B)))), fact_147_add__less__cancel__right, 2500). % add_less_cancel_right
formula(forall([B : code_integer, A : code_integer], equiv(pp(ord_le1687847920teger2(plus_p715165435teger2(B, A), B)), pp(ord_le1687847920teger2(A, zero_z413810534nteger)))), fact_148_add__less__same__cancel1, 2511). % add_less_same_cancel1
formula(forall([B : inT, A : inT], equiv(pp(ord_less_int2(plus_plus_int2(B, A), B)), pp(ord_less_int2(A, zero_zero_int)))), fact_149_add__less__same__cancel1, 2522). % add_less_same_cancel1
formula(forall([B : naT, A : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(B, A), B)), pp(ord_less_nat2(A, zero_zero_nat)))), fact_150_add__less__same__cancel1, 2533). % add_less_same_cancel1
formula(equal:lt(one_one_nat, suC(zero_zero_nat)), fact_151_One__nat__def, 2543). % One_nat_def
formula(forall([M : nuM, N : nuM], equal:lt(suB(M, N), minus_minus_int(numeral_numeral_int1(M), numeral_numeral_int1(N)))), fact_152_Int_Osub__def, 2554). % Int.sub_def
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1687847920teger2(plus_p715165435teger2(A, B), B)), pp(ord_le1687847920teger2(A, zero_z413810534nteger)))), fact_153_add__less__same__cancel2, 2565). % add_less_same_cancel2
formula(forall([A : inT, B : inT], equiv(pp(ord_less_int2(plus_plus_int2(A, B), B)), pp(ord_less_int2(A, zero_zero_int)))), fact_154_add__less__same__cancel2, 2576). % add_less_same_cancel2
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(plus_plus_nat2(A, B), B)), pp(ord_less_nat2(A, zero_zero_nat)))), fact_155_add__less__same__cancel2, 2587). % add_less_same_cancel2
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1687847920teger2(A, plus_p715165435teger2(A, B))), pp(ord_le1687847920teger2(zero_z413810534nteger, B)))), fact_156_less__add__same__cancel1, 2598). % less_add_same_cancel1
formula(forall([A : inT, B : inT], equiv(pp(ord_less_int2(A, plus_plus_int2(A, B))), pp(ord_less_int2(zero_zero_int, B)))), fact_157_less__add__same__cancel1, 2609). % less_add_same_cancel1
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(A, plus_plus_nat2(A, B))), pp(ord_less_nat2(zero_zero_nat, B)))), fact_158_less__add__same__cancel1, 2620). % less_add_same_cancel1
formula(forall([A : naT], equal(times_times_nat(A, one_one_nat), A)), fact_159_mult_Oright__neutral, 2631). % mult.right_neutral
formula(forall([N : naT], not(pp(ord_less_nat2(N, zero_zero_nat)))), fact_160_not__less__zero, 2641). % not_less_zero
formula(forall([X : naT, Y : naT], equiv(not(pp(ord_less_nat2(X, Y))), pp(ord_less_eq_nat2(Y, X)))), fact_161_linorder__not__less, 2652). % linorder_not_less
formula(forall([A : code_integer], equal(plus_p715165435teger2(uminus636303014ntegeR(A), A), zero_z413810534nteger)), fact_162_ab__left__minus, 2663). % ab_left_minus
formula(forall([A : inT], equal(plus_plus_int2(uminus_uminus_int(A), A), zero_zero_int)), fact_163_ab__left__minus, 2674). % ab_left_minus
formula(forall([A : code_integer, B : code_integer], equiv(pp(ord_le1687847920teger2(A, plus_p715165435teger2(B, A))), pp(ord_le1687847920teger2(zero_z413810534nteger, B)))), fact_164_less__add__same__cancel2, 2685). % less_add_same_cancel2
formula(forall([A : inT, B : inT], equiv(pp(ord_less_int2(A, plus_plus_int2(B, A))), pp(ord_less_int2(zero_zero_int, B)))), fact_165_less__add__same__cancel2, 2696). % less_add_same_cancel2
formula(forall([A : naT, B : naT], equiv(pp(ord_less_nat2(A, plus_plus_nat2(B, A))), pp(ord_less_nat2(zero_zero_nat, B)))), fact_166_less__add__same__cancel2, 2707). % less_add_same_cancel2
formula(forall([A : code_integer], equiv(pp(ord_le1687847920teger2(plus_p715165435teger2(A, A), zero_z413810534nteger)), pp(ord_le1687847920teger2(A, zero_z413810534nteger)))), fact_167_double__add__less__zero__iff__single__add__less__zero, 2718). % double_add_less_zero_iff_single_add_less_zero
formula(forall([A : inT], equiv(pp(ord_less_int2(plus_plus_int2(A, A), zero_zero_int)), pp(ord_less_int2(A, zero_zero_int)))), fact_168_double__add__less__zero__iff__single__add__less__zero, 2729). % double_add_less_zero_iff_single_add_less_zero
formula(forall([A : naT, B : naT], equal(minus_minus_nat(plus_plus_nat2(A, B), A), B)), fact_169_add__diff__cancel__left_H, 2739). % add_diff_cancel_left'
formula(forall([A : code_integer, B : code_integer], equal(minus_1582103350nteger(plus_p715165435teger2(A, B), A), B)), fact_170_add__diff__cancel__left_H, 2750). % add_diff_cancel_left'
formula(forall([A : inT, B : inT], equal(minus_minus_int(plus_plus_int2(A, B), A), B)), fact_171_add__diff__cancel__left_H, 2761). % add_diff_cancel_left'
formula(forall([A : naT], equal(times_times_nat(one_one_nat, A), A)), fact_172_comm__monoid__mult__class_Omult__1, 2772). % comm_monoid_mult_class.mult_1
formula(forall([X : naT], not(pp(ord_less_nat2(X, X)))), fact_173_order__less__irrefl, 2783). % order_less_irrefl
formula(forall([X : naT, Y : naT], equiv(pp(ord_less_nat2(X, Y)), and(pp(ord_less_eq_nat2(X, Y)), not(equal(X, Y))))), fact_174_order__less__le, 2794). % order_less_le
formula(forall([X2_ : naT], not(equal(suC(X2_), zero_zero_nat))), fact_175_nat_Osimps_I3_J, 2805). % nat.simps(3)
formula(forall([A : naT, B : naT, C : naT], equal(times_times_nat(plus_plus_nat2(A, B), C), plus_plus_nat2(times_times_nat(A, C), times_times_nat(B, C)))), fact_176_comm__semiring__class_Odistrib, 2816). % comm_semiring_class.distrib
formula(forall([A : code_integer, B : code_integer, C : code_integer], equal(times_1419655522nteger(plus_p715165435teger2(A, B), C), plus_p715165435teger2(times_1419655522nteger(A, C), times_1419655522nteger(B, C)))), fact_177_comm__semiring__class_Odistrib, 2827). % comm_semiring_class.distrib
formula(forall([A : inT, B : inT, C : inT], equal(times_times_int(plus_plus_int2(A, B), C), plus_plus_int2(times_times_int(A, C), times_times_int(B, C)))), fact_178_comm__semiring__class_Odistrib, 2837). % comm_semiring_class.distrib
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), pp(ord_less_eq_nat2(K, L))), pp(ord_less_eq_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_179_add__mono__thms__linordered__semiring_I1_J, 2848). % add_mono_thms_linordered_semiring(1)
formula(forall([I : code_integer, J : code_integer, K : code_integer, L : code_integer], implies(and(pp(ord_le1442264292teger2(I, J)), pp(ord_le1442264292teger2(K, L))), pp(ord_le1442264292teger2(plus_p715165435teger2(I, K), plus_p715165435teger2(J, L))))), fact_180_add__mono__thms__linordered__semiring_I1_J, 2859). % add_mono_thms_linordered_semiring(1)
formula(forall([I : inT, J : inT, K : inT, L : inT], implies(and(pp(ord_less_eq_int2(I, J)), pp(ord_less_eq_int2(K, L))), pp(ord_less_eq_int2(plus_plus_int2(I, K), plus_plus_int2(J, L))))), fact_181_add__mono__thms__linordered__semiring_I1_J, 2870). % add_mono_thms_linordered_semiring(1)
formula(forall([A : code_integer, B : code_integer, C : code_integer, D : code_integer], implies(pp(ord_le1687847920teger2(A, B)), implies(pp(ord_le1442264292teger2(C, D)), pp(ord_le1687847920teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, D)))))), fact_182_add__less__le__mono, 2881). % add_less_le_mono
formula(forall([A : inT, B : inT, C : inT, D : inT], implies(pp(ord_less_int2(A, B)), implies(pp(ord_less_eq_int2(C, D)), pp(ord_less_int2(plus_plus_int2(A, C), plus_plus_int2(B, D)))))), fact_183_add__less__le__mono, 2892). % add_less_le_mono
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_nat2(A, B)), implies(pp(ord_less_eq_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_184_add__less__le__mono, 2903). % add_less_le_mono
formula(forall([A : code_integer, B : code_integer, C : code_integer, D : code_integer], implies(pp(ord_le1442264292teger2(A, B)), implies(pp(ord_le1687847920teger2(C, D)), pp(ord_le1687847920teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, D)))))), fact_185_add__le__less__mono, 2914). % add_le_less_mono
formula(forall([A : inT, B : inT, C : inT, D : inT], implies(pp(ord_less_eq_int2(A, B)), implies(pp(ord_less_int2(C, D)), pp(ord_less_int2(plus_plus_int2(A, C), plus_plus_int2(B, D)))))), fact_186_add__le__less__mono, 2925). % add_le_less_mono
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(pp(ord_less_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_187_add__le__less__mono, 2935). % add_le_less_mono
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), equal(K, L)), pp(ord_less_eq_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_188_add__mono__thms__linordered__semiring_I3_J, 2946). % add_mono_thms_linordered_semiring(3)
formula(forall([I : code_integer, J : code_integer, K : code_integer, L : code_integer], implies(and(pp(ord_le1442264292teger2(I, J)), equal(K, L)), pp(ord_le1442264292teger2(plus_p715165435teger2(I, K), plus_p715165435teger2(J, L))))), fact_189_add__mono__thms__linordered__semiring_I3_J, 2957). % add_mono_thms_linordered_semiring(3)
formula(forall([I : inT, J : inT, K : inT, L : inT], implies(and(pp(ord_less_eq_int2(I, J)), equal(K, L)), pp(ord_less_eq_int2(plus_plus_int2(I, K), plus_plus_int2(J, L))))), fact_190_add__mono__thms__linordered__semiring_I3_J, 2968). % add_mono_thms_linordered_semiring(3)
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1687847920teger2(A, zero_z413810534nteger)), implies(pp(ord_le1442264292teger2(B, zero_z413810534nteger)), pp(ord_le1687847920teger2(plus_p715165435teger2(A, B), zero_z413810534nteger))))), fact_191_add__neg__nonpos, 2979). % add_neg_nonpos
formula(forall([A : inT, B : inT], implies(pp(ord_less_int2(A, zero_zero_int)), implies(pp(ord_less_eq_int2(B, zero_zero_int)), pp(ord_less_int2(plus_plus_int2(A, B), zero_zero_int))))), fact_192_add__neg__nonpos, 2990). % add_neg_nonpos
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, zero_zero_nat)), implies(pp(ord_less_eq_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_193_add__neg__nonpos, 3001). % add_neg_nonpos
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1442264292teger2(zero_z413810534nteger, A)), implies(pp(ord_le1687847920teger2(zero_z413810534nteger, B)), pp(ord_le1687847920teger2(zero_z413810534nteger, plus_p715165435teger2(A, B)))))), fact_194_add__nonneg__pos, 3012). % add_nonneg_pos
formula(forall([A : inT, B : inT], implies(pp(ord_less_eq_int2(zero_zero_int, A)), implies(pp(ord_less_int2(zero_zero_int, B)), pp(ord_less_int2(zero_zero_int, plus_plus_int2(A, B)))))), fact_195_add__nonneg__pos, 3022). % add_nonneg_pos
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_196_add__nonneg__pos, 3033). % add_nonneg_pos
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1687847920teger2(zero_z413810534nteger, A)), implies(pp(ord_le1442264292teger2(zero_z413810534nteger, B)), pp(ord_le1687847920teger2(zero_z413810534nteger, plus_p715165435teger2(A, B)))))), fact_197_add__pos__nonneg, 3044). % add_pos_nonneg
formula(forall([A : inT, B : inT], implies(pp(ord_less_int2(zero_zero_int, A)), implies(pp(ord_less_eq_int2(zero_zero_int, B)), pp(ord_less_int2(zero_zero_int, plus_plus_int2(A, B)))))), fact_198_add__pos__nonneg, 3055). % add_pos_nonneg
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_199_add__pos__nonneg, 3066). % add_pos_nonneg
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1442264292teger2(A, zero_z413810534nteger)), implies(pp(ord_le1687847920teger2(B, zero_z413810534nteger)), pp(ord_le1687847920teger2(plus_p715165435teger2(A, B), zero_z413810534nteger))))), fact_200_add__nonpos__neg, 3077). % add_nonpos_neg
formula(forall([A : inT, B : inT], implies(pp(ord_less_eq_int2(A, zero_zero_int)), implies(pp(ord_less_int2(B, zero_zero_int)), pp(ord_less_int2(plus_plus_int2(A, B), zero_zero_int))))), fact_201_add__nonpos__neg, 3088). % add_nonpos_neg
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(A, zero_zero_nat)), implies(pp(ord_less_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_202_add__nonpos__neg, 3099). % add_nonpos_neg
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, B)), not(forall([C2 : naT], implies(equal(B, plus_plus_nat2(A, C2)), equal(C2, zero_zero_nat)))))), fact_203_canonically__ordered__monoid__add__class_OlessE, 3110). % canonically_ordered_monoid_add_class.lessE
formula(forall([A : naT], equal(times_times_nat(zero_zero_nat, A), zero_zero_nat)), fact_204_mult__zero__left, 3120). % mult_zero_left
formula(forall([A : code_integer], equal(times_1419655522nteger(zero_z413810534nteger, A), zero_z413810534nteger)), fact_205_mult__zero__left, 3131). % mult_zero_left
formula(forall([A : inT], equal(times_times_int(zero_zero_int, A), zero_zero_int)), fact_206_mult__zero__left, 3142). % mult_zero_left
formula(forall([A : code_integer, B : code_integer, C : code_integer], implies(pp(ord_le1687847920teger2(zero_z413810534nteger, A)), implies(pp(ord_le1442264292teger2(B, C)), pp(ord_le1687847920teger2(B, plus_p715165435teger2(A, C)))))), fact_207_add__strict__increasing, 3153). % add_strict_increasing
formula(forall([A : inT, B : inT, C : inT], implies(pp(ord_less_int2(zero_zero_int, A)), implies(pp(ord_less_eq_int2(B, C)), pp(ord_less_int2(B, plus_plus_int2(A, C)))))), fact_208_add__strict__increasing, 3164). % add_strict_increasing
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(B, C)), pp(ord_less_nat2(B, plus_plus_nat2(A, C)))))), fact_209_add__strict__increasing, 3175). % add_strict_increasing
formula(forall([A : naT], equal(minus_minus_nat(A, zero_zero_nat), A)), fact_210_diff__zero, 3186). % diff_zero
formula(forall([A : code_integer], equal(minus_1582103350nteger(A, zero_z413810534nteger), A)), fact_211_diff__zero, 3197). % diff_zero
formula(forall([A : inT], equal(minus_minus_int(A, zero_zero_int), A)), fact_212_diff__zero, 3208). % diff_zero
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_eq_nat2(A, B)), implies(pp(ord_less_eq_nat2(C, D)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_213_add__mono, 3218). % add_mono
formula(forall([A : code_integer, B : code_integer, C : code_integer, D : code_integer], implies(pp(ord_le1442264292teger2(A, B)), implies(pp(ord_le1442264292teger2(C, D)), pp(ord_le1442264292teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, D)))))), fact_214_add__mono, 3229). % add_mono
formula(forall([A : inT, B : inT, C : inT, D : inT], implies(pp(ord_less_eq_int2(A, B)), implies(pp(ord_less_eq_int2(C, D)), pp(ord_less_eq_int2(plus_plus_int2(A, C), plus_plus_int2(B, D)))))), fact_215_add__mono, 3240). % add_mono
formula(forall([A : code_integer, B : code_integer, C : code_integer], implies(pp(ord_le1442264292teger2(zero_z413810534nteger, A)), implies(pp(ord_le1687847920teger2(B, C)), pp(ord_le1687847920teger2(B, plus_p715165435teger2(A, C)))))), fact_216_add__strict__increasing2, 3251). % add_strict_increasing2
formula(forall([A : inT, B : inT, C : inT], implies(pp(ord_less_eq_int2(zero_zero_int, A)), implies(pp(ord_less_int2(B, C)), pp(ord_less_int2(B, plus_plus_int2(A, C)))))), fact_217_add__strict__increasing2, 3262). % add_strict_increasing2
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(B, C)), pp(ord_less_nat2(B, plus_plus_nat2(A, C)))))), fact_218_add__strict__increasing2, 3273). % add_strict_increasing2
formula(forall([I : code_integer, J : code_integer, K : code_integer, L : code_integer], implies(and(pp(ord_le1687847920teger2(I, J)), pp(ord_le1442264292teger2(K, L))), pp(ord_le1687847920teger2(plus_p715165435teger2(I, K), plus_p715165435teger2(J, L))))), fact_219_add__mono__thms__linordered__field_I3_J, 3284). % add_mono_thms_linordered_field(3)
formula(forall([I : inT, J : inT, K : inT, L : inT], implies(and(pp(ord_less_int2(I, J)), pp(ord_less_eq_int2(K, L))), pp(ord_less_int2(plus_plus_int2(I, K), plus_plus_int2(J, L))))), fact_220_add__mono__thms__linordered__field_I3_J, 3295). % add_mono_thms_linordered_field(3)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_nat2(I, J)), pp(ord_less_eq_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_221_add__mono__thms__linordered__field_I3_J, 3306). % add_mono_thms_linordered_field(3)
formula(forall([A : naT], equiv(not(equal(A, zero_zero_nat)), pp(ord_less_nat2(zero_zero_nat, A)))), fact_222_bot__nat__0_Onot__eq__extremum, 3316). % bot_nat_0.not_eq_extremum
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(plus_plus_nat2(C, A), plus_plus_nat2(C, B))))), fact_223_add__left__mono, 3327). % add_left_mono
formula(forall([A : code_integer, B : code_integer, C : code_integer], implies(pp(ord_le1442264292teger2(A, B)), pp(ord_le1442264292teger2(plus_p715165435teger2(C, A), plus_p715165435teger2(C, B))))), fact_224_add__left__mono, 3338). % add_left_mono
formula(forall([A : inT, B : inT, C : inT], implies(pp(ord_less_eq_int2(A, B)), pp(ord_less_eq_int2(plus_plus_int2(C, A), plus_plus_int2(C, B))))), fact_225_add__left__mono, 3349). % add_left_mono
formula(forall([I : code_integer, J : code_integer, K : code_integer, L : code_integer], implies(and(pp(ord_le1442264292teger2(I, J)), pp(ord_le1687847920teger2(K, L))), pp(ord_le1687847920teger2(plus_p715165435teger2(I, K), plus_p715165435teger2(J, L))))), fact_226_add__mono__thms__linordered__field_I4_J, 3360). % add_mono_thms_linordered_field(4)
formula(forall([I : inT, J : inT, K : inT, L : inT], implies(and(pp(ord_less_eq_int2(I, J)), pp(ord_less_int2(K, L))), pp(ord_less_int2(plus_plus_int2(I, K), plus_plus_int2(J, L))))), fact_227_add__mono__thms__linordered__field_I4_J, 3371). % add_mono_thms_linordered_field(4)
formula(forall([I : naT, J : naT, K : naT, L : naT], implies(and(pp(ord_less_eq_nat2(I, J)), pp(ord_less_nat2(K, L))), pp(ord_less_nat2(plus_plus_nat2(I, K), plus_plus_nat2(J, L))))), fact_228_add__mono__thms__linordered__field_I4_J, 3382). % add_mono_thms_linordered_field(4)
formula(forall([A : code_integer], equal(plus_p715165435teger2(uminus636303014ntegeR(A), A), zero_z413810534nteger)), fact_229_ab__group__add__class_Oab__left__minus, 3393). % ab_group_add_class.ab_left_minus
formula(forall([A : inT], equal(plus_plus_int2(uminus_uminus_int(A), A), zero_zero_int)), fact_230_ab__group__add__class_Oab__left__minus, 3404). % ab_group_add_class.ab_left_minus
formula(forall([A : code_integer, B : code_integer, C : code_integer, D : code_integer], implies(pp(ord_le1687847920teger2(A, B)), implies(pp(ord_le1687847920teger2(C, D)), pp(ord_le1687847920teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, D)))))), fact_231_add__strict__mono, 3414). % add_strict_mono
formula(forall([A : inT, B : inT, C : inT, D : inT], implies(pp(ord_less_int2(A, B)), implies(pp(ord_less_int2(C, D)), pp(ord_less_int2(plus_plus_int2(A, C), plus_plus_int2(B, D)))))), fact_232_add__strict__mono, 3425). % add_strict_mono
formula(forall([A : naT, B : naT, C : naT, D : naT], implies(pp(ord_less_nat2(A, B)), implies(pp(ord_less_nat2(C, D)), pp(ord_less_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, D)))))), fact_233_add__strict__mono, 3436). % add_strict_mono
formula(forall([A : naT, B : naT, C : naT], implies(pp(ord_less_eq_nat2(A, B)), pp(ord_less_eq_nat2(plus_plus_nat2(A, C), plus_plus_nat2(B, C))))), fact_234_add__right__mono, 3447). % add_right_mono
formula(forall([A : code_integer, B : code_integer, C : code_integer], implies(pp(ord_le1442264292teger2(A, B)), pp(ord_le1442264292teger2(plus_p715165435teger2(A, C), plus_p715165435teger2(B, C))))), fact_235_add__right__mono, 3458). % add_right_mono
formula(forall([A : inT, B : inT, C : inT], implies(pp(ord_less_eq_int2(A, B)), pp(ord_less_eq_int2(plus_plus_int2(A, C), plus_plus_int2(B, C))))), fact_236_add__right__mono, 3469). % add_right_mono
formula(forall([A : naT], equal(times_times_nat(A, zero_zero_nat), zero_zero_nat)), fact_237_mult__zero__right, 3480). % mult_zero_right
formula(forall([A : code_integer], equal(times_1419655522nteger(A, zero_z413810534nteger), zero_z413810534nteger)), fact_238_mult__zero__right, 3491). % mult_zero_right
formula(forall([A : inT], equal(times_times_int(A, zero_zero_int), zero_zero_int)), fact_239_mult__zero__right, 3502). % mult_zero_right
formula(forall([A : naT, B : naT], implies(pp(ord_less_eq_nat2(zero_zero_nat, A)), implies(pp(ord_less_eq_nat2(zero_zero_nat, B)), pp(ord_less_eq_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_240_add__nonneg__nonneg, 3512). % add_nonneg_nonneg
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1442264292teger2(zero_z413810534nteger, A)), implies(pp(ord_le1442264292teger2(zero_z413810534nteger, B)), pp(ord_le1442264292teger2(zero_z413810534nteger, plus_p715165435teger2(A, B)))))), fact_241_add__nonneg__nonneg, 3523). % add_nonneg_nonneg
formula(forall([A : inT, B : inT], implies(pp(ord_less_eq_int2(zero_zero_int, A)), implies(pp(ord_less_eq_int2(zero_zero_int, B)), pp(ord_less_eq_int2(zero_zero_int, plus_plus_int2(A, B)))))), fact_242_add__nonneg__nonneg, 3534). % add_nonneg_nonneg
formula(forall([A : code_integer, B : code_integer], implies(pp(ord_le1687847920teger2(zero_z413810534nteger, A)), implies(pp(ord_le1687847920teger2(zero_z413810534nteger, B)), pp(ord_le1687847920teger2(zero_z413810534nteger, plus_p715165435teger2(A, B)))))), fact_243_add__pos__pos, 3545). % add_pos_pos
formula(forall([A : inT, B : inT], implies(pp(ord_less_int2(zero_zero_int, A)), implies(pp(ord_less_int2(zero_zero_int, B)), pp(ord_less_int2(zero_zero_int, plus_plus_int2(A, B)))))), fact_244_add__pos__pos, 3556). % add_pos_pos
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(zero_zero_nat, A)), implies(pp(ord_less_nat2(zero_zero_nat, B)), pp(ord_less_nat2(zero_zero_nat, plus_plus_nat2(A, B)))))), fact_245_add__pos__pos, 3567). % add_pos_pos
formula(forall([A : inT, B : inT], implies(pp(ord_less_int2(A, zero_zero_int)), implies(pp(ord_less_int2(B, zero_zero_int)), pp(ord_less_int2(plus_plus_int2(A, B), zero_zero_int))))), fact_246_add__neg__neg, 3578). % add_neg_neg
formula(forall([A : naT, B : naT], implies(pp(ord_less_nat2(A, zero_zero_nat)), implies(pp(ord_less_nat2(B, zero_zero_nat)), pp(ord_less_nat2(plus_plus_nat2(A, B), zero_zero_nat))))), fact_247_add__neg__neg, 3589). % add_neg_neg

formula(pp(fTruE), help_pp_2_1_U).
formula(not(pp(fFalsE)), help_pp_1_1_U).
end_of_list.

list_of_formulae(conjectures).
formula(equal(plus_plus_a(x, zero_zero_a), x), conj_0).
end_of_list.

list_of_settings(SPASS).
set_precedence(image_int_int, image_1151633089nteger, ord_le1426714813nteger, ord_le945590961nteger, ord_less_int, ord_less_eq_int, plus_plus_int, plus_p2058578406nteger, ord_less_eq_int2, ord_less_int2, image_nat_nat, ord_le1687847920teger2, ord_le1442264292teger2, plus_p715165434teger1, plus_plus_int1, ord_less_nat, ord_less_eq_nat, plus_plus_nat, plus_plus_literal, ord_less_eq_nat2, minus_minus_nat, ord_less_nat2, plus_plus_int2, suB, plus_p715165435teger2, plus_plus_literal1, plus_plus_nat1, monoid_int, monoid_nat, dvd_dvd_int, dvd_dvd_nat, times_times_int, minus_minus_int, times_times_nat, plus_plus_nat2, comm_monoid_int, comm_monoid_nat, plus_plus_literal2, monoid_Code_integer, numeral_numeral_int, comm_m604335976nteger, dvd_dvd_Code_integer, times_1419655522nteger, minus_1582103350nteger, zero_z413810534nteger, uminus636303014ntegeR, dvd_dv413397790teger2, comm_m138292217teger2, numeral_numeral_int1, monoid_Code_integer2, zero_zero_literal, uminus_uminus_int, comm_monoid_nat2, comm_monoid_int2, zero_zero_nat, zero_zero_int, dvd_dvd_nat2, dvd_dvd_int2, one_one_nat, monoid_nat2, monoid_int2).
end_of_list.

end_problem.
