% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 2.500 --mode=ho-pragmatic -nc --tptp-def-as-rewrite --rewrite-before-cnf=true --mode=ho-competitive --boolean-reasoning=simpl-only --ext-rules=ext-family --ext-rules-max-depth=1 --ho-prim-enum=none --avatar=off --recognize-injectivity=true --ho-elim-leibniz=1 --ho-unif-level=pragmatic-framework --no-max-vars --max-inferences=4 --ho-max-app-projections=1 --ho-max-elims=0 --ho-max-rigid-imitations=2 --ho-max-identifications=0 --ho-unif-max-depth=3 -q "6|prefer-sos|pnrefined(1,1,1,2,2,2,0.5)" -q "6|const|conjecture-relative-var(1.02,l,f)" -q "1|prefer-processed|fifo" -q "1|prefer-non-goals|conjecture-relative-var(1,l,f)" -q "4|prefer-easy-ho|conjecture-relative-var(1.01,s,f)" --select=e-selection7 --ho-choice-inst=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --e-timeout=7 --sine=50 --sine-tolerance=1 --sine-depth-max=2 --sine-depth-min=1 --e-max-derived=64 --sine-ignore-k-most-common-syms=2 --sine-trim-implications=true --e-encode-lambdas=lift --scan-clause-ac=false --lambdasup=0 --kbo-weight-fun=lambda-def-invfreqrank --demod-in-var-args=true --bool-demod=true --lambda-demod=true --e-call-point=0.1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4884484_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:42:54.143
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a)))), [], [isabelle_rank(900)]). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
