% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 2.500 --mode=ho-pragmatic --max-inferences=4 --ho-max-app-projections=1 --ho-max-elims=0 --ho-max-rigid-imitations=2 --ho-max-identifications=0 --ho-unif-max-depth=2 --max-inferences=3 --boolean-reasoning=bool-hoist --bool-select=LO --ext-rules=off --kbo-weight-fun=lambda-def-invfreqrank --ho-prim-enum=none --ho-unif-level=pragmatic-framework -q "1|prefer-sos|conjecture-relative-var(1.01,s,f)" -q "4|const|conjecture-relative-var(1.05,l,f)" -q "1|prefer-processed|fifo" -q "1|prefer-non-goals|conjecture-relative-var(1.02,l,f)" -q "4|prefer-sos|pnrefined(3,2,3,2,2,1.5,2)" --ho-elim-leibniz=1 --ho-fixpoint-decider=true --ho-pattern-decider=true --ho-solid-decider=true --select=e-selection2 --solve-formulas=true --lambdasup=0 --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --e-timeout=3 --e-max-derived=48 --e-encode-lambdas=lift --presaturate=true --prec-gen-fun=invfreq --e-call-point=0.2 --e-auto=true --sine-trim-implications=true /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4769274_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:26.521
% Could-be-implicit typings (1)
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
thf(sy_v_x, type,
    x : a).

% Relevant facts (1)
thf(fact_0_zero__reorient, axiom,
    ((![X : a]: ((zero_zero_a = X) = (X = zero_zero_a)))), [], [isabelle_rank(900)]). % zero_reorient

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ zero_zero_a) = x))).
