% /Applications/Isabelle2025.app/contrib/vampire-4.8/x86_64-darwin/vampire --input_syntax tptp --proof tptp --output_axiom_names on --mode portfolio --schedule snake_slh -t 5 --input_file /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4729480_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:25.339
% Could-be-implicit typings (1)
tff(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (1)
tff(sy_v_P, type,
    p : a > $o).

% Conjectures (1)
tff(conj_0, conjecture,
    ((![X : a]: ((~ (p(X))) | p(X))))).
