% /Applications/Isabelle2025.app/contrib/e-3.1-1/arm64-darwin/eprover --tstp-in --tstp-out --silent --auto-schedule --cpu-limit=5 --proof-object=1 /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4748530_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:26.060
% Could-be-implicit typings (1)
tff(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (3)
tff(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : (a * a) > a).
tff(sy_c_Groups_Ozero__class_Ozero_001tf__a, type,
    zero_zero_a : a).
tff(sy_v_x, type,
    x : a).

% Relevant facts (1)
tff(fact_0_zero__reorient, axiom,
    ((![Xa : a]: ((zero_zero_a = Xa) <=> (Xa = zero_zero_a))))). % zero_reorient

% Conjectures (1)
tff(conj_0, conjecture,
    ((plus_plus_a(x, zero_zero_a) = x))).
