% /Applications/Isabelle2025.app/contrib/vampire-4.8/x86_64-darwin/vampire --input_syntax tptp --proof tptp --output_axiom_names on --mode portfolio --schedule snake_slh -t 5 --input_file /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob4831412_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:40:31.811
% Could-be-implicit typings (3)
tff(ty_t_Set_Oset, type,
    set : $tType > $tType).
tff(ty_t_fun, type,
    fun : ($tType * $tType) > $tType).
tff(ty_tf_a, type,
    a : $tType).

% Explicit typings (52)
tff(sy_cl_Groups_Oplus, type,
    plus : !>[A : $tType]: $o).
tff(sy_cl_HOL_Otype, type,
    type : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ozero, type,
    zero : !>[A : $tType]: $o).
tff(sy_cl_Fields_Ofield, type,
    field : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Oord, type,
    ord : !>[A : $tType]: $o).
tff(sy_cl_Num_Oneg__numeral, type,
    neg_numeral : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Oorder, type,
    order : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ogroup__add, type,
    group_add : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Ono__bot, type,
    no_bot : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Ono__top, type,
    no_top : !>[A : $tType]: $o).
tff(sy_cl_Groups_Omonoid__add, type,
    monoid_add : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Opreorder, type,
    preorder : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Owellorder, type,
    wellorder : !>[A : $tType]: $o).
tff(sy_cl_Fields_Odivision__ring, type,
    division_ring : !>[A : $tType]: $o).
tff(sy_cl_Groups_Osemigroup__add, type,
    semigroup_add : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Odense__order, type,
    dense_order : !>[A : $tType]: $o).
tff(sy_cl_Rings_Olinordered__idom, type,
    linordered_idom : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocomm__monoid__add, type,
    comm_monoid_add : !>[A : $tType]: $o).
tff(sy_cl_Fields_Olinordered__field, type,
    linordered_field : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oab__semigroup__add, type,
    ab_semigroup_add : !>[A : $tType]: $o).
tff(sy_cl_Orderings_Odense__linorder, type,
    dense_linorder : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocancel__semigroup__add, type,
    cancel_semigroup_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocancel__comm__monoid__add, type,
    cancel1352612707id_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Olinordered__ab__group__add, type,
    linord219039673up_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__comm__monoid__add, type,
    ordere216010020id_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__ab__semigroup__add, type,
    ordere779506340up_add : !>[A : $tType]: $o).
tff(sy_cl_Rings_Olinordered__nonzero__semiring, type,
    linord1659791738miring : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocanonically__ordered__monoid__add, type,
    canoni770627133id_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__cancel__comm__monoid__add, type,
    ordere1818651114id_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ostrict__ordered__comm__monoid__add, type,
    strict797366125id_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__ab__semigroup__add__imp__le, type,
    ordere236663937imp_le : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__cancel__ab__semigroup__add, type,
    ordere223160158up_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ostrict__ordered__ab__semigroup__add, type,
    strict2144017051up_add : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__ab__semigroup__monoid__add__imp__le, type,
    ordere516151231imp_le : !>[A : $tType]: $o).
tff(sy_cl_Semiring__Normalization_Ocomm__semiring__1__cancel__crossproduct, type,
    semiri456707255roduct : !>[A : $tType]: $o).
tff(sy_cl_Conditionally__Complete__Lattices_Oconditionally__complete__linorder, type,
    condit1037483654norder : !>[A : $tType]: $o).
tff(sy_c_ATP_058Lamp__a____, type,
    aTP_Lamp_a : !>[A : $tType, B : $tType]: (A > B)).
tff(sy_c_Fields_Oinverse__class_Oinverse, type,
    inverse_inverse : !>[A : $tType]: (A > A)).
tff(sy_c_Groups_Ocomm__monoid, type,
    comm_monoid : !>[A : $tType]: ((fun(A, fun(A, A)) * A) > $o)).
tff(sy_c_Groups_Ocomm__monoid__axioms, type,
    comm_monoid_axioms : !>[A : $tType]: ((fun(A, fun(A, A)) * A) > $o)).
tff(sy_c_Groups_Omonoid, type,
    monoid : !>[A : $tType]: ((fun(A, fun(A, A)) * A) > $o)).
tff(sy_c_Groups_Omonoid__axioms, type,
    monoid_axioms : !>[A : $tType]: ((fun(A, fun(A, A)) * A) > $o)).
tff(sy_c_Groups_Oplus__class_Oplus, type,
    plus_plus : !>[A : $tType]: fun(A, fun(A, A))).
tff(sy_c_Groups_Ozero__class_Ozero, type,
    zero_zero : !>[A : $tType]: A).
tff(sy_c_Orderings_Oord__class_Oless, type,
    ord_less : !>[A : $tType]: ((A * A) > $o)).
tff(sy_c_Orderings_Oord__class_Oless__eq, type,
    ord_less_eq : !>[A : $tType]: ((A * A) > $o)).
tff(sy_c_Orderings_Oorder__class_OGreatest, type,
    order_Greatest : !>[A : $tType]: (fun(A, $o) > A)).
tff(sy_c_Set_OCollect, type,
    collect : !>[A : $tType]: (fun(A, $o) > set(A))).
tff(sy_c_aa, type,
    aa : !>[A : $tType, B : $tType]: ((fun(A, B) * A) > B)).
tff(sy_c_member, type,
    member : !>[A : $tType]: ((A * set(A)) > $o)).
tff(sy_v_x, type,
    x : a).

% Relevant facts (256)
tff(fact_0_add_Oright__neutral, axiom,
    ((![B : $tType]: (monoid_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), zero_zero(B)) = A2)))))). % add.right_neutral
tff(fact_1_double__zero__sym, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: ((zero_zero(B) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2)) <=> (A2 = zero_zero(B)))))))). % double_zero_sym
tff(fact_2_add__cancel__left__left, axiom,
    ((![B : $tType]: (cancel1352612707id_add(B) => (![B2 : B, A2 : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2) = A2) <=> (B2 = zero_zero(B)))))))). % add_cancel_left_left
tff(fact_3_add__cancel__left__right, axiom,
    ((![B : $tType]: (cancel1352612707id_add(B) => (![A2 : B, B2 : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2) = A2) <=> (B2 = zero_zero(B)))))))). % add_cancel_left_right
tff(fact_4_add__cancel__right__left, axiom,
    ((![B : $tType]: (cancel1352612707id_add(B) => (![A2 : B, B2 : B]: ((A2 = aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2)) <=> (B2 = zero_zero(B)))))))). % add_cancel_right_left
tff(fact_5_add__cancel__right__right, axiom,
    ((![B : $tType]: (cancel1352612707id_add(B) => (![A2 : B, B2 : B]: ((A2 = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)) <=> (B2 = zero_zero(B)))))))). % add_cancel_right_right
tff(fact_6_add__eq__0__iff__both__eq__0, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![Xa : B, Y : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), Xa), Y) = zero_zero(B)) <=> ((Xa = zero_zero(B)) & (Y = zero_zero(B))))))))). % add_eq_0_iff_both_eq_0
tff(fact_7_zero__eq__add__iff__both__eq__0, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![Xa : B, Y : B]: ((zero_zero(B) = aa(B, B, aa(B, fun(B, B), plus_plus(B), Xa), Y)) <=> ((Xa = zero_zero(B)) & (Y = zero_zero(B))))))))). % zero_eq_add_iff_both_eq_0
tff(fact_8_add__0, axiom,
    ((![B : $tType]: (monoid_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), zero_zero(B)), A2) = A2)))))). % add_0
tff(fact_9_double__eq__0__iff, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2) = zero_zero(B)) <=> (A2 = zero_zero(B)))))))). % double_eq_0_iff
tff(fact_10_add__left__cancel, axiom,
    ((![B : $tType]: (cancel_semigroup_add(B) => (![A2 : B, B2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C)) <=> (B2 = C))))))). % add_left_cancel
tff(fact_11_add__right__cancel, axiom,
    ((![B : $tType]: (cancel_semigroup_add(B) => (![B2 : B, A2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2)) <=> (B2 = C))))))). % add_right_cancel
tff(fact_12_zero__reorient, axiom,
    ((![B : $tType]: (zero(B) => (![Xa : B]: ((zero_zero(B) = Xa) <=> (Xa = zero_zero(B)))))))). % zero_reorient
tff(fact_13_add__right__imp__eq, axiom,
    ((![B : $tType]: (cancel_semigroup_add(B) => (![B2 : B, A2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2)) => (B2 = C))))))). % add_right_imp_eq
tff(fact_14_add__left__imp__eq, axiom,
    ((![B : $tType]: (cancel_semigroup_add(B) => (![A2 : B, B2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C)) => (B2 = C))))))). % add_left_imp_eq
tff(fact_15_add_Oleft__commute, axiom,
    ((![B : $tType]: (ab_semigroup_add(B) => (![B2 : B, A2 : B, C : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C)) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % add.left_commute
tff(fact_16_add_Ocommute, axiom,
    ((![B : $tType]: (ab_semigroup_add(B) => (![A2 : B, B2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2))))))). % add.commute
tff(fact_17_add_Oright__cancel, axiom,
    ((![B : $tType]: (group_add(B) => (![B2 : B, A2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2)) <=> (B2 = C))))))). % add.right_cancel
tff(fact_18_add_Oleft__cancel, axiom,
    ((![B : $tType]: (group_add(B) => (![A2 : B, B2 : B, C : B]: ((aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C)) <=> (B2 = C))))))). % add.left_cancel
tff(fact_19_add_Oassoc, axiom,
    ((![B : $tType]: (semigroup_add(B) => (![A2 : B, B2 : B, C : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)), C) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % add.assoc
tff(fact_20_group__cancel_Oadd2, axiom,
    ((![B : $tType]: (comm_monoid_add(B) => (![B3 : B, K : B, B2 : B, A2 : B]: ((B3 = aa(B, B, aa(B, fun(B, B), plus_plus(B), K), B2)) => (aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B3) = aa(B, B, aa(B, fun(B, B), plus_plus(B), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % group_cancel.add2
tff(fact_21_group__cancel_Oadd1, axiom,
    ((![B : $tType]: (comm_monoid_add(B) => (![A3 : B, K : B, A2 : B, B2 : B]: ((A3 = aa(B, B, aa(B, fun(B, B), plus_plus(B), K), A2)) => (aa(B, B, aa(B, fun(B, B), plus_plus(B), A3), B2) = aa(B, B, aa(B, fun(B, B), plus_plus(B), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % group_cancel.add1
tff(fact_22_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![I : B, J : B, K : B, L : B]: (((I = J) & (K = L)) => (aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K) = aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_semiring(4)
tff(fact_23_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![B : $tType]: (ab_semigroup_add(B) => (![A2 : B, B2 : B, C : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)), C) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % ab_semigroup_add_class.add_ac(1)
tff(fact_24_add_Ogroup__left__neutral, axiom,
    ((![B : $tType]: (group_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), zero_zero(B)), A2) = A2)))))). % add.group_left_neutral
tff(fact_25_add_Ocomm__neutral, axiom,
    ((![B : $tType]: (comm_monoid_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), zero_zero(B)) = A2)))))). % add.comm_neutral
tff(fact_26_comm__monoid__add__class_Oadd__0, axiom,
    ((![B : $tType]: (comm_monoid_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), zero_zero(B)), A2) = A2)))))). % comm_monoid_add_class.add_0
tff(fact_27_verit__sum__simplify, axiom,
    ((![B : $tType]: (cancel1352612707id_add(B) => (![A2 : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), zero_zero(B)) = A2)))))). % verit_sum_simplify
tff(fact_28_add__0__iff, axiom,
    ((![B : $tType]: (semiri456707255roduct(B) => (![B2 : B, A2 : B]: ((B2 = aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2)) <=> (A2 = zero_zero(B)))))))). % add_0_iff
tff(fact_29_is__num__normalize_I1_J, axiom,
    ((![B : $tType]: (neg_numeral(B) => (![A2 : B, B2 : B, C : B]: (aa(B, B, aa(B, fun(B, B), plus_plus(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)), C) = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % is_num_normalize(1)
tff(fact_30_add_Omonoid__axioms, axiom,
    ((![B : $tType]: (monoid_add(B) => monoid(B, plus_plus(B), zero_zero(B)))))). % add.monoid_axioms
tff(fact_31_add_Ocomm__monoid__axioms, axiom,
    ((![B : $tType]: (comm_monoid_add(B) => comm_monoid(B, plus_plus(B), zero_zero(B)))))). % add.comm_monoid_axioms
tff(fact_32_zero__le__double__add__iff__zero__le__single__add, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: (ord_less_eq(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2)) <=> ord_less_eq(B, zero_zero(B), A2))))))). % zero_le_double_add_iff_zero_le_single_add
tff(fact_33_double__add__le__zero__iff__single__add__le__zero, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2), zero_zero(B)) <=> ord_less_eq(B, A2, zero_zero(B)))))))). % double_add_le_zero_iff_single_add_le_zero
tff(fact_34_le__add__same__cancel2, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2)) <=> ord_less_eq(B, zero_zero(B), B2))))))). % le_add_same_cancel2
tff(fact_35_le__add__same__cancel1, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)) <=> ord_less_eq(B, zero_zero(B), B2))))))). % le_add_same_cancel1
tff(fact_36_add__le__same__cancel2, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), B2) <=> ord_less_eq(B, A2, zero_zero(B)))))))). % add_le_same_cancel2
tff(fact_37_add__le__same__cancel1, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![B2 : B, A2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2), B2) <=> ord_less_eq(B, A2, zero_zero(B)))))))). % add_le_same_cancel1
tff(fact_38_zero__less__double__add__iff__zero__less__single__add, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: (ord_less(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2)) <=> ord_less(B, zero_zero(B), A2))))))). % zero_less_double_add_iff_zero_less_single_add
tff(fact_39_le__zero__eq, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![N : B]: (ord_less_eq(B, N, zero_zero(B)) <=> (N = zero_zero(B)))))))). % le_zero_eq
tff(fact_40_not__gr__zero, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![N : B]: ((~ (ord_less(B, zero_zero(B), N))) <=> (N = zero_zero(B)))))))). % not_gr_zero
tff(fact_41_add__le__cancel__left, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![C : B, A2 : B, B2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)) <=> ord_less_eq(B, A2, B2))))))). % add_le_cancel_left
tff(fact_42_add__le__cancel__right, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![A2 : B, C : B, B2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)) <=> ord_less_eq(B, A2, B2))))))). % add_le_cancel_right
tff(fact_43_add__less__cancel__left, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![C : B, A2 : B, B2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)) <=> ord_less(B, A2, B2))))))). % add_less_cancel_left
tff(fact_44_mem__Collect__eq, axiom,
    ((![B : $tType]: (![A2 : B, P : fun(B, $o)]: (member(B, A2, collect(B, P)) <=> aa(B, $o, P, A2)))))). % mem_Collect_eq
tff(fact_45_Collect__mem__eq, axiom,
    ((![B : $tType]: (![A3 : set(B)]: (collect(B, aTP_Lamp_a(set(B), fun(B, $o), A3)) = A3))))). % Collect_mem_eq
tff(fact_46_Collect__cong, axiom,
    ((![B : $tType]: (![P : fun(B, $o), Q : fun(B, $o)]: ((![X : B]: (aa(B, $o, P, X) <=> aa(B, $o, Q, X))) => (collect(B, P) = collect(B, Q))))))). % Collect_cong
tff(fact_47_ext, axiom,
    ((![C2 : $tType, B : $tType]: (![F : fun(B, C2), G : fun(B, C2)]: ((![X : B]: (aa(B, C2, F, X) = aa(B, C2, G, X))) => (F = G)))))). % ext
tff(fact_48_add__less__cancel__right, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![A2 : B, C : B, B2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)) <=> ord_less(B, A2, B2))))))). % add_less_cancel_right
tff(fact_49_add__less__same__cancel1, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![B2 : B, A2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2), B2) <=> ord_less(B, A2, zero_zero(B)))))))). % add_less_same_cancel1
tff(fact_50_add__less__same__cancel2, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), B2) <=> ord_less(B, A2, zero_zero(B)))))))). % add_less_same_cancel2
tff(fact_51_less__add__same__cancel1, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2)) <=> ord_less(B, zero_zero(B), B2))))))). % less_add_same_cancel1
tff(fact_52_less__add__same__cancel2, axiom,
    ((![B : $tType]: (ordere516151231imp_le(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), A2)) <=> ord_less(B, zero_zero(B), B2))))))). % less_add_same_cancel2
tff(fact_53_double__add__less__zero__iff__single__add__less__zero, axiom,
    ((![B : $tType]: (linord219039673up_add(B) => (![A2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), A2), zero_zero(B)) <=> ord_less(B, A2, zero_zero(B)))))))). % double_add_less_zero_iff_single_add_less_zero
tff(fact_54_monoid_Oleft__neutral, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B, A2 : B]: (monoid(B, F, Z) => (aa(B, B, aa(B, fun(B, B), F, Z), A2) = A2)))))). % monoid.left_neutral
tff(fact_55_monoid_Oright__neutral, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B, A2 : B]: (monoid(B, F, Z) => (aa(B, B, aa(B, fun(B, B), F, A2), Z) = A2)))))). % monoid.right_neutral
tff(fact_56_comm__monoid_Ocomm__neutral, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B, A2 : B]: (comm_monoid(B, F, Z) => (aa(B, B, aa(B, fun(B, B), F, A2), Z) = A2)))))). % comm_monoid.comm_neutral
tff(fact_57_verit__la__disequality, axiom,
    ((![B : $tType]: (linorder(B) => (![A2 : B, B2 : B]: ((A2 = B2) | ((~ (ord_less_eq(B, A2, B2))) | (~ (ord_less_eq(B, B2, A2)))))))))). % verit_la_disequality
tff(fact_58_verit__comp__simplify1_I1_J, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B]: (~ (ord_less(B, A2, A2)))))))). % verit_comp_simplify1(1)
tff(fact_59_verit__comp__simplify1_I2_J, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B]: ord_less_eq(B, A2, A2)))))). % verit_comp_simplify1(2)
tff(fact_60_verit__comp__simplify1_I3_J, axiom,
    ((![B : $tType]: (linorder(B) => (![B4 : B, A4 : B]: ((~ (ord_less_eq(B, B4, A4))) <=> ord_less(B, A4, B4))))))). % verit_comp_simplify1(3)
tff(fact_61_add__less__le__mono, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![A2 : B, B2 : B, C : B, D : B]: (ord_less(B, A2, B2) => (ord_less_eq(B, C, D) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), D))))))))). % add_less_le_mono
tff(fact_62_add__le__less__mono, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![A2 : B, B2 : B, C : B, D : B]: (ord_less_eq(B, A2, B2) => (ord_less(B, C, D) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), D))))))))). % add_le_less_mono
tff(fact_63_add__mono__thms__linordered__field_I3_J, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less(B, I, J) & ord_less_eq(B, K, L)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_field(3)
tff(fact_64_add__mono__thms__linordered__field_I4_J, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less_eq(B, I, J) & ord_less(B, K, L)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_field(4)
tff(fact_65_less__numeral__extra_I3_J, axiom,
    ((![B : $tType]: (linord1659791738miring(B) => (~ (ord_less(B, zero_zero(B), zero_zero(B)))))))). % less_numeral_extra(3)
tff(fact_66_le__numeral__extra_I3_J, axiom,
    ((![B : $tType]: (linord1659791738miring(B) => ord_less_eq(B, zero_zero(B), zero_zero(B)))))). % le_numeral_extra(3)
tff(fact_67_add__neg__nonpos, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, zero_zero(B)) => (ord_less_eq(B, B2, zero_zero(B)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), zero_zero(B))))))))). % add_neg_nonpos
tff(fact_68_add__nonneg__pos, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, zero_zero(B), A2) => (ord_less(B, zero_zero(B), B2) => ord_less(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % add_nonneg_pos
tff(fact_69_add__nonpos__neg, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, zero_zero(B)) => (ord_less(B, B2, zero_zero(B)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), zero_zero(B))))))))). % add_nonpos_neg
tff(fact_70_add__pos__nonneg, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less(B, zero_zero(B), A2) => (ord_less_eq(B, zero_zero(B), B2) => ord_less(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % add_pos_nonneg
tff(fact_71_add__strict__increasing, axiom,
    ((![B : $tType]: (ordere1818651114id_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, zero_zero(B), A2) => (ord_less_eq(B, B2, C) => ord_less(B, B2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C))))))))). % add_strict_increasing
tff(fact_72_add__strict__increasing2, axiom,
    ((![B : $tType]: (ordere1818651114id_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, zero_zero(B), A2) => (ord_less(B, B2, C) => ord_less(B, B2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C))))))))). % add_strict_increasing2
tff(fact_73_gr__zeroI, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![N : B]: ((N != zero_zero(B)) => ord_less(B, zero_zero(B), N))))))). % gr_zeroI
tff(fact_74_not__less__zero, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![N : B]: (~ (ord_less(B, N, zero_zero(B))))))))). % not_less_zero
tff(fact_75_gr__implies__not__zero, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![M : B, N : B]: (ord_less(B, M, N) => (N != zero_zero(B)))))))). % gr_implies_not_zero
tff(fact_76_zero__less__iff__neq__zero, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![N : B]: (ord_less(B, zero_zero(B), N) <=> (N != zero_zero(B)))))))). % zero_less_iff_neq_zero
tff(fact_77_zero__le, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![Xa : B]: ord_less_eq(B, zero_zero(B), Xa)))))). % zero_le
tff(fact_78_add__mono__thms__linordered__field_I5_J, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less(B, I, J) & ord_less(B, K, L)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_field(5)
tff(fact_79_add__mono__thms__linordered__field_I2_J, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![I : B, J : B, K : B, L : B]: (((I = J) & ord_less(B, K, L)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_field(2)
tff(fact_80_add__mono__thms__linordered__field_I1_J, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less(B, I, J) & (K = L)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_field(1)
tff(fact_81_add__strict__mono, axiom,
    ((![B : $tType]: (strict2144017051up_add(B) => (![A2 : B, B2 : B, C : B, D : B]: (ord_less(B, A2, B2) => (ord_less(B, C, D) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), D))))))))). % add_strict_mono
tff(fact_82_add__strict__left__mono, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, A2, B2) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)))))))). % add_strict_left_mono
tff(fact_83_add__strict__right__mono, axiom,
    ((![B : $tType]: (ordere223160158up_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, A2, B2) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % add_strict_right_mono
tff(fact_84_add__less__imp__less__left, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![C : B, A2 : B, B2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)) => ord_less(B, A2, B2))))))). % add_less_imp_less_left
tff(fact_85_add__less__imp__less__right, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![A2 : B, C : B, B2 : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)) => ord_less(B, A2, B2))))))). % add_less_imp_less_right
tff(fact_86_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less_eq(B, I, J) & (K = L)) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_semiring(3)
tff(fact_87_add__mono__thms__linordered__semiring_I2_J, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![I : B, J : B, K : B, L : B]: (((I = J) & ord_less_eq(B, K, L)) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_semiring(2)
tff(fact_88_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![I : B, J : B, K : B, L : B]: ((ord_less_eq(B, I, J) & ord_less_eq(B, K, L)) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), I), K), aa(B, B, aa(B, fun(B, B), plus_plus(B), J), L)))))))). % add_mono_thms_linordered_semiring(1)
tff(fact_89_add__mono, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![A2 : B, B2 : B, C : B, D : B]: (ord_less_eq(B, A2, B2) => (ord_less_eq(B, C, D) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), D))))))))). % add_mono
tff(fact_90_add__left__mono, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, A2, B2) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)))))))). % add_left_mono
tff(fact_91_less__eqE, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, B2) => (~ ((![C3 : B]: (B2 != aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C3))))))))))). % less_eqE
tff(fact_92_add__right__mono, axiom,
    ((![B : $tType]: (ordere779506340up_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, A2, B2) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)))))))). % add_right_mono
tff(fact_93_le__iff__add, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, B2) <=> (?[C4 : B]: (B2 = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C4))))))))). % le_iff_add
tff(fact_94_add__le__imp__le__left, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![C : B, A2 : B, B2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), C), A2), aa(B, B, aa(B, fun(B, B), plus_plus(B), C), B2)) => ord_less_eq(B, A2, B2))))))). % add_le_imp_le_left
tff(fact_95_add__le__imp__le__right, axiom,
    ((![B : $tType]: (ordere236663937imp_le(B) => (![A2 : B, C : B, B2 : B]: (ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), aa(B, B, aa(B, fun(B, B), plus_plus(B), B2), C)) => ord_less_eq(B, A2, B2))))))). % add_le_imp_le_right
tff(fact_96_add__neg__neg, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, zero_zero(B)) => (ord_less(B, B2, zero_zero(B)) => ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), zero_zero(B))))))))). % add_neg_neg
tff(fact_97_add__pos__pos, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less(B, zero_zero(B), A2) => (ord_less(B, zero_zero(B), B2) => ord_less(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % add_pos_pos
tff(fact_98_canonically__ordered__monoid__add__class_OlessE, axiom,
    ((![B : $tType]: (canoni770627133id_add(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (~ ((![C3 : B]: ((B2 = aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C3)) => (C3 = zero_zero(B)))))))))))). % canonically_ordered_monoid_add_class.lessE
tff(fact_99_pos__add__strict, axiom,
    ((![B : $tType]: (strict797366125id_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, zero_zero(B), A2) => (ord_less(B, B2, C) => ord_less(B, B2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C))))))))). % pos_add_strict
tff(fact_100_add__decreasing, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, C : B, B2 : B]: (ord_less_eq(B, A2, zero_zero(B)) => (ord_less_eq(B, C, B2) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), B2)))))))). % add_decreasing
tff(fact_101_add__increasing, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, zero_zero(B), A2) => (ord_less_eq(B, B2, C) => ord_less_eq(B, B2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C))))))))). % add_increasing
tff(fact_102_add__decreasing2, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![C : B, A2 : B, B2 : B]: (ord_less_eq(B, C, zero_zero(B)) => (ord_less_eq(B, A2, B2) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C), B2)))))))). % add_decreasing2
tff(fact_103_add__increasing2, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![C : B, B2 : B, A2 : B]: (ord_less_eq(B, zero_zero(B), C) => (ord_less_eq(B, B2, A2) => ord_less_eq(B, B2, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), C))))))))). % add_increasing2
tff(fact_104_add__nonneg__nonneg, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, zero_zero(B), A2) => (ord_less_eq(B, zero_zero(B), B2) => ord_less_eq(B, zero_zero(B), aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2))))))))). % add_nonneg_nonneg
tff(fact_105_add__nonpos__nonpos, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, zero_zero(B)) => (ord_less_eq(B, B2, zero_zero(B)) => ord_less_eq(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), A2), B2), zero_zero(B))))))))). % add_nonpos_nonpos
tff(fact_106_add__nonneg__eq__0__iff, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![Xa : B, Y : B]: (ord_less_eq(B, zero_zero(B), Xa) => (ord_less_eq(B, zero_zero(B), Y) => ((aa(B, B, aa(B, fun(B, B), plus_plus(B), Xa), Y) = zero_zero(B)) <=> ((Xa = zero_zero(B)) & (Y = zero_zero(B))))))))))). % add_nonneg_eq_0_iff
tff(fact_107_add__nonpos__eq__0__iff, axiom,
    ((![B : $tType]: (ordere216010020id_add(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, zero_zero(B)) => (ord_less_eq(B, Y, zero_zero(B)) => ((aa(B, B, aa(B, fun(B, B), plus_plus(B), Xa), Y) = zero_zero(B)) <=> ((Xa = zero_zero(B)) & (Y = zero_zero(B))))))))))). % add_nonpos_eq_0_iff
tff(fact_108_field__le__epsilon, axiom,
    ((![B : $tType]: (linordered_field(B) => (![Xa : B, Y : B]: ((![E : B]: (ord_less(B, zero_zero(B), E) => ord_less_eq(B, Xa, aa(B, B, aa(B, fun(B, B), plus_plus(B), Y), E)))) => ord_less_eq(B, Xa, Y))))))). % field_le_epsilon
tff(fact_109_add__less__zeroD, axiom,
    ((![B : $tType]: (linordered_idom(B) => (![Xa : B, Y : B]: (ord_less(B, aa(B, B, aa(B, fun(B, B), plus_plus(B), Xa), Y), zero_zero(B)) => (ord_less(B, Xa, zero_zero(B)) | ord_less(B, Y, zero_zero(B))))))))). % add_less_zeroD
tff(fact_110_dual__order_Orefl, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B]: ord_less_eq(B, A2, A2)))))). % dual_order.refl
tff(fact_111_order__refl, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B]: ord_less_eq(B, Xa, Xa)))))). % order_refl
tff(fact_112_order__le__imp__less__or__eq, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) => (ord_less(B, Xa, Y) | (Xa = Y)))))))). % order_le_imp_less_or_eq
tff(fact_113_linorder__le__less__linear, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) | ord_less(B, Y, Xa))))))). % linorder_le_less_linear
tff(fact_114_order__less__le__subst2, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less(B, A2, B2) => (ord_less_eq(C2, aa(B, C2, F, B2), C) => ((![X : B, Y2 : B]: (ord_less(B, X, Y2) => ord_less(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less(C2, aa(B, C2, F, A2), C))))))))). % order_less_le_subst2
tff(fact_115_order__less__le__subst1, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: (ord_less(B, A2, aa(C2, B, F, B2)) => (ord_less_eq(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less_eq(C2, X, Y2) => ord_less_eq(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less(B, A2, aa(C2, B, F, C)))))))))). % order_less_le_subst1
tff(fact_116_order__le__less__subst2, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less_eq(B, A2, B2) => (ord_less(C2, aa(B, C2, F, B2), C) => ((![X : B, Y2 : B]: (ord_less_eq(B, X, Y2) => ord_less_eq(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less(C2, aa(B, C2, F, A2), C))))))))). % order_le_less_subst2
tff(fact_117_order__le__less__subst1, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: (ord_less_eq(B, A2, aa(C2, B, F, B2)) => (ord_less(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less(C2, X, Y2) => ord_less(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less(B, A2, aa(C2, B, F, C)))))))))). % order_le_less_subst1
tff(fact_118_order__less__le__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B, Z : B]: (ord_less(B, Xa, Y) => (ord_less_eq(B, Y, Z) => ord_less(B, Xa, Z)))))))). % order_less_le_trans
tff(fact_119_nle__le, axiom,
    ((![B : $tType]: (linorder(B) => (![A2 : B, B2 : B]: ((~ (ord_less_eq(B, A2, B2))) <=> (ord_less_eq(B, B2, A2) & (B2 != A2)))))))). % nle_le
tff(fact_120_le__cases3, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B, Z : B]: ((ord_less_eq(B, Xa, Y) => (~ (ord_less_eq(B, Y, Z)))) => ((ord_less_eq(B, Y, Xa) => (~ (ord_less_eq(B, Xa, Z)))) => ((ord_less_eq(B, Xa, Z) => (~ (ord_less_eq(B, Z, Y)))) => ((ord_less_eq(B, Z, Y) => (~ (ord_less_eq(B, Y, Xa)))) => ((ord_less_eq(B, Y, Z) => (~ (ord_less_eq(B, Z, Xa)))) => (~ ((ord_less_eq(B, Z, Xa) => (~ (ord_less_eq(B, Xa, Y)))))))))))))))). % le_cases3
tff(fact_121_order__class_Oorder__eq__iff, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: ((Xa = Y) <=> (ord_less_eq(B, Xa, Y) & ord_less_eq(B, Y, Xa)))))))). % order_class.order_eq_iff
tff(fact_122_ord__eq__le__trans, axiom,
    ((![B : $tType]: (ord(B) => (![A2 : B, B2 : B, C : B]: ((A2 = B2) => (ord_less_eq(B, B2, C) => ord_less_eq(B, A2, C)))))))). % ord_eq_le_trans
tff(fact_123_ord__le__eq__trans, axiom,
    ((![B : $tType]: (ord(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, A2, B2) => ((B2 = C) => ord_less_eq(B, A2, C)))))))). % ord_le_eq_trans
tff(fact_124_order__antisym, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) => (ord_less_eq(B, Y, Xa) => (Xa = Y)))))))). % order_antisym
tff(fact_125_order_Otrans, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, A2, B2) => (ord_less_eq(B, B2, C) => ord_less_eq(B, A2, C)))))))). % order.trans
tff(fact_126_order__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B, Z : B]: (ord_less_eq(B, Xa, Y) => (ord_less_eq(B, Y, Z) => ord_less_eq(B, Xa, Z)))))))). % order_trans
tff(fact_127_linorder__wlog, axiom,
    ((![B : $tType]: (linorder(B) => (![P : fun(B, fun(B, $o)), A2 : B, B2 : B]: ((![A5 : B, B5 : B]: (ord_less_eq(B, A5, B5) => aa(B, $o, aa(B, fun(B, $o), P, A5), B5))) => ((![A5 : B, B5 : B]: (aa(B, $o, aa(B, fun(B, $o), P, B5), A5) => aa(B, $o, aa(B, fun(B, $o), P, A5), B5))) => aa(B, $o, aa(B, fun(B, $o), P, A2), B2)))))))). % linorder_wlog
tff(fact_128_dual__order_Oeq__iff, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: ((A2 = B2) <=> (ord_less_eq(B, B2, A2) & ord_less_eq(B, A2, B2)))))))). % dual_order.eq_iff
tff(fact_129_dual__order_Oantisym, axiom,
    ((![B : $tType]: (order(B) => (![B2 : B, A2 : B]: (ord_less_eq(B, B2, A2) => (ord_less_eq(B, A2, B2) => (A2 = B2)))))))). % dual_order.antisym
tff(fact_130_dual__order_Otrans, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B, C : B]: (ord_less_eq(B, B2, A2) => (ord_less_eq(B, C, B2) => ord_less_eq(B, C, A2)))))))). % dual_order.trans
tff(fact_131_antisym, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, B2) => (ord_less_eq(B, B2, A2) => (A2 = B2)))))))). % antisym
tff(fact_132_le__funD, axiom,
    ((![C2 : $tType, B : $tType]: (ord(C2) => (![F : fun(B, C2), G : fun(B, C2), Xa : B]: (ord_less_eq(fun(B, C2), F, G) => ord_less_eq(C2, aa(B, C2, F, Xa), aa(B, C2, G, Xa)))))))). % le_funD
tff(fact_133_le__funE, axiom,
    ((![C2 : $tType, B : $tType]: (ord(C2) => (![F : fun(B, C2), G : fun(B, C2), Xa : B]: (ord_less_eq(fun(B, C2), F, G) => ord_less_eq(C2, aa(B, C2, F, Xa), aa(B, C2, G, Xa)))))))). % le_funE
tff(fact_134_le__funI, axiom,
    ((![C2 : $tType, B : $tType]: (ord(C2) => (![F : fun(B, C2), G : fun(B, C2)]: ((![X : B]: ord_less_eq(C2, aa(B, C2, F, X), aa(B, C2, G, X))) => ord_less_eq(fun(B, C2), F, G))))))). % le_funI
tff(fact_135_le__fun__def, axiom,
    ((![C2 : $tType, B : $tType]: (ord(C2) => (![F : fun(B, C2), G : fun(B, C2)]: (ord_less_eq(fun(B, C2), F, G) <=> (![X2 : B]: ord_less_eq(C2, aa(B, C2, F, X2), aa(B, C2, G, X2))))))))). % le_fun_def
tff(fact_136_Orderings_Oorder__eq__iff, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: ((A2 = B2) <=> (ord_less_eq(B, A2, B2) & ord_less_eq(B, B2, A2)))))))). % Orderings.order_eq_iff
tff(fact_137_order__subst1, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: (ord_less_eq(B, A2, aa(C2, B, F, B2)) => (ord_less_eq(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less_eq(C2, X, Y2) => ord_less_eq(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less_eq(B, A2, aa(C2, B, F, C)))))))))). % order_subst1
tff(fact_138_order__subst2, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less_eq(B, A2, B2) => (ord_less_eq(C2, aa(B, C2, F, B2), C) => ((![X : B, Y2 : B]: (ord_less_eq(B, X, Y2) => ord_less_eq(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less_eq(C2, aa(B, C2, F, A2), C))))))))). % order_subst2
tff(fact_139_order__eq__refl, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: ((Xa = Y) => ord_less_eq(B, Xa, Y))))))). % order_eq_refl
tff(fact_140_linorder__linear, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) | ord_less_eq(B, Y, Xa))))))). % linorder_linear
tff(fact_141_ord__eq__le__subst, axiom,
    ((![B : $tType, C2 : $tType]: ((ord(C2) & ord(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: ((A2 = aa(C2, B, F, B2)) => (ord_less_eq(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less_eq(C2, X, Y2) => ord_less_eq(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less_eq(B, A2, aa(C2, B, F, C)))))))))). % ord_eq_le_subst
tff(fact_142_ord__le__eq__subst, axiom,
    ((![B : $tType, C2 : $tType]: ((ord(C2) & ord(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less_eq(B, A2, B2) => ((aa(B, C2, F, B2) = C) => ((![X : B, Y2 : B]: (ord_less_eq(B, X, Y2) => ord_less_eq(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less_eq(C2, aa(B, C2, F, A2), C))))))))). % ord_le_eq_subst
tff(fact_143_linorder__le__cases, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less_eq(B, Xa, Y))) => ord_less_eq(B, Y, Xa))))))). % linorder_le_cases
tff(fact_144_order__antisym__conv, axiom,
    ((![B : $tType]: (order(B) => (![Y : B, Xa : B]: (ord_less_eq(B, Y, Xa) => (ord_less_eq(B, Xa, Y) <=> (Xa = Y)))))))). % order_antisym_conv
tff(fact_145_lt__ex, axiom,
    ((![B : $tType]: (no_bot(B) => (![Xa : B]: (?[Y2 : B]: ord_less(B, Y2, Xa))))))). % lt_ex
tff(fact_146_gt__ex, axiom,
    ((![B : $tType]: (no_top(B) => (![Xa : B]: (?[X_1 : B]: ord_less(B, Xa, X_1))))))). % gt_ex
tff(fact_147_dense, axiom,
    ((![B : $tType]: (dense_order(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (?[Z2 : B]: (ord_less(B, Xa, Z2) & ord_less(B, Z2, Y))))))))). % dense
tff(fact_148_less__imp__neq, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (Xa != Y))))))). % less_imp_neq
tff(fact_149_order_Oasym, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (~ (ord_less(B, B2, A2))))))))). % order.asym
tff(fact_150_ord__eq__less__trans, axiom,
    ((![B : $tType]: (ord(B) => (![A2 : B, B2 : B, C : B]: ((A2 = B2) => (ord_less(B, B2, C) => ord_less(B, A2, C)))))))). % ord_eq_less_trans
tff(fact_151_ord__less__eq__trans, axiom,
    ((![B : $tType]: (ord(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, A2, B2) => ((B2 = C) => ord_less(B, A2, C)))))))). % ord_less_eq_trans
tff(fact_152_less__induct, axiom,
    ((![B : $tType]: (wellorder(B) => (![P : fun(B, $o), A2 : B]: ((![X : B]: ((![Y3 : B]: (ord_less(B, Y3, X) => aa(B, $o, P, Y3))) => aa(B, $o, P, X))) => aa(B, $o, P, A2))))))). % less_induct
tff(fact_153_antisym__conv3, axiom,
    ((![B : $tType]: (linorder(B) => (![Y : B, Xa : B]: ((~ (ord_less(B, Y, Xa))) => ((~ (ord_less(B, Xa, Y))) <=> (Xa = Y)))))))). % antisym_conv3
tff(fact_154_linorder__cases, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less(B, Xa, Y))) => ((Xa != Y) => ord_less(B, Y, Xa)))))))). % linorder_cases
tff(fact_155_dual__order_Oasym, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B]: (ord_less(B, B2, A2) => (~ (ord_less(B, A2, B2))))))))). % dual_order.asym
tff(fact_156_dual__order_Oirrefl, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B]: (~ (ord_less(B, A2, A2)))))))). % dual_order.irrefl
tff(fact_157_exists__least__iff, axiom,
    ((![B : $tType]: (wellorder(B) => (![P : fun(B, $o)]: ((?[X_12 : B]: aa(B, $o, P, X_12)) <=> (?[N2 : B]: (aa(B, $o, P, N2) & (![M2 : B]: (ord_less(B, M2, N2) => (~ (aa(B, $o, P, M2))))))))))))). % exists_least_iff
tff(fact_158_linorder__less__wlog, axiom,
    ((![B : $tType]: (linorder(B) => (![P : fun(B, fun(B, $o)), A2 : B, B2 : B]: ((![A5 : B, B5 : B]: (ord_less(B, A5, B5) => aa(B, $o, aa(B, fun(B, $o), P, A5), B5))) => ((![A5 : B]: aa(B, $o, aa(B, fun(B, $o), P, A5), A5)) => ((![A5 : B, B5 : B]: (aa(B, $o, aa(B, fun(B, $o), P, B5), A5) => aa(B, $o, aa(B, fun(B, $o), P, A5), B5))) => aa(B, $o, aa(B, fun(B, $o), P, A2), B2))))))))). % linorder_less_wlog
tff(fact_159_order_Ostrict__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, A2, B2) => (ord_less(B, B2, C) => ord_less(B, A2, C)))))))). % order.strict_trans
tff(fact_160_not__less__iff__gr__or__eq, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less(B, Xa, Y))) <=> (ord_less(B, Y, Xa) | (Xa = Y)))))))). % not_less_iff_gr_or_eq
tff(fact_161_dual__order_Ostrict__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B, C : B]: (ord_less(B, B2, A2) => (ord_less(B, C, B2) => ord_less(B, C, A2)))))))). % dual_order.strict_trans
tff(fact_162_order_Ostrict__implies__not__eq, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (A2 != B2))))))). % order.strict_implies_not_eq
tff(fact_163_linordered__field__no__lb, axiom,
    ((![B : $tType]: (linordered_field(B) => (![X3 : B]: (?[Y2 : B]: ord_less(B, Y2, X3))))))). % linordered_field_no_lb
tff(fact_164_linordered__field__no__ub, axiom,
    ((![B : $tType]: (linordered_field(B) => (![X3 : B]: (?[X_1 : B]: ord_less(B, X3, X_1))))))). % linordered_field_no_ub
tff(fact_165_dual__order_Ostrict__implies__not__eq, axiom,
    ((![B : $tType]: (order(B) => (![B2 : B, A2 : B]: (ord_less(B, B2, A2) => (A2 != B2))))))). % dual_order.strict_implies_not_eq
tff(fact_166_linorder__neqE__linordered__idom, axiom,
    ((![B : $tType]: (linordered_idom(B) => (![Xa : B, Y : B]: ((Xa != Y) => ((~ (ord_less(B, Xa, Y))) => ord_less(B, Y, Xa)))))))). % linorder_neqE_linordered_idom
tff(fact_167_linorder__neqE, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((Xa != Y) => ((~ (ord_less(B, Xa, Y))) => ord_less(B, Y, Xa)))))))). % linorder_neqE
tff(fact_168_order__less__asym, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (~ (ord_less(B, Y, Xa))))))))). % order_less_asym
tff(fact_169_linorder__neq__iff, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((Xa != Y) <=> (ord_less(B, Xa, Y) | ord_less(B, Y, Xa)))))))). % linorder_neq_iff
tff(fact_170_order__less__asym_H, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (~ (ord_less(B, B2, A2))))))))). % order_less_asym'
tff(fact_171_order__less__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B, Z : B]: (ord_less(B, Xa, Y) => (ord_less(B, Y, Z) => ord_less(B, Xa, Z)))))))). % order_less_trans
tff(fact_172_ord__eq__less__subst, axiom,
    ((![B : $tType, C2 : $tType]: ((ord(C2) & ord(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: ((A2 = aa(C2, B, F, B2)) => (ord_less(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less(C2, X, Y2) => ord_less(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less(B, A2, aa(C2, B, F, C)))))))))). % ord_eq_less_subst
tff(fact_173_ord__less__eq__subst, axiom,
    ((![B : $tType, C2 : $tType]: ((ord(C2) & ord(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less(B, A2, B2) => ((aa(B, C2, F, B2) = C) => ((![X : B, Y2 : B]: (ord_less(B, X, Y2) => ord_less(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less(C2, aa(B, C2, F, A2), C))))))))). % ord_less_eq_subst
tff(fact_174_order__less__irrefl, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B]: (~ (ord_less(B, Xa, Xa)))))))). % order_less_irrefl
tff(fact_175_order__less__subst1, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, F : fun(C2, B), B2 : C2, C : C2]: (ord_less(B, A2, aa(C2, B, F, B2)) => (ord_less(C2, B2, C) => ((![X : C2, Y2 : C2]: (ord_less(C2, X, Y2) => ord_less(B, aa(C2, B, F, X), aa(C2, B, F, Y2)))) => ord_less(B, A2, aa(C2, B, F, C)))))))))). % order_less_subst1
tff(fact_176_order__less__subst2, axiom,
    ((![B : $tType, C2 : $tType]: ((order(C2) & order(B)) => (![A2 : B, B2 : B, F : fun(B, C2), C : C2]: (ord_less(B, A2, B2) => (ord_less(C2, aa(B, C2, F, B2), C) => ((![X : B, Y2 : B]: (ord_less(B, X, Y2) => ord_less(C2, aa(B, C2, F, X), aa(B, C2, F, Y2)))) => ord_less(C2, aa(B, C2, F, A2), C))))))))). % order_less_subst2
tff(fact_177_order__less__not__sym, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (~ (ord_less(B, Y, Xa))))))))). % order_less_not_sym
tff(fact_178_order__less__imp__triv, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B, P : $o]: (ord_less(B, Xa, Y) => (ord_less(B, Y, Xa) => P))))))). % order_less_imp_triv
tff(fact_179_linorder__less__linear, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) | ((Xa = Y) | ord_less(B, Y, Xa)))))))). % linorder_less_linear
tff(fact_180_order__less__imp__not__eq, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (Xa != Y))))))). % order_less_imp_not_eq
tff(fact_181_order__less__imp__not__eq2, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (Y != Xa))))))). % order_less_imp_not_eq2
tff(fact_182_order__less__imp__not__less, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => (~ (ord_less(B, Y, Xa))))))))). % order_less_imp_not_less
tff(fact_183_leD, axiom,
    ((![B : $tType]: (order(B) => (![Y : B, Xa : B]: (ord_less_eq(B, Y, Xa) => (~ (ord_less(B, Xa, Y))))))))). % leD
tff(fact_184_leI, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less(B, Xa, Y))) => ord_less_eq(B, Y, Xa))))))). % leI
tff(fact_185_nless__le, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: ((~ (ord_less(B, A2, B2))) <=> ((~ (ord_less_eq(B, A2, B2))) | (A2 = B2)))))))). % nless_le
tff(fact_186_antisym__conv1, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: ((~ (ord_less(B, Xa, Y))) => (ord_less_eq(B, Xa, Y) <=> (Xa = Y)))))))). % antisym_conv1
tff(fact_187_antisym__conv2, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) => ((~ (ord_less(B, Xa, Y))) <=> (Xa = Y)))))))). % antisym_conv2
tff(fact_188_dense__ge, axiom,
    ((![B : $tType]: (dense_linorder(B) => (![Z : B, Y : B]: ((![X : B]: (ord_less(B, Z, X) => ord_less_eq(B, Y, X))) => ord_less_eq(B, Y, Z))))))). % dense_ge
tff(fact_189_dense__le, axiom,
    ((![B : $tType]: (dense_linorder(B) => (![Y : B, Z : B]: ((![X : B]: (ord_less(B, X, Y) => ord_less_eq(B, X, Z))) => ord_less_eq(B, Y, Z))))))). % dense_le
tff(fact_190_less__le__not__le, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) <=> (ord_less_eq(B, Xa, Y) & (~ (ord_less_eq(B, Y, Xa)))))))))). % less_le_not_le
tff(fact_191_not__le__imp__less, axiom,
    ((![B : $tType]: (linorder(B) => (![Y : B, Xa : B]: ((~ (ord_less_eq(B, Y, Xa))) => ord_less(B, Xa, Y))))))). % not_le_imp_less
tff(fact_192_order_Oorder__iff__strict, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, B2) <=> (ord_less(B, A2, B2) | (A2 = B2)))))))). % order.order_iff_strict
tff(fact_193_order_Ostrict__iff__order, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) <=> (ord_less_eq(B, A2, B2) & (A2 != B2)))))))). % order.strict_iff_order
tff(fact_194_order_Ostrict__trans1, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B, C : B]: (ord_less_eq(B, A2, B2) => (ord_less(B, B2, C) => ord_less(B, A2, C)))))))). % order.strict_trans1
tff(fact_195_order_Ostrict__trans2, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B, C : B]: (ord_less(B, A2, B2) => (ord_less_eq(B, B2, C) => ord_less(B, A2, C)))))))). % order.strict_trans2
tff(fact_196_order_Ostrict__iff__not, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) <=> (ord_less_eq(B, A2, B2) & (~ (ord_less_eq(B, B2, A2)))))))))). % order.strict_iff_not
tff(fact_197_dense__ge__bounded, axiom,
    ((![B : $tType]: (dense_linorder(B) => (![Z : B, Xa : B, Y : B]: (ord_less(B, Z, Xa) => ((![W : B]: (ord_less(B, Z, W) => (ord_less(B, W, Xa) => ord_less_eq(B, Y, W)))) => ord_less_eq(B, Y, Z)))))))). % dense_ge_bounded
tff(fact_198_dense__le__bounded, axiom,
    ((![B : $tType]: (dense_linorder(B) => (![Xa : B, Y : B, Z : B]: (ord_less(B, Xa, Y) => ((![W : B]: (ord_less(B, Xa, W) => (ord_less(B, W, Y) => ord_less_eq(B, W, Z)))) => ord_less_eq(B, Y, Z)))))))). % dense_le_bounded
tff(fact_199_dual__order_Oorder__iff__strict, axiom,
    ((![B : $tType]: (order(B) => (![B2 : B, A2 : B]: (ord_less_eq(B, B2, A2) <=> (ord_less(B, B2, A2) | (A2 = B2)))))))). % dual_order.order_iff_strict
tff(fact_200_dual__order_Ostrict__iff__order, axiom,
    ((![B : $tType]: (order(B) => (![B2 : B, A2 : B]: (ord_less(B, B2, A2) <=> (ord_less_eq(B, B2, A2) & (A2 != B2)))))))). % dual_order.strict_iff_order
tff(fact_201_dual__order_Ostrict__trans1, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B, C : B]: (ord_less_eq(B, B2, A2) => (ord_less(B, C, B2) => ord_less(B, C, A2)))))))). % dual_order.strict_trans1
tff(fact_202_dual__order_Ostrict__trans2, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B, C : B]: (ord_less(B, B2, A2) => (ord_less_eq(B, C, B2) => ord_less(B, C, A2)))))))). % dual_order.strict_trans2
tff(fact_203_dual__order_Ostrict__iff__not, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B]: (ord_less(B, B2, A2) <=> (ord_less_eq(B, B2, A2) & (~ (ord_less_eq(B, A2, B2)))))))))). % dual_order.strict_iff_not
tff(fact_204_order_Ostrict__implies__order, axiom,
    ((![B : $tType]: (preorder(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => ord_less_eq(B, A2, B2))))))). % order.strict_implies_order
tff(fact_205_dual__order_Ostrict__implies__order, axiom,
    ((![B : $tType]: (preorder(B) => (![B2 : B, A2 : B]: (ord_less(B, B2, A2) => ord_less_eq(B, B2, A2))))))). % dual_order.strict_implies_order
tff(fact_206_order__le__less, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less_eq(B, Xa, Y) <=> (ord_less(B, Xa, Y) | (Xa = Y)))))))). % order_le_less
tff(fact_207_order__less__le, axiom,
    ((![B : $tType]: (order(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) <=> (ord_less_eq(B, Xa, Y) & (Xa != Y)))))))). % order_less_le
tff(fact_208_linorder__not__le, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less_eq(B, Xa, Y))) <=> ord_less(B, Y, Xa))))))). % linorder_not_le
tff(fact_209_linorder__not__less, axiom,
    ((![B : $tType]: (linorder(B) => (![Xa : B, Y : B]: ((~ (ord_less(B, Xa, Y))) <=> ord_less_eq(B, Y, Xa))))))). % linorder_not_less
tff(fact_210_order__less__imp__le, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B]: (ord_less(B, Xa, Y) => ord_less_eq(B, Xa, Y))))))). % order_less_imp_le
tff(fact_211_order__le__neq__trans, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, A2, B2) => ((A2 != B2) => ord_less(B, A2, B2)))))))). % order_le_neq_trans
tff(fact_212_order__neq__le__trans, axiom,
    ((![B : $tType]: (order(B) => (![A2 : B, B2 : B]: ((A2 != B2) => (ord_less_eq(B, A2, B2) => ord_less(B, A2, B2)))))))). % order_neq_le_trans
tff(fact_213_order__le__less__trans, axiom,
    ((![B : $tType]: (preorder(B) => (![Xa : B, Y : B, Z : B]: (ord_less_eq(B, Xa, Y) => (ord_less(B, Y, Z) => ord_less(B, Xa, Z)))))))). % order_le_less_trans
tff(fact_214_minf_I8_J, axiom,
    ((![B : $tType]: (linorder(B) => (![T : B]: (?[Z2 : B]: (![X3 : B]: (ord_less(B, X3, Z2) => (~ (ord_less_eq(B, T, X3))))))))))). % minf(8)
tff(fact_215_minf_I6_J, axiom,
    ((![B : $tType]: (linorder(B) => (![T : B]: (?[Z2 : B]: (![X3 : B]: (ord_less(B, X3, Z2) => ord_less_eq(B, X3, T))))))))). % minf(6)
tff(fact_216_pinf_I8_J, axiom,
    ((![B : $tType]: (linorder(B) => (![T : B]: (?[Z2 : B]: (![X3 : B]: (ord_less(B, Z2, X3) => ord_less_eq(B, T, X3))))))))). % pinf(8)
tff(fact_217_pinf_I6_J, axiom,
    ((![B : $tType]: (linorder(B) => (![T : B]: (?[Z2 : B]: (![X3 : B]: (ord_less(B, Z2, X3) => (~ (ord_less_eq(B, X3, T))))))))))). % pinf(6)
tff(fact_218_complete__interval, axiom,
    ((![B : $tType]: (condit1037483654norder(B) => (![A2 : B, B2 : B, P : fun(B, $o)]: (ord_less(B, A2, B2) => (aa(B, $o, P, A2) => ((~ (aa(B, $o, P, B2))) => (?[C3 : B]: (ord_less_eq(B, A2, C3) & (ord_less_eq(B, C3, B2) & ((![X3 : B]: ((ord_less_eq(B, A2, X3) & ord_less(B, X3, C3)) => aa(B, $o, P, X3))) & (![D2 : B]: ((![X : B]: ((ord_less_eq(B, A2, X) & ord_less(B, X, D2)) => aa(B, $o, P, X))) => ord_less_eq(B, D2, C3))))))))))))))). % complete_interval
tff(fact_219_GreatestI2__order, axiom,
    ((![B : $tType]: (order(B) => (![P : fun(B, $o), Xa : B, Q : fun(B, $o)]: (aa(B, $o, P, Xa) => ((![Y2 : B]: (aa(B, $o, P, Y2) => ord_less_eq(B, Y2, Xa))) => ((![X : B]: (aa(B, $o, P, X) => ((![Y3 : B]: (aa(B, $o, P, Y3) => ord_less_eq(B, Y3, X))) => aa(B, $o, Q, X)))) => aa(B, $o, Q, order_Greatest(B, P)))))))))). % GreatestI2_order
tff(fact_220_Greatest__equality, axiom,
    ((![B : $tType]: (order(B) => (![P : fun(B, $o), Xa : B]: (aa(B, $o, P, Xa) => ((![Y2 : B]: (aa(B, $o, P, Y2) => ord_less_eq(B, Y2, Xa))) => (order_Greatest(B, P) = Xa)))))))). % Greatest_equality
tff(fact_221_monoid_Oaxioms_I2_J, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: (monoid(B, F, Z) => monoid_axioms(B, F, Z)))))). % monoid.axioms(2)
tff(fact_222_comm__monoid_Oaxioms_I2_J, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: (comm_monoid(B, F, Z) => comm_monoid_axioms(B, F, Z)))))). % comm_monoid.axioms(2)
tff(fact_223_inverse__le__iff__le__neg, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, zero_zero(B)) => (ord_less(B, B2, zero_zero(B)) => (ord_less_eq(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) <=> ord_less_eq(B, B2, A2))))))))). % inverse_le_iff_le_neg
tff(fact_224_inverse__le__iff__le, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, zero_zero(B), A2) => (ord_less(B, zero_zero(B), B2) => (ord_less_eq(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) <=> ord_less_eq(B, B2, A2))))))))). % inverse_le_iff_le
tff(fact_225_inverse__eq__iff__eq, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B, B2 : B]: ((inverse_inverse(B, A2) = inverse_inverse(B, B2)) <=> (A2 = B2))))))). % inverse_eq_iff_eq
tff(fact_226_inverse__inverse__eq, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B]: (inverse_inverse(B, inverse_inverse(B, A2)) = A2)))))). % inverse_inverse_eq
tff(fact_227_inverse__zero, axiom,
    ((![B : $tType]: (division_ring(B) => (inverse_inverse(B, zero_zero(B)) = zero_zero(B)))))). % inverse_zero
tff(fact_228_inverse__nonzero__iff__nonzero, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B]: ((inverse_inverse(B, A2) = zero_zero(B)) <=> (A2 = zero_zero(B)))))))). % inverse_nonzero_iff_nonzero
tff(fact_229_inverse__nonnegative__iff__nonnegative, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less_eq(B, zero_zero(B), inverse_inverse(B, A2)) <=> ord_less_eq(B, zero_zero(B), A2))))))). % inverse_nonnegative_iff_nonnegative
tff(fact_230_inverse__nonpositive__iff__nonpositive, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less_eq(B, inverse_inverse(B, A2), zero_zero(B)) <=> ord_less_eq(B, A2, zero_zero(B)))))))). % inverse_nonpositive_iff_nonpositive
tff(fact_231_inverse__less__iff__less, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, zero_zero(B), A2) => (ord_less(B, zero_zero(B), B2) => (ord_less(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) <=> ord_less(B, B2, A2))))))))). % inverse_less_iff_less
tff(fact_232_inverse__less__iff__less__neg, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, zero_zero(B)) => (ord_less(B, B2, zero_zero(B)) => (ord_less(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) <=> ord_less(B, B2, A2))))))))). % inverse_less_iff_less_neg
tff(fact_233_inverse__negative__iff__negative, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, inverse_inverse(B, A2), zero_zero(B)) <=> ord_less(B, A2, zero_zero(B)))))))). % inverse_negative_iff_negative
tff(fact_234_inverse__positive__iff__positive, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, zero_zero(B), inverse_inverse(B, A2)) <=> ord_less(B, zero_zero(B), A2))))))). % inverse_positive_iff_positive
tff(fact_235_less__fun__def, axiom,
    ((![C2 : $tType, B : $tType]: (ord(C2) => (![F : fun(B, C2), G : fun(B, C2)]: (ord_less(fun(B, C2), F, G) <=> (ord_less_eq(fun(B, C2), F, G) & (~ (ord_less_eq(fun(B, C2), G, F)))))))))). % less_fun_def
tff(fact_236_inverse__eq__imp__eq, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B, B2 : B]: ((inverse_inverse(B, A2) = inverse_inverse(B, B2)) => (A2 = B2))))))). % inverse_eq_imp_eq
tff(fact_237_comm__monoid__axioms__def, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: (comm_monoid_axioms(B, F, Z) <=> (![A6 : B]: (aa(B, B, aa(B, fun(B, B), F, A6), Z) = A6))))))). % comm_monoid_axioms_def
tff(fact_238_monoid__axioms__def, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: (monoid_axioms(B, F, Z) <=> ((![A6 : B]: (aa(B, B, aa(B, fun(B, B), F, Z), A6) = A6)) & (![A6 : B]: (aa(B, B, aa(B, fun(B, B), F, A6), Z) = A6)))))))). % monoid_axioms_def
tff(fact_239_comm__monoid__axioms_Ointro, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: ((![A5 : B]: (aa(B, B, aa(B, fun(B, B), F, A5), Z) = A5)) => comm_monoid_axioms(B, F, Z)))))). % comm_monoid_axioms.intro
tff(fact_240_monoid__axioms_Ointro, axiom,
    ((![B : $tType]: (![F : fun(B, fun(B, B)), Z : B]: ((![A5 : B]: (aa(B, B, aa(B, fun(B, B), F, Z), A5) = A5)) => ((![A5 : B]: (aa(B, B, aa(B, fun(B, B), F, A5), Z) = A5)) => monoid_axioms(B, F, Z))))))). % monoid_axioms.intro
tff(fact_241_field__class_Ofield__inverse__zero, axiom,
    ((![B : $tType]: (field(B) => (inverse_inverse(B, zero_zero(B)) = zero_zero(B)))))). % field_class.field_inverse_zero
tff(fact_242_inverse__zero__imp__zero, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B]: ((inverse_inverse(B, A2) = zero_zero(B)) => (A2 = zero_zero(B)))))))). % inverse_zero_imp_zero
tff(fact_243_nonzero__inverse__eq__imp__eq, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B, B2 : B]: ((inverse_inverse(B, A2) = inverse_inverse(B, B2)) => ((A2 != zero_zero(B)) => ((B2 != zero_zero(B)) => (A2 = B2))))))))). % nonzero_inverse_eq_imp_eq
tff(fact_244_nonzero__inverse__inverse__eq, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B]: ((A2 != zero_zero(B)) => (inverse_inverse(B, inverse_inverse(B, A2)) = A2))))))). % nonzero_inverse_inverse_eq
tff(fact_245_nonzero__imp__inverse__nonzero, axiom,
    ((![B : $tType]: (division_ring(B) => (![A2 : B]: ((A2 != zero_zero(B)) => (inverse_inverse(B, A2) != zero_zero(B)))))))). % nonzero_imp_inverse_nonzero
tff(fact_246_inverse__less__imp__less, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) => (ord_less(B, zero_zero(B), A2) => ord_less(B, B2, A2)))))))). % inverse_less_imp_less
tff(fact_247_less__imp__inverse__less, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (ord_less(B, zero_zero(B), A2) => ord_less(B, inverse_inverse(B, B2), inverse_inverse(B, A2))))))))). % less_imp_inverse_less
tff(fact_248_inverse__less__imp__less__neg, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) => (ord_less(B, B2, zero_zero(B)) => ord_less(B, B2, A2)))))))). % inverse_less_imp_less_neg
tff(fact_249_less__imp__inverse__less__neg, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less(B, A2, B2) => (ord_less(B, B2, zero_zero(B)) => ord_less(B, inverse_inverse(B, B2), inverse_inverse(B, A2))))))))). % less_imp_inverse_less_neg
tff(fact_250_inverse__negative__imp__negative, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, inverse_inverse(B, A2), zero_zero(B)) => ((A2 != zero_zero(B)) => ord_less(B, A2, zero_zero(B))))))))). % inverse_negative_imp_negative
tff(fact_251_inverse__positive__imp__positive, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, zero_zero(B), inverse_inverse(B, A2)) => ((A2 != zero_zero(B)) => ord_less(B, zero_zero(B), A2)))))))). % inverse_positive_imp_positive
tff(fact_252_negative__imp__inverse__negative, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, A2, zero_zero(B)) => ord_less(B, inverse_inverse(B, A2), zero_zero(B)))))))). % negative_imp_inverse_negative
tff(fact_253_positive__imp__inverse__positive, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B]: (ord_less(B, zero_zero(B), A2) => ord_less(B, zero_zero(B), inverse_inverse(B, A2)))))))). % positive_imp_inverse_positive
tff(fact_254_inverse__le__imp__le, axiom,
    ((![B : $tType]: (linordered_field(B) => (![A2 : B, B2 : B]: (ord_less_eq(B, inverse_inverse(B, A2), inverse_inverse(B, B2)) => (ord_less(B, zero_zero(B), A2) => ord_less_eq(B, B2, A2)))))))). % inverse_le_imp_le
tff(fact_255_ATP_Olambda__1, axiom,
    ((![B : $tType]: (![Uu : set(B), Uua : B]: (aa(B, $o, aTP_Lamp_a(set(B), fun(B, $o), Uu), Uua) <=> member(B, Uua, Uu)))))). % ATP.lambda_1

% Subclasses (2)
tff(subcl_Groups_Oplus___HOL_Otype, axiom,
    ((![A : $tType]: (plus(A) => type(A))))).
tff(subcl_Groups_Ozero___HOL_Otype, axiom,
    ((![A : $tType]: (zero(A) => type(A))))).

% Type constructors (10)
tff(tcon_fun___Orderings_Opreorder, axiom,
    ((![A7 : $tType, A8 : $tType]: (preorder(A8) => preorder(fun(A7, A8)))))).
tff(tcon_fun___Orderings_Oorder, axiom,
    ((![A7 : $tType, A8 : $tType]: (order(A8) => order(fun(A7, A8)))))).
tff(tcon_fun___Orderings_Oord, axiom,
    ((![A7 : $tType, A8 : $tType]: (ord(A8) => ord(fun(A7, A8)))))).
tff(tcon_Set_Oset___Orderings_Opreorder_1, axiom,
    ((![A7 : $tType]: preorder(set(A7))))).
tff(tcon_Set_Oset___Orderings_Oorder_2, axiom,
    ((![A7 : $tType]: order(set(A7))))).
tff(tcon_Set_Oset___Orderings_Oord_3, axiom,
    ((![A7 : $tType]: ord(set(A7))))).
tff(tcon_HOL_Obool___Orderings_Opreorder_4, axiom,
    (preorder($o))).
tff(tcon_HOL_Obool___Orderings_Olinorder, axiom,
    (linorder($o))).
tff(tcon_HOL_Obool___Orderings_Oorder_5, axiom,
    (order($o))).
tff(tcon_HOL_Obool___Orderings_Oord_6, axiom,
    (ord($o))).

% Free types (2)
tff(tfree_0, hypothesis,
    (plus(a))).
tff(tfree_1, hypothesis,
    (zero(a))).

% Conjectures (1)
tff(conj_0, conjecture,
    ((aa(a, a, aa(a, fun(a, a), plus_plus(a), x), zero_zero(a)) = x))).
