% /Applications/Isabelle2025.app/contrib/vampire-4.8/x86_64-darwin/vampire --input_syntax tptp --proof tptp --output_axiom_names on --mode portfolio --schedule snake_slh -t 5 --input_file /Users/linqilan/Downloads/KEP\ AWS/sledgehammer_export/prob5283040_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2025-11-20 21:44:04.830
% Could-be-implicit typings (4)
thf(ty_n_t__Set__Oset_It__Nat__Onat_J, type,
    set_nat : $tType).
thf(ty_n_t__Num__Onum, type,
    num : $tType).
thf(ty_n_t__Nat__Onat, type,
    nat : $tType).
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (33)
thf(sy_c_Fun_Ocomp_001t__Nat__Onat_001t__Nat__Onat_001t__Nat__Onat, type,
    comp_nat_nat_nat : (nat > nat) > (nat > nat) > nat > nat).
thf(sy_c_Fun_Oinj__on_001t__Nat__Onat_001t__Nat__Onat, type,
    inj_on_nat_nat : (nat > nat) > set_nat > $o).
thf(sy_c_Groups_Oabel__semigroup_001t__Nat__Onat, type,
    abel_semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Oabel__semigroup__axioms_001t__Nat__Onat, type,
    abel_s1659454557ms_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Ocomm__monoid_001t__Nat__Onat, type,
    comm_monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ocomm__monoid__axioms_001t__Nat__Onat, type,
    comm_m2051353214ms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Ominus__class_Ominus_001t__Nat__Onat, type,
    minus_minus_nat : nat > nat > nat).
thf(sy_c_Groups_Omonoid_001t__Nat__Onat, type,
    monoid_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Omonoid__axioms_001t__Nat__Onat, type,
    monoid_axioms_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat, type,
    one_one_nat : nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Nat__Onat, type,
    plus_plus_nat : nat > nat > nat).
thf(sy_c_Groups_Oplus__class_Oplus_001t__Num__Onum, type,
    plus_plus_num : num > num > num).
thf(sy_c_Groups_Oplus__class_Oplus_001tf__a, type,
    plus_plus_a : a > a > a).
thf(sy_c_Groups_Osemigroup_001t__Nat__Onat, type,
    semigroup_nat : (nat > nat > nat) > $o).
thf(sy_c_Groups_Otimes__class_Otimes_001t__Nat__Onat, type,
    times_times_nat : nat > nat > nat).
thf(sy_c_Groups_Ozero__class_Ozero_001t__Nat__Onat, type,
    zero_zero_nat : nat).
thf(sy_c_Groups__Big_Ocomm__monoid__add__class_Osum_001t__Nat__Onat_001t__Nat__Onat, type,
    groups1842438620at_nat : (nat > nat) > set_nat > nat).
thf(sy_c_Groups__Big_Ocomm__monoid__set_001t__Nat__Onat, type,
    groups1056228905et_nat : (nat > nat > nat) > nat > $o).
thf(sy_c_Nat_OSuc, type,
    suc : nat > nat).
thf(sy_c_Num_Onum_OBit0, type,
    bit0 : num > num).
thf(sy_c_Num_Onum_OOne, type,
    one : num).
thf(sy_c_Num_Onumeral__class_Onumeral_001t__Nat__Onat, type,
    numeral_numeral_nat : num > nat).
thf(sy_c_Orderings_Obot__class_Obot_001_Eo, type,
    bot_bot_o : $o).
thf(sy_c_Orderings_Oord__class_Oless_001_Eo, type,
    ord_less_o : $o > $o > $o).
thf(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat, type,
    ord_less_nat : nat > nat > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001_Eo, type,
    ord_less_eq_o : $o > $o > $o).
thf(sy_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat, type,
    ord_less_eq_nat : nat > nat > $o).
thf(sy_c_Rings_Ozero__neq__one__class_Oof__bool_001t__Nat__Onat, type,
    zero_n1356753679ol_nat : $o > nat).
thf(sy_c_Set__Interval_Oord__class_OatLeastAtMost_001t__Nat__Onat, type,
    set_or601162459st_nat : nat > nat > set_nat).
thf(sy_c_Set__Interval_Oord__class_OatLeastLessThan_001t__Nat__Onat, type,
    set_or562006527an_nat : nat > nat > set_nat).
thf(sy_c_Set__Interval_Oord__class_OatMost_001t__Nat__Onat, type,
    set_ord_atMost_nat : nat > set_nat).
thf(sy_v_x, type,
    x : a).
thf(sy_v_y, type,
    y : a).

% Relevant facts (219)
thf(fact_0_add__left__cancel, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) = (B = C))))). % add_left_cancel
thf(fact_1_semigroup_Ointro, axiom,
    ((![F : nat > nat > nat]: ((![A2 : nat, B2 : nat, C2 : nat]: ((F @ (F @ A2 @ B2) @ C2) = (F @ A2 @ (F @ B2 @ C2)))) => (semigroup_nat @ F))))). % semigroup.intro
thf(fact_2_add__right__cancel, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) = (B = C))))). % add_right_cancel
thf(fact_3_ab__semigroup__add__class_Oadd__ac_I1_J, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % ab_semigroup_add_class.add_ac(1)
thf(fact_4_add__numeral__left, axiom,
    ((![V : num, W : num, Z : nat]: ((plus_plus_nat @ (numeral_numeral_nat @ V) @ (plus_plus_nat @ (numeral_numeral_nat @ W) @ Z)) = (plus_plus_nat @ (numeral_numeral_nat @ (plus_plus_num @ V @ W)) @ Z))))). % add_numeral_left
thf(fact_5_add__mono__thms__linordered__semiring_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (K = L)) => ((plus_plus_nat @ I @ K) = (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(4)
thf(fact_6_group__cancel_Oadd1, axiom,
    ((![A3 : nat, K : nat, A : nat, B : nat]: ((A3 = (plus_plus_nat @ K @ A)) => ((plus_plus_nat @ A3 @ B) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add1
thf(fact_7_abel__semigroup_Ocommute, axiom,
    ((![F : nat > nat > nat, A : nat, B : nat]: ((abel_semigroup_nat @ F) => ((F @ A @ B) = (F @ B @ A)))))). % abel_semigroup.commute
thf(fact_8_group__cancel_Oadd2, axiom,
    ((![B3 : nat, K : nat, B : nat, A : nat]: ((B3 = (plus_plus_nat @ K @ B)) => ((plus_plus_nat @ A @ B3) = (plus_plus_nat @ K @ (plus_plus_nat @ A @ B))))))). % group_cancel.add2
thf(fact_9_add_Oright__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.right_neutral
thf(fact_10_add_Ocommute, axiom,
    ((plus_plus_nat = (^[A4 : nat]: (^[B4 : nat]: (plus_plus_nat @ B4 @ A4)))))). % add.commute
thf(fact_11_add__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % add_0
thf(fact_12_abel__semigroup_Ointro, axiom,
    ((![F : nat > nat > nat]: ((semigroup_nat @ F) => ((abel_s1659454557ms_nat @ F) => (abel_semigroup_nat @ F)))))). % abel_semigroup.intro
thf(fact_13_add_Oassoc, axiom,
    ((![A : nat, B : nat, C : nat]: ((plus_plus_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.assoc
thf(fact_14_monoid_Oright__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % monoid.right_neutral
thf(fact_15_add_Oleft__commute, axiom,
    ((![B : nat, A : nat, C : nat]: ((plus_plus_nat @ B @ (plus_plus_nat @ A @ C)) = (plus_plus_nat @ A @ (plus_plus_nat @ B @ C)))))). % add.left_commute
thf(fact_16_add__left__imp__eq, axiom,
    ((![A : nat, B : nat, C : nat]: (((plus_plus_nat @ A @ B) = (plus_plus_nat @ A @ C)) => (B = C))))). % add_left_imp_eq
thf(fact_17_add__right__imp__eq, axiom,
    ((![B : nat, A : nat, C : nat]: (((plus_plus_nat @ B @ A) = (plus_plus_nat @ C @ A)) => (B = C))))). % add_right_imp_eq
thf(fact_18_monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((semigroup_nat @ F) => ((monoid_axioms_nat @ F @ Z) => (monoid_nat @ F @ Z)))))). % monoid.intro
thf(fact_19_comm__monoid__add__class_Oadd__0, axiom,
    ((![A : nat]: ((plus_plus_nat @ zero_zero_nat @ A) = A)))). % comm_monoid_add_class.add_0
thf(fact_20_dual__order_Orefl, axiom,
    ((![A : $o]: (ord_less_eq_o @ A @ A)))). % dual_order.refl
thf(fact_21_dual__order_Orefl, axiom,
    ((![A : nat]: (ord_less_eq_nat @ A @ A)))). % dual_order.refl
thf(fact_22_add__cancel__right__right, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ A @ B)) = (B = zero_zero_nat))))). % add_cancel_right_right
thf(fact_23_add__cancel__left__right, axiom,
    ((![A : nat, B : nat]: (((plus_plus_nat @ A @ B) = A) = (B = zero_zero_nat))))). % add_cancel_left_right
thf(fact_24_add__cancel__right__left, axiom,
    ((![A : nat, B : nat]: ((A = (plus_plus_nat @ B @ A)) = (B = zero_zero_nat))))). % add_cancel_right_left
thf(fact_25_add__eq__0__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: (((plus_plus_nat @ X @ Y) = zero_zero_nat) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % add_eq_0_iff_both_eq_0
thf(fact_26_zero__eq__add__iff__both__eq__0, axiom,
    ((![X : nat, Y : nat]: ((zero_zero_nat = (plus_plus_nat @ X @ Y)) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))). % zero_eq_add_iff_both_eq_0
thf(fact_27_add__cancel__left__left, axiom,
    ((![B : nat, A : nat]: (((plus_plus_nat @ B @ A) = A) = (B = zero_zero_nat))))). % add_cancel_left_left
thf(fact_28_comm__monoid_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((abel_semigroup_nat @ F) => ((comm_m2051353214ms_nat @ F @ Z) => (comm_monoid_nat @ F @ Z)))))). % comm_monoid.intro
thf(fact_29_monoid_Oleft__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((monoid_nat @ F @ Z) => ((F @ Z @ A) = A))))). % monoid.left_neutral
thf(fact_30_numeral__plus__numeral, axiom,
    ((![M : num, N : num]: ((plus_plus_nat @ (numeral_numeral_nat @ M) @ (numeral_numeral_nat @ N)) = (numeral_numeral_nat @ (plus_plus_num @ M @ N)))))). % numeral_plus_numeral
thf(fact_31_add_Ocomm__neutral, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % add.comm_neutral
thf(fact_32_add__le__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_left
thf(fact_33_abel__semigroup_Oleft__commute, axiom,
    ((![F : nat > nat > nat, B : nat, A : nat, C : nat]: ((abel_semigroup_nat @ F) => ((F @ B @ (F @ A @ C)) = (F @ A @ (F @ B @ C))))))). % abel_semigroup.left_commute
thf(fact_34_verit__sum__simplify, axiom,
    ((![A : nat]: ((plus_plus_nat @ A @ zero_zero_nat) = A)))). % verit_sum_simplify
thf(fact_35_comm__monoid__set_Ointro, axiom,
    ((![F : nat > nat > nat, Z : nat]: ((comm_monoid_nat @ F @ Z) => (groups1056228905et_nat @ F @ Z))))). % comm_monoid_set.intro
thf(fact_36_add__Suc__right, axiom,
    ((![M : nat, N : nat]: ((plus_plus_nat @ M @ (suc @ N)) = (suc @ (plus_plus_nat @ M @ N)))))). % add_Suc_right
thf(fact_37_add__mono__thms__linordered__semiring_I1_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(1)
thf(fact_38_zero__reorient, axiom,
    ((![X : nat]: ((zero_zero_nat = X) = (X = zero_zero_nat))))). % zero_reorient
thf(fact_39_add_Ocomm__monoid__axioms, axiom,
    ((comm_monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.comm_monoid_axioms
thf(fact_40_add_Omonoid__axioms, axiom,
    ((monoid_nat @ plus_plus_nat @ zero_zero_nat))). % add.monoid_axioms
thf(fact_41_add__0__iff, axiom,
    ((![B : nat, A : nat]: ((B = (plus_plus_nat @ B @ A)) = (A = zero_zero_nat))))). % add_0_iff
thf(fact_42_order__less__irrefl, axiom,
    ((![X : $o]: (~ ((ord_less_o @ X @ X)))))). % order_less_irrefl
thf(fact_43_order__less__irrefl, axiom,
    ((![X : nat]: (~ ((ord_less_nat @ X @ X)))))). % order_less_irrefl
thf(fact_44_comm__monoid_Ocomm__neutral, axiom,
    ((![F : nat > nat > nat, Z : nat, A : nat]: ((comm_monoid_nat @ F @ Z) => ((F @ A @ Z) = A))))). % comm_monoid.comm_neutral
thf(fact_45_One__nat__def, axiom,
    ((one_one_nat = (suc @ zero_zero_nat)))). % One_nat_def
thf(fact_46_nat__arith_Orule0, axiom,
    ((![A : nat]: (A = (plus_plus_nat @ A @ zero_zero_nat))))). % nat_arith.rule0
thf(fact_47_add__mono__thms__linordered__semiring_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (K = L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(3)
thf(fact_48_o__apply, axiom,
    ((comp_nat_nat_nat = (^[F2 : nat > nat]: (^[G : nat > nat]: (^[X2 : nat]: (F2 @ (G @ X2)))))))). % o_apply
thf(fact_49_ord__eq__le__trans, axiom,
    ((![A : $o, B : $o, C : $o]: ((A = B) => ((ord_less_eq_o @ B @ C) => (ord_less_eq_o @ A @ C)))))). % ord_eq_le_trans
thf(fact_50_ord__eq__le__trans, axiom,
    ((![A : nat, B : nat, C : nat]: ((A = B) => ((ord_less_eq_nat @ B @ C) => (ord_less_eq_nat @ A @ C)))))). % ord_eq_le_trans
thf(fact_51_order__antisym, axiom,
    ((![X : $o, Y : $o]: ((ord_less_eq_o @ X @ Y) => ((ord_less_eq_o @ Y @ X) => (X = Y)))))). % order_antisym
thf(fact_52_order__antisym, axiom,
    ((![X : nat, Y : nat]: ((ord_less_eq_nat @ X @ Y) => ((ord_less_eq_nat @ Y @ X) => (X = Y)))))). % order_antisym
thf(fact_53_le__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel1
thf(fact_54_le__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_eq_nat @ zero_zero_nat @ B))))). % le_add_same_cancel2
thf(fact_55_order__trans, axiom,
    ((![X : $o, Y : $o, Z : $o]: ((ord_less_eq_o @ X @ Y) => ((ord_less_eq_o @ Y @ Z) => (ord_less_eq_o @ X @ Z)))))). % order_trans
thf(fact_56_order__trans, axiom,
    ((![X : nat, Y : nat, Z : nat]: ((ord_less_eq_nat @ X @ Y) => ((ord_less_eq_nat @ Y @ Z) => (ord_less_eq_nat @ X @ Z)))))). % order_trans
thf(fact_57_add__mono__thms__linordered__field_I3_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (ord_less_eq_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(3)
thf(fact_58_le__zero__eq, axiom,
    ((![N : nat]: ((ord_less_eq_nat @ N @ zero_zero_nat) = (N = zero_zero_nat))))). % le_zero_eq
thf(fact_59_add__le__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel1
thf(fact_60_add__le__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_eq_nat @ A @ zero_zero_nat))))). % add_le_same_cancel2
thf(fact_61_add__mono__thms__linordered__field_I4_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_eq_nat @ I @ J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(4)
thf(fact_62_add__less__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_nat @ A @ B))))). % add_less_cancel_right
thf(fact_63_zero__le, axiom,
    ((![X : nat]: (ord_less_eq_nat @ zero_zero_nat @ X)))). % zero_le
thf(fact_64_semigroup_Oassoc, axiom,
    ((![F : nat > nat > nat, A : nat, B : nat, C : nat]: ((semigroup_nat @ F) => ((F @ (F @ A @ B) @ C) = (F @ A @ (F @ B @ C))))))). % semigroup.assoc
thf(fact_65_add__mono__thms__linordered__field_I1_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (K = L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(1)
thf(fact_66_not__gr__zero, axiom,
    ((![N : nat]: ((~ ((ord_less_nat @ zero_zero_nat @ N))) = (N = zero_zero_nat))))). % not_gr_zero
thf(fact_67_add__le__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (ord_less_eq_nat @ A @ B))))). % add_le_cancel_right
thf(fact_68_add__less__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (ord_less_nat @ A @ B))))). % add_less_cancel_left
thf(fact_69_add__mono__thms__linordered__field_I5_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((ord_less_nat @ I @ J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(5)
thf(fact_70_add__mono__thms__linordered__semiring_I2_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (ord_less_eq_nat @ K @ L)) => (ord_less_eq_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_semiring(2)
thf(fact_71_add__mono__thms__linordered__field_I2_J, axiom,
    ((![I : nat, J : nat, K : nat, L : nat]: (((I = J) & (ord_less_nat @ K @ L)) => (ord_less_nat @ (plus_plus_nat @ I @ K) @ (plus_plus_nat @ J @ L)))))). % add_mono_thms_linordered_field(2)
thf(fact_72_linorder__not__less, axiom,
    ((![X : $o, Y : $o]: ((~ ((ord_less_o @ X @ Y))) = (ord_less_eq_o @ Y @ X))))). % linorder_not_less
thf(fact_73_linorder__not__less, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_nat @ X @ Y))) = (ord_less_eq_nat @ Y @ X))))). % linorder_not_less
thf(fact_74_nat_Osimps_I3_J, axiom,
    ((![X22 : nat]: ((suc @ X22) != zero_zero_nat)))). % nat.simps(3)
thf(fact_75_o__def, axiom,
    ((comp_nat_nat_nat = (^[F2 : nat > nat]: (^[G : nat > nat]: (^[X2 : nat]: (F2 @ (G @ X2)))))))). % o_def
thf(fact_76_add__less__same__cancel1, axiom,
    ((![B : nat, A : nat]: ((ord_less_nat @ (plus_plus_nat @ B @ A) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel1
thf(fact_77_add__less__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ B) @ B) = (ord_less_nat @ A @ zero_zero_nat))))). % add_less_same_cancel2
thf(fact_78_less__add__same__cancel1, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ A @ B)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel1
thf(fact_79_add__diff__cancel__left_H, axiom,
    ((![A : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ A @ B) @ A) = B)))). % add_diff_cancel_left'
thf(fact_80_mult__1, axiom,
    ((![A : nat]: ((times_times_nat @ one_one_nat @ A) = A)))). % mult_1
thf(fact_81_not__less__zero, axiom,
    ((![N : nat]: (~ ((ord_less_nat @ N @ zero_zero_nat)))))). % not_less_zero
thf(fact_82_order__less__le, axiom,
    ((ord_less_o = (^[X2 : $o]: (^[Y2 : $o]: (((ord_less_eq_o @ X2 @ Y2)) & ((~ ((X2 = Y2)))))))))). % order_less_le
thf(fact_83_order__less__le, axiom,
    ((ord_less_nat = (^[X2 : nat]: (^[Y2 : nat]: (((ord_less_eq_nat @ X2 @ Y2)) & ((~ ((X2 = Y2)))))))))). % order_less_le
thf(fact_84_bot__bool__def, axiom,
    ((~ (bot_bot_o)))). % bot_bool_def
thf(fact_85_less__add__same__cancel2, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ (plus_plus_nat @ B @ A)) = (ord_less_nat @ zero_zero_nat @ B))))). % less_add_same_cancel2
thf(fact_86_antisym, axiom,
    ((![A : $o, B : $o]: ((ord_less_eq_o @ A @ B) => ((ord_less_eq_o @ B @ A) => (A = B)))))). % antisym
thf(fact_87_antisym, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_eq_nat @ B @ A) => (A = B)))))). % antisym
thf(fact_88_mult_Oright__neutral, axiom,
    ((![A : nat]: ((times_times_nat @ A @ one_one_nat) = A)))). % mult.right_neutral
thf(fact_89_le__iff__add, axiom,
    ((ord_less_eq_nat = (^[A4 : nat]: (^[B4 : nat]: (?[C3 : nat]: (B4 = (plus_plus_nat @ A4 @ C3)))))))). % le_iff_add
thf(fact_90_order__eq__refl, axiom,
    ((![X : $o, Y : $o]: ((X = Y) => (ord_less_eq_o @ X @ Y))))). % order_eq_refl
thf(fact_91_order__eq__refl, axiom,
    ((![X : nat, Y : nat]: ((X = Y) => (ord_less_eq_nat @ X @ Y))))). % order_eq_refl
thf(fact_92_add__le__less__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_le_less_mono
thf(fact_93_add__diff__cancel__right_H, axiom,
    ((![A : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ A @ B) @ B) = A)))). % add_diff_cancel_right'
thf(fact_94_add__less__le__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_nat @ A @ B) => ((ord_less_eq_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_less_le_mono
thf(fact_95_add__Suc, axiom,
    ((![M : nat, N : nat]: ((plus_plus_nat @ (suc @ M) @ N) = (suc @ (plus_plus_nat @ M @ N)))))). % add_Suc
thf(fact_96_add__pos__nonneg, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ zero_zero_nat @ B) => (ord_less_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_pos_nonneg
thf(fact_97_add__strict__increasing2, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_nat @ B @ C) => (ord_less_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_strict_increasing2
thf(fact_98_less__eqE, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ B) => (~ ((![C2 : nat]: (B != (plus_plus_nat @ A @ C2))))))))). % less_eqE
thf(fact_99_comm__monoid__mult__class_Omult__1, axiom,
    ((![A : nat]: ((times_times_nat @ one_one_nat @ A) = A)))). % comm_monoid_mult_class.mult_1
thf(fact_100_add__strict__increasing, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ B @ C) => (ord_less_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_strict_increasing
thf(fact_101_add__neg__nonpos, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ zero_zero_nat) => ((ord_less_eq_nat @ B @ zero_zero_nat) => (ord_less_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_neg_nonpos
thf(fact_102_verit__comp__simplify1_I3_J, axiom,
    ((![B5 : $o, A5 : $o]: ((~ ((ord_less_eq_o @ B5 @ A5))) = (ord_less_o @ A5 @ B5))))). % verit_comp_simplify1(3)
thf(fact_103_verit__comp__simplify1_I3_J, axiom,
    ((![B5 : nat, A5 : nat]: ((~ ((ord_less_eq_nat @ B5 @ A5))) = (ord_less_nat @ A5 @ B5))))). % verit_comp_simplify1(3)
thf(fact_104_add__nonpos__neg, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ zero_zero_nat) => ((ord_less_nat @ B @ zero_zero_nat) => (ord_less_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_nonpos_neg
thf(fact_105_add__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_eq_nat @ A @ B) => ((ord_less_eq_nat @ C @ D) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_mono
thf(fact_106_add__right__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ A @ B) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)))))). % add_right_mono
thf(fact_107_verit__comp__simplify1_I2_J, axiom,
    ((![A : $o]: (ord_less_eq_o @ A @ A)))). % verit_comp_simplify1(2)
thf(fact_108_verit__comp__simplify1_I2_J, axiom,
    ((![A : nat]: (ord_less_eq_nat @ A @ A)))). % verit_comp_simplify1(2)
thf(fact_109_add__nonneg__pos, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_nat @ zero_zero_nat @ B) => (ord_less_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_nonneg_pos
thf(fact_110_mult_Ocommute, axiom,
    ((times_times_nat = (^[A4 : nat]: (^[B4 : nat]: (times_times_nat @ B4 @ A4)))))). % mult.commute
thf(fact_111_add__left__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ A @ B) => (ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)))))). % add_left_mono
thf(fact_112_distrib__left, axiom,
    ((![A : nat, B : nat, C : nat]: ((times_times_nat @ A @ (plus_plus_nat @ B @ C)) = (plus_plus_nat @ (times_times_nat @ A @ B) @ (times_times_nat @ A @ C)))))). % distrib_left
thf(fact_113_verit__comp__simplify1_I1_J, axiom,
    ((![A : $o]: (~ ((ord_less_o @ A @ A)))))). % verit_comp_simplify1(1)
thf(fact_114_verit__comp__simplify1_I1_J, axiom,
    ((![A : nat]: (~ ((ord_less_nat @ A @ A)))))). % verit_comp_simplify1(1)
thf(fact_115_canonically__ordered__monoid__add__class_OlessE, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ B) => (~ ((![C2 : nat]: ((B = (plus_plus_nat @ A @ C2)) => (C2 = zero_zero_nat))))))))). % canonically_ordered_monoid_add_class.lessE
thf(fact_116_add__strict__mono, axiom,
    ((![A : nat, B : nat, C : nat, D : nat]: ((ord_less_nat @ A @ B) => ((ord_less_nat @ C @ D) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ D))))))). % add_strict_mono
thf(fact_117_add__less__imp__less__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) => (ord_less_nat @ A @ B))))). % add_less_imp_less_right
thf(fact_118_verit__la__disequality, axiom,
    ((![A : $o, B : $o]: ((A = B) | ((~ ((ord_less_eq_o @ A @ B))) | (~ ((ord_less_eq_o @ B @ A)))))))). % verit_la_disequality
thf(fact_119_verit__la__disequality, axiom,
    ((![A : nat, B : nat]: ((A = B) | ((~ ((ord_less_eq_nat @ A @ B))) | (~ ((ord_less_eq_nat @ B @ A)))))))). % verit_la_disequality
thf(fact_120_add__less__imp__less__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) => (ord_less_nat @ A @ B))))). % add_less_imp_less_left
thf(fact_121_add__strict__right__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ A @ B) => (ord_less_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)))))). % add_strict_right_mono
thf(fact_122_comm__semiring__class_Odistrib, axiom,
    ((![A : nat, B : nat, C : nat]: ((times_times_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ (times_times_nat @ A @ C) @ (times_times_nat @ B @ C)))))). % comm_semiring_class.distrib
thf(fact_123_le__boolI_H, axiom,
    ((![P : $o, Q : $o]: ((P => Q) => (ord_less_eq_o @ P @ Q))))). % le_boolI'
thf(fact_124_add__strict__left__mono, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ A @ B) => (ord_less_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)))))). % add_strict_left_mono
thf(fact_125_zero__less__iff__neq__zero, axiom,
    ((![N : nat]: ((ord_less_nat @ zero_zero_nat @ N) = (~ ((N = zero_zero_nat))))))). % zero_less_iff_neq_zero
thf(fact_126_gr__implies__not__zero, axiom,
    ((![M : nat, N : nat]: ((ord_less_nat @ M @ N) => (N != zero_zero_nat))))). % gr_implies_not_zero
thf(fact_127_nle__le, axiom,
    ((![A : $o, B : $o]: ((~ ((ord_less_eq_o @ A @ B))) = (((ord_less_eq_o @ B @ A)) & ((~ ((B = A))))))))). % nle_le
thf(fact_128_nle__le, axiom,
    ((![A : nat, B : nat]: ((~ ((ord_less_eq_nat @ A @ B))) = (((ord_less_eq_nat @ B @ A)) & ((~ ((B = A))))))))). % nle_le
thf(fact_129_bot__nat__0_Onot__eq__extremum, axiom,
    ((![A : nat]: ((~ ((A = zero_zero_nat))) = (ord_less_nat @ zero_zero_nat @ A))))). % bot_nat_0.not_eq_extremum
thf(fact_130_add__le__imp__le__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) => (ord_less_eq_nat @ A @ B))))). % add_le_imp_le_left
thf(fact_131_add__le__imp__le__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) => (ord_less_eq_nat @ A @ B))))). % add_le_imp_le_right
thf(fact_132_gr__zeroI, axiom,
    ((![N : nat]: ((N != zero_zero_nat) => (ord_less_nat @ zero_zero_nat @ N))))). % gr_zeroI
thf(fact_133_add__pos__pos, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_nat @ zero_zero_nat @ B) => (ord_less_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_pos_pos
thf(fact_134_numeral__One, axiom,
    (((numeral_numeral_nat @ one) = one_one_nat))). % numeral_One
thf(fact_135_add__nonneg__nonneg, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ zero_zero_nat @ B) => (ord_less_eq_nat @ zero_zero_nat @ (plus_plus_nat @ A @ B))))))). % add_nonneg_nonneg
thf(fact_136_less__numeral__extra_I3_J, axiom,
    ((~ ((ord_less_nat @ zero_zero_nat @ zero_zero_nat))))). % less_numeral_extra(3)
thf(fact_137_le__numeral__extra_I3_J, axiom,
    ((ord_less_eq_nat @ zero_zero_nat @ zero_zero_nat))). % le_numeral_extra(3)
thf(fact_138_nless__le, axiom,
    ((![A : $o, B : $o]: ((~ ((ord_less_o @ A @ B))) = (((~ ((ord_less_eq_o @ A @ B)))) | ((A = B))))))). % nless_le
thf(fact_139_nless__le, axiom,
    ((![A : nat, B : nat]: ((~ ((ord_less_nat @ A @ B))) = (((~ ((ord_less_eq_nat @ A @ B)))) | ((A = B))))))). % nless_le
thf(fact_140_nat__arith_Osuc1, axiom,
    ((![A3 : nat, K : nat, A : nat]: ((A3 = (plus_plus_nat @ K @ A)) => ((suc @ A3) = (plus_plus_nat @ K @ (suc @ A))))))). % nat_arith.suc1
thf(fact_141_add__nonneg__eq__0__iff, axiom,
    ((![X : nat, Y : nat]: ((ord_less_eq_nat @ zero_zero_nat @ X) => ((ord_less_eq_nat @ zero_zero_nat @ Y) => (((plus_plus_nat @ X @ Y) = zero_zero_nat) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))))). % add_nonneg_eq_0_iff
thf(fact_142_add__neg__neg, axiom,
    ((![A : nat, B : nat]: ((ord_less_nat @ A @ zero_zero_nat) => ((ord_less_nat @ B @ zero_zero_nat) => (ord_less_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_neg_neg
thf(fact_143_linorder__linear, axiom,
    ((![X : $o, Y : $o]: ((ord_less_eq_o @ X @ Y) | (ord_less_eq_o @ Y @ X))))). % linorder_linear
thf(fact_144_linorder__linear, axiom,
    ((![X : nat, Y : nat]: ((ord_less_eq_nat @ X @ Y) | (ord_less_eq_nat @ Y @ X))))). % linorder_linear
thf(fact_145_add__nonpos__eq__0__iff, axiom,
    ((![X : nat, Y : nat]: ((ord_less_eq_nat @ X @ zero_zero_nat) => ((ord_less_eq_nat @ Y @ zero_zero_nat) => (((plus_plus_nat @ X @ Y) = zero_zero_nat) = (((X = zero_zero_nat)) & ((Y = zero_zero_nat))))))))). % add_nonpos_eq_0_iff
thf(fact_146_ord__le__eq__trans, axiom,
    ((![A : $o, B : $o, C : $o]: ((ord_less_eq_o @ A @ B) => ((B = C) => (ord_less_eq_o @ A @ C)))))). % ord_le_eq_trans
thf(fact_147_ord__le__eq__trans, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ A @ B) => ((B = C) => (ord_less_eq_nat @ A @ C)))))). % ord_le_eq_trans
thf(fact_148_linorder__not__le, axiom,
    ((![X : $o, Y : $o]: ((~ ((ord_less_eq_o @ X @ Y))) = (ord_less_o @ Y @ X))))). % linorder_not_le
thf(fact_149_linorder__not__le, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_eq_nat @ X @ Y))) = (ord_less_nat @ Y @ X))))). % linorder_not_le
thf(fact_150_add__increasing, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_eq_nat @ zero_zero_nat @ A) => ((ord_less_eq_nat @ B @ C) => (ord_less_eq_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_increasing
thf(fact_151_add__nonpos__nonpos, axiom,
    ((![A : nat, B : nat]: ((ord_less_eq_nat @ A @ zero_zero_nat) => ((ord_less_eq_nat @ B @ zero_zero_nat) => (ord_less_eq_nat @ (plus_plus_nat @ A @ B) @ zero_zero_nat)))))). % add_nonpos_nonpos
thf(fact_152_add__increasing2, axiom,
    ((![C : nat, B : nat, A : nat]: ((ord_less_eq_nat @ zero_zero_nat @ C) => ((ord_less_eq_nat @ B @ A) => (ord_less_eq_nat @ B @ (plus_plus_nat @ A @ C))))))). % add_increasing2
thf(fact_153_add__decreasing, axiom,
    ((![A : nat, C : nat, B : nat]: ((ord_less_eq_nat @ A @ zero_zero_nat) => ((ord_less_eq_nat @ C @ B) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ B)))))). % add_decreasing
thf(fact_154_bot__nat__0_Oextremum, axiom,
    ((![A : nat]: (ord_less_eq_nat @ zero_zero_nat @ A)))). % bot_nat_0.extremum
thf(fact_155_add__decreasing2, axiom,
    ((![C : nat, A : nat, B : nat]: ((ord_less_eq_nat @ C @ zero_zero_nat) => ((ord_less_eq_nat @ A @ B) => (ord_less_eq_nat @ (plus_plus_nat @ A @ C) @ B)))))). % add_decreasing2
thf(fact_156_add__diff__cancel__left, axiom,
    ((![C : nat, A : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ C @ A) @ (plus_plus_nat @ C @ B)) = (minus_minus_nat @ A @ B))))). % add_diff_cancel_left
thf(fact_157_order__le__less, axiom,
    ((ord_less_eq_o = (^[X2 : $o]: (^[Y2 : $o]: (((ord_less_o @ X2 @ Y2)) | ((X2 = Y2)))))))). % order_le_less
thf(fact_158_order__le__less, axiom,
    ((ord_less_eq_nat = (^[X2 : nat]: (^[Y2 : nat]: (((ord_less_nat @ X2 @ Y2)) | ((X2 = Y2)))))))). % order_le_less
thf(fact_159_pos__add__strict, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ zero_zero_nat @ A) => ((ord_less_nat @ B @ C) => (ord_less_nat @ B @ (plus_plus_nat @ A @ C))))))). % pos_add_strict
thf(fact_160_sum_OatLeastAtMost__rev, axiom,
    ((![G2 : nat > nat, N : nat, M : nat]: ((groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ N @ M)) = (groups1842438620at_nat @ (^[I2 : nat]: (G2 @ (minus_minus_nat @ (plus_plus_nat @ M @ N) @ I2))) @ (set_or601162459st_nat @ N @ M)))))). % sum.atLeastAtMost_rev
thf(fact_161_sum_OSuc__reindex__ivl, axiom,
    ((![M : nat, N : nat, G2 : nat > nat]: ((ord_less_eq_nat @ M @ N) => ((plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ M @ N)) @ (G2 @ (suc @ N))) = (plus_plus_nat @ (G2 @ M) @ (groups1842438620at_nat @ (^[I2 : nat]: (G2 @ (suc @ I2))) @ (set_or601162459st_nat @ M @ N)))))))). % sum.Suc_reindex_ivl
thf(fact_162_le__boolD, axiom,
    ((![P : $o, Q : $o]: ((ord_less_eq_o @ P @ Q) => (P => Q))))). % le_boolD
thf(fact_163_order__antisym__conv, axiom,
    ((![Y : $o, X : $o]: ((ord_less_eq_o @ Y @ X) => ((ord_less_eq_o @ X @ Y) = (X = Y)))))). % order_antisym_conv
thf(fact_164_order__antisym__conv, axiom,
    ((![Y : nat, X : nat]: ((ord_less_eq_nat @ Y @ X) => ((ord_less_eq_nat @ X @ Y) = (X = Y)))))). % order_antisym_conv
thf(fact_165_less__le__not__le, axiom,
    ((ord_less_o = (^[X2 : $o]: (^[Y2 : $o]: (((ord_less_eq_o @ X2 @ Y2)) & ((~ ((ord_less_eq_o @ Y2 @ X2)))))))))). % less_le_not_le
thf(fact_166_less__le__not__le, axiom,
    ((ord_less_nat = (^[X2 : nat]: (^[Y2 : nat]: (((ord_less_eq_nat @ X2 @ Y2)) & ((~ ((ord_less_eq_nat @ Y2 @ X2)))))))))). % less_le_not_le
thf(fact_167_diff__zero, axiom,
    ((![A : nat]: ((minus_minus_nat @ A @ zero_zero_nat) = A)))). % diff_zero
thf(fact_168_order__less__imp__le, axiom,
    ((![X : $o, Y : $o]: ((ord_less_o @ X @ Y) => (ord_less_eq_o @ X @ Y))))). % order_less_imp_le
thf(fact_169_order__less__imp__le, axiom,
    ((![X : nat, Y : nat]: ((ord_less_nat @ X @ Y) => (ord_less_eq_nat @ X @ Y))))). % order_less_imp_le
thf(fact_170_sum_OatLeast0__atMost__Suc, axiom,
    ((![G2 : nat > nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ zero_zero_nat @ (suc @ N))) = (plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ zero_zero_nat @ N)) @ (G2 @ (suc @ N))))))). % sum.atLeast0_atMost_Suc
thf(fact_171_mult__zero__left, axiom,
    ((![A : nat]: ((times_times_nat @ zero_zero_nat @ A) = zero_zero_nat)))). % mult_zero_left
thf(fact_172_sum_OatLeastLessThan__concat, axiom,
    ((![M : nat, N : nat, P2 : nat, G2 : nat > nat]: ((ord_less_eq_nat @ M @ N) => ((ord_less_eq_nat @ N @ P2) => ((plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ M @ N)) @ (groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ N @ P2))) = (groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ M @ P2)))))))). % sum.atLeastLessThan_concat
thf(fact_173_Suc__eq__plus1, axiom,
    ((suc = (^[N2 : nat]: (plus_plus_nat @ N2 @ one_one_nat))))). % Suc_eq_plus1
thf(fact_174_sum_OatLeast0__atMost__Suc__shift, axiom,
    ((![G2 : nat > nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ zero_zero_nat @ (suc @ N))) = (plus_plus_nat @ (G2 @ zero_zero_nat) @ (groups1842438620at_nat @ (comp_nat_nat_nat @ G2 @ suc) @ (set_or601162459st_nat @ zero_zero_nat @ N))))))). % sum.atLeast0_atMost_Suc_shift
thf(fact_175_distrib__right, axiom,
    ((![A : nat, B : nat, C : nat]: ((times_times_nat @ (plus_plus_nat @ A @ B) @ C) = (plus_plus_nat @ (times_times_nat @ A @ C) @ (times_times_nat @ B @ C)))))). % distrib_right
thf(fact_176_order__le__less__trans, axiom,
    ((![X : $o, Y : $o, Z : $o]: ((ord_less_eq_o @ X @ Y) => ((ord_less_o @ Y @ Z) => (ord_less_o @ X @ Z)))))). % order_le_less_trans
thf(fact_177_order__le__less__trans, axiom,
    ((![X : nat, Y : nat, Z : nat]: ((ord_less_eq_nat @ X @ Y) => ((ord_less_nat @ Y @ Z) => (ord_less_nat @ X @ Z)))))). % order_le_less_trans
thf(fact_178_mult__zero__right, axiom,
    ((![A : nat]: ((times_times_nat @ A @ zero_zero_nat) = zero_zero_nat)))). % mult_zero_right
thf(fact_179_sum_OatLeast0__lessThan__Suc, axiom,
    ((![G2 : nat > nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ zero_zero_nat @ (suc @ N))) = (plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ zero_zero_nat @ N)) @ (G2 @ N)))))). % sum.atLeast0_lessThan_Suc
thf(fact_180_order__less__le__trans, axiom,
    ((![X : $o, Y : $o, Z : $o]: ((ord_less_o @ X @ Y) => ((ord_less_eq_o @ Y @ Z) => (ord_less_o @ X @ Z)))))). % order_less_le_trans
thf(fact_181_order__less__le__trans, axiom,
    ((![X : nat, Y : nat, Z : nat]: ((ord_less_nat @ X @ Y) => ((ord_less_eq_nat @ Y @ Z) => (ord_less_nat @ X @ Z)))))). % order_less_le_trans
thf(fact_182_ord__less__eq__trans, axiom,
    ((![A : $o, B : $o, C : $o]: ((ord_less_o @ A @ B) => ((B = C) => (ord_less_o @ A @ C)))))). % ord_less_eq_trans
thf(fact_183_ord__less__eq__trans, axiom,
    ((![A : nat, B : nat, C : nat]: ((ord_less_nat @ A @ B) => ((B = C) => (ord_less_nat @ A @ C)))))). % ord_less_eq_trans
thf(fact_184_one__add__one, axiom,
    (((plus_plus_nat @ one_one_nat @ one_one_nat) = (numeral_numeral_nat @ (bit0 @ one))))). % one_add_one
thf(fact_185_leI, axiom,
    ((![X : $o, Y : $o]: ((~ ((ord_less_o @ X @ Y))) => (ord_less_eq_o @ Y @ X))))). % leI
thf(fact_186_leI, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_nat @ X @ Y))) => (ord_less_eq_nat @ Y @ X))))). % leI
thf(fact_187_bot__nat__0_Oextremum__unique, axiom,
    ((![A : nat]: ((ord_less_eq_nat @ A @ zero_zero_nat) = (A = zero_zero_nat))))). % bot_nat_0.extremum_unique
thf(fact_188_add_Osemigroup__axioms, axiom,
    ((semigroup_nat @ plus_plus_nat))). % add.semigroup_axioms
thf(fact_189_sum_OatLeast0__lessThan__Suc__shift, axiom,
    ((![G2 : nat > nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ zero_zero_nat @ (suc @ N))) = (plus_plus_nat @ (G2 @ zero_zero_nat) @ (groups1842438620at_nat @ (comp_nat_nat_nat @ G2 @ suc) @ (set_or562006527an_nat @ zero_zero_nat @ N))))))). % sum.atLeast0_lessThan_Suc_shift
thf(fact_190_order__less__trans, axiom,
    ((![X : $o, Y : $o, Z : $o]: ((ord_less_o @ X @ Y) => ((ord_less_o @ Y @ Z) => (ord_less_o @ X @ Z)))))). % order_less_trans
thf(fact_191_order__less__trans, axiom,
    ((![X : nat, Y : nat, Z : nat]: ((ord_less_nat @ X @ Y) => ((ord_less_nat @ Y @ Z) => (ord_less_nat @ X @ Z)))))). % order_less_trans
thf(fact_192_sum_OatLeastLessThan__rev, axiom,
    ((![G2 : nat > nat, N : nat, M : nat]: ((groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ N @ M)) = (groups1842438620at_nat @ (^[I2 : nat]: (G2 @ (minus_minus_nat @ (plus_plus_nat @ M @ N) @ (suc @ I2)))) @ (set_or562006527an_nat @ N @ M)))))). % sum.atLeastLessThan_rev
thf(fact_193_order__refl, axiom,
    ((![X : $o]: (ord_less_eq_o @ X @ X)))). % order_refl
thf(fact_194_order__refl, axiom,
    ((![X : nat]: (ord_less_eq_nat @ X @ X)))). % order_refl
thf(fact_195_sum_OatLeastAtMost__shift__0, axiom,
    ((![M : nat, N : nat, G2 : nat > nat]: ((ord_less_eq_nat @ M @ N) => ((groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ M @ N)) = (groups1842438620at_nat @ (comp_nat_nat_nat @ G2 @ (plus_plus_nat @ M)) @ (set_or601162459st_nat @ zero_zero_nat @ (minus_minus_nat @ N @ M)))))))). % sum.atLeastAtMost_shift_0
thf(fact_196_add_Oabel__semigroup__axioms, axiom,
    ((abel_semigroup_nat @ plus_plus_nat))). % add.abel_semigroup_axioms
thf(fact_197_mult_Oassoc, axiom,
    ((![A : nat, B : nat, C : nat]: ((times_times_nat @ (times_times_nat @ A @ B) @ C) = (times_times_nat @ A @ (times_times_nat @ B @ C)))))). % mult.assoc
thf(fact_198_sum_OatLeastAtMost__shift__bounds, axiom,
    ((![G2 : nat > nat, M : nat, K : nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_or601162459st_nat @ (plus_plus_nat @ M @ K) @ (plus_plus_nat @ N @ K))) = (groups1842438620at_nat @ (comp_nat_nat_nat @ G2 @ (plus_plus_nat @ K)) @ (set_or601162459st_nat @ M @ N)))))). % sum.atLeastAtMost_shift_bounds
thf(fact_199_comm__monoid__def, axiom,
    ((comm_monoid_nat = (^[F2 : nat > nat > nat]: (^[Z2 : nat]: (((abel_semigroup_nat @ F2)) & ((comm_m2051353214ms_nat @ F2 @ Z2)))))))). % comm_monoid_def
thf(fact_200_of__bool__eq_I2_J, axiom,
    (((zero_n1356753679ol_nat @ ($true)) = one_one_nat))). % of_bool_eq(2)
thf(fact_201_linorder__le__cases, axiom,
    ((![X : $o, Y : $o]: ((~ ((ord_less_eq_o @ X @ Y))) => (ord_less_eq_o @ Y @ X))))). % linorder_le_cases
thf(fact_202_linorder__le__cases, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_eq_nat @ X @ Y))) => (ord_less_eq_nat @ Y @ X))))). % linorder_le_cases
thf(fact_203_sum_OatMost__Suc, axiom,
    ((![G2 : nat > nat, N : nat]: ((groups1842438620at_nat @ G2 @ (set_ord_atMost_nat @ (suc @ N))) = (plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_ord_atMost_nat @ N)) @ (G2 @ (suc @ N))))))). % sum.atMost_Suc
thf(fact_204_linorder__less__linear, axiom,
    ((![X : $o, Y : $o]: ((ord_less_o @ X @ Y) | ((X = Y) | (ord_less_o @ Y @ X)))))). % linorder_less_linear
thf(fact_205_linorder__less__linear, axiom,
    ((![X : nat, Y : nat]: ((ord_less_nat @ X @ Y) | ((X = Y) | (ord_less_nat @ Y @ X)))))). % linorder_less_linear
thf(fact_206_add__diff__cancel__right, axiom,
    ((![A : nat, C : nat, B : nat]: ((minus_minus_nat @ (plus_plus_nat @ A @ C) @ (plus_plus_nat @ B @ C)) = (minus_minus_nat @ A @ B))))). % add_diff_cancel_right
thf(fact_207_sum_OatLeastLessThan__Suc, axiom,
    ((![A : nat, B : nat, G2 : nat > nat]: ((ord_less_eq_nat @ A @ B) => ((groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ A @ (suc @ B))) = (plus_plus_nat @ (groups1842438620at_nat @ G2 @ (set_or562006527an_nat @ A @ B)) @ (G2 @ B))))))). % sum.atLeastLessThan_Suc
thf(fact_208_Orderings_Oorder__eq__iff, axiom,
    (((^[Y3 : $o]: (^[Z3 : $o]: (Y3 = Z3))) = (^[A4 : $o]: (^[B4 : $o]: (((ord_less_eq_o @ A4 @ B4)) & ((ord_less_eq_o @ B4 @ A4)))))))). % Orderings.order_eq_iff
thf(fact_209_Orderings_Oorder__eq__iff, axiom,
    (((^[Y3 : nat]: (^[Z3 : nat]: (Y3 = Z3))) = (^[A4 : nat]: (^[B4 : nat]: (((ord_less_eq_nat @ A4 @ B4)) & ((ord_less_eq_nat @ B4 @ A4)))))))). % Orderings.order_eq_iff
thf(fact_210_less__imp__neq, axiom,
    ((![X : $o, Y : $o]: ((ord_less_o @ X @ Y) => (X != Y))))). % less_imp_neq
thf(fact_211_less__imp__neq, axiom,
    ((![X : nat, Y : nat]: ((ord_less_nat @ X @ Y) => (X != Y))))). % less_imp_neq
thf(fact_212_linorder__neqE, axiom,
    ((![X : $o, Y : $o]: ((X = (~ (Y))) => ((~ ((ord_less_o @ X @ Y))) => (ord_less_o @ Y @ X)))))). % linorder_neqE
thf(fact_213_linorder__neqE, axiom,
    ((![X : nat, Y : nat]: ((X != Y) => ((~ ((ord_less_nat @ X @ Y))) => (ord_less_nat @ Y @ X)))))). % linorder_neqE
thf(fact_214_less__induct, axiom,
    ((![P : nat > $o, A : nat]: ((![X3 : nat]: ((![Y4 : nat]: ((ord_less_nat @ Y4 @ X3) => (P @ Y4))) => (P @ X3))) => (P @ A))))). % less_induct
thf(fact_215_not__less__iff__gr__or__eq, axiom,
    ((![X : $o, Y : $o]: ((~ ((ord_less_o @ X @ Y))) = (((ord_less_o @ Y @ X)) | ((X = Y))))))). % not_less_iff_gr_or_eq
thf(fact_216_not__less__iff__gr__or__eq, axiom,
    ((![X : nat, Y : nat]: ((~ ((ord_less_nat @ X @ Y))) = (((ord_less_nat @ Y @ X)) | ((X = Y))))))). % not_less_iff_gr_or_eq
thf(fact_217_Nat_Oadd__0__right, axiom,
    ((![M : nat]: ((plus_plus_nat @ M @ zero_zero_nat) = M)))). % Nat.add_0_right
thf(fact_218_inj__on__add_H, axiom,
    ((![A : nat, A3 : set_nat]: (inj_on_nat_nat @ (^[B4 : nat]: (plus_plus_nat @ B4 @ A)) @ A3)))). % inj_on_add'

% Conjectures (1)
thf(conj_0, conjecture,
    (((plus_plus_a @ x @ y) = (plus_plus_a @ y @ x)))).
